### ISSUE TITLE
can set default value in content_type fields?

### ISSUE THREAD

**Issue by hw676018683** [locomotivecms/engine#1014]
i want set a default value to a field of a content_type, any solution?

**Comment by neversion** [comment]
I meet the same question. anyone got any idea?

**Comment by did** [comment]
Good feature. This needs to be implemented in https://github.com/locomotivecms/custom_fields and https://github.com/locomotivecms/steam.

**Comment by did** [comment]
works with the following types: :string, :text, :color, :select, :boolean, :email, :integer and :float.

Will be shipped in the next version of Engine and Wagon.
