### ISSUE TITLE
Scenario: Public_submission multipart/form-data engine field require 3x image data email file not found error

### ISSUE THREAD

**Issue by creativefingers** [locomotivecms/engine#1015]
Hi Did,

First, I would like to tell you of rails locomotive cms is a super ride and I support him as I can. I am drafting the first loco project now, and I already know, me from expecting another two projects in the order that I want to write the rails locomotive. I like the rails and I like it much connected with the classic locomotive engine rails app!
My problem is:

[1]. Problem model email form > upload + send 3 fields file from form from
{{ contents.advertises.public_submission_url }}
I have a model form which is also '3 fields file'

a) Scenario: If I define require in engine admin and send this, I get this error
Photo1 - can't be blank
Photo2 - can't be blank
Photo3 - can't be blank

b) Scenario: If I do no require in engine admin and I have only require with javascript foundation field control require, I this email send, I do not see error and in gmail I see only 3x word 'file'
with this url 'sites/54381ed9969adbdd45000002/content_entry547d7cdaa6929500ed000108/547da9f6a69295847d0000e9/files'

PS: I try add this 'attachments["file.jpg"] = File.read("#{Rails.root}/public/tmp/file.jpg")' fix attachments for control to class Notifications < ActionMailer::Base
yes but at the moment I see this attachments at every emails from my 4 email models

Locomotivecms can not add files upload and we have to write it myself?
Pushing me time, client and run the project therefore I this problem solved for the moment definition iframe post php, but I am sorry for such solutions
It's NOT pure work and as a developer I am very unhappy ..

I would like to ask how to write correctly only rails locomotive engine admin.

[2]. Problem: model form with field email
{{ contents.bookings.public_submission_url }}

How is it possible to add in admin engine
field $email for $to the model from created email bookings for this model?
in php I wrote that by this way > model bookings with field 'email'
$to = 'admin@project.net, '.$_POST['email'].'

Thank you for your answer

Filip

**Comment by did** [comment]
@creativefingers I've fixed a couple of bugs concerning the public forms in v3. I also ran a local test with your scenario and everything went fine (latest commits of both Steam and Engine).
