### ISSUE TITLE
Inline editor home button to take an admin to content entries screen

### ISSUE THREAD

**Issue by danielmyasnikov** [locomotivecms/engine#1026]
That would be nice to have this functionality:

If an author wants to preview a templatized page, and clicks home button, the author is taken to a templatized page instead of the content entries page.

Usually templatized pages don't have content, hence that would be great to direct them to content entry or content types entries page of that page.

**Comment by did** [comment]
When previewing a templatized page (live editing), the right sidebar gives you the ability to edit the displayed content entry :-)
