### ISSUE TITLE
Devise issues when upgrading

### ISSUE THREAD

**Issue by genofedanzo** [locomotivecms/engine#1036]
I recently attempted an upgrade from 2.4.1 to 2.5.6 and ran into a few issues with devise.  The first was secret_key being declared which has been removed (is that a devise 3.1 feature?).  The other issue I had was authentication broke because a pepper was added and those hashes  were not peppered originally.  I commented out the line and auth started working.  It's a good idea to salt/pepper passwords and also encrypt tokens but hard to pull off after the fact when upgrading.  Should I have used forgot password instead of disabling the pepper?  Also, it would be better to dynamically generate these strings as they are currently hardcoded in the template file.

**Comment by did** [comment]
@genofedanzo thanks for the explanation. About your last suggestion, I included it in v3.
