### ISSUE TITLE
URL with non-existent locale should 404 or redirect.

### ISSUE THREAD

**Issue by jasongonzales23** [locomotivecms/engine#1038]
To reproduce: 

Go to www.somesite.com/en-fake -> the page should redirect to the default locale homepage.
Go to www.somesite.com/en-fake/page/content_type/:id -> should either 404 or redirect, but instead 500s with the following error:

NoMethodError: undefined method `children_with_minimal_attributes' for nil:NilClass

However, I also get 500s if I hit a page that doesn't rely on a content_type.

I'm seeing this in production of our website where users are trying to hit a locale we no longer support (it's turned off in the admin and removed from site.yml, there are no longer templates for it). But if I just make up any old local, I get the same errors.

**Comment by jasongonzales23** [comment]
Bump. Still getting hella 500s out here.

**Comment by did** [comment]
@jasongonzales23 could you still reproduce this error with v3 (use the last commit on Github)? thanks!

**Comment by did** [comment]
I was not able to reproduce it in v3.
