### ISSUE TITLE
Issue installing Locomotive Engine

### ISSUE THREAD

**Issue by lutzjs** [locomotivecms/engine#1042]
<p>I've been fighting with trying to install LocomotiveCMS for over a day, each time I get through one problem, another one pops up, however this time I haven't been able to solve it.</p>

<h4>My Command Prompt shows the following:</h4>

`Microsoft Windows [Version 6.1.7601]`
`Copyright (c) 2009 Microsoft Corporation.  All rights reserved.`

`C:\Bitnami\rubystack-2.0.0-25>cd projects`

`C:\Bitnami\rubystack-2.0.0-25\projects>cd locomotive_engine`

`C:\Bitnami\rubystack-2.0.0-25\projects\locomotive_engine>rails -v
Rails 3.2.19`

`C:\Bitnami\rubystack-2.0.0-25\projects\locomotive_engine>ruby -v
ruby 2.0.0p645 (2015-04-13) [i386-mingw32]`

`C:\Bitnami\rubystack-2.0.0-25\projects\locomotive_engine>bundle install`
`Using rake 10.0.4`
`Using RedCloth 4.2.9`
`Using i18n 0.6.11`
`Using multi_json 1.7.9`
`Using activesupport 3.2.19`
`Using builder 3.0.4`
`Using activemodel 3.2.19`
`Using erubis 2.7.0`
`Using journey 1.0.4`
`Using rack 1.4.5`
`Using rack-cache 1.2`
`Using rack-test 0.6.3`
`Using hike 1.2.3`
`Using tilt 1.4.1`
`Using sprockets 2.2.3`
`Using actionpack 3.2.19`
`Using mime-types 1.25.1`
`Using polyglot 0.3.5`
`Using treetop 1.4.15`
`Using mail 2.5.4`
`Using actionmailer 3.2.19`
`Using arel 3.0.3`
`Using tzinfo 0.3.43`
`Using activerecord 3.2.19`
`Using activeresource 3.2.19`
`Using bundler 1.9.4`
`Using rack-ssl 1.3.4`
`Using json 1.8.2`
`Using rdoc 3.12.2`
`Using thor 0.19.1`
`Using railties 3.2.19`
`Using rails 3.2.19`
`Using actionmailer-with-request 0.4.0`
`Using addressable 2.3.8`
`Using bcrypt 3.1.10`
`Using bcrypt-ruby 3.1.5`
`Using cancan 1.6.7`
`Using carrierwave 0.9.0`
`Using moped 1.5.2`
`Using origin 1.1.0`
`Using mongoid 3.1.6`
`Using mongoid-grid_fs 1.9.2`
`Using carrierwave-mongoid 0.6.3`
`Using cells 3.8.8`
`Using chunky_png 1.3.4`
`Using codemirror-rails 3.24`
`Using coffee-script-source 1.9.1.1`
`Using execjs 2.5.2`
`Using coffee-script 2.2.0`
`Using coffee-rails 3.2.2`
`Using fssm 0.2.10`
`Using sass 3.2.19`
`Using compass 0.12.7`
`Using compass-rails 2.0.0`
`Using money 5.1.1`
`Using custom_fields 2.3.2`
`Using orm_adapter 0.5.0`
`Using warden 1.2.3`
`Using devise 2.2.7`
`Using devise-encryptable 0.1.2`
`Using dragonfly 1.0.7`
`Using ejs 1.0.0`
`Using excon 0.23.0`
`Using flash_cookie_session 1.1.6`
`Using formatador 0.2.5`
`Using net-ssh 2.9.2`
`Using net-scp 1.2.1`
`Using nokogiri 1.5.11`
`Using ruby-hmac 0.4.0`
`Using fog 1.12.1`
`Using formtastic 2.2.1`
`Using haml 4.0.6`
`Using highline 1.6.21`
`Using multi_xml 0.5.5`
`Using httparty 0.11.0`
`Using jquery-rails 2.1.4`
`Using kaminari 0.14.1`
`Using locomotive-aloha-rails 0.23.2.2`
`Using locomotive-tinymce-rails 3.5.8.2`
`Using locomotive_liquid 2.4.2`
`Using locomotivecms_solid 0.2.2`
`Using mimetype-fu 0.1.2`
`Using mongo_session_store-rails3 4.1.1`
`Using mongoid-tree 1.0.4`
`Using mongoid_migration 0.0.8`
`Using rails-backbone 0.7.2`
`Using redcarpet 3.0.0`
`Using responders 0.9.3`
`Using sanitize 2.0.3`
`Using stringex 2.0.11`
`Using locomotive_cms 2.5.6`
`Using sass-rails 3.2.6`
`Using uglifier 2.7.1`
`Bundle complete! 7 Gemfile dependencies, 93 gems now installed.`
`Use 'bundle show [gemname]' to see where a bundled gem is installed.`

`C:\Bitnami\rubystack-2.0.0-25\projects\locomotive_engine>bundle exec rails g loc
omotive:install`
`DL is deprecated, please use Fiddle`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19
/lib/active_support/dependencies.rb:251:in 'require': cannot load such file -- 2
.0/redcloth_scan (LoadError)`
`Couldn't load 2.0/redcloth_scan`
`The $LOAD_PATH was:`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/custom_fields-2.3.2/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongo_session_store-
rails3-4.1.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/uglifier-2.7.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/sass-rails-3.2.6/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomotive_cms-2.5.6
/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/stringex-2.0.11/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/sanitize-2.0.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/responders-0.9.3/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/redcarpet-3.0.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rails-backbone-0.7.2
/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongoid_migration-0.
0.8/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongoid-tree-1.0.4/l
ib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongo_session_store-
rails3-4.1.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mimetype-fu-0.1.2/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomotivecms_solid-
0.2.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomotive_liquid-2.
4.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomotive-tinymce-r
ails-3.5.8.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomotive-aloha-rai
ls-0.23.2.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/kaminari-0.14.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/jquery-rails-2.1.4/l
ib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/httparty-0.11.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/multi_xml-0.5.5/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/highline-1.6.21/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/haml-4.0.6/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/formtastic-2.2.1/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/fog-1.12.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/ruby-hmac-0.4.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.11-x86-
mingw32/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/net-scp-1.2.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/formatador-0.2.5/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/flash_cookie_session
-1.1.6/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/excon-0.23.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/ejs-1.0.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/dragonfly-1.0.7/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/devise-encryptable-0
.1.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/devise-2.2.7/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/orm_adapter-0.5.0/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/custom_fields-2.3.2/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/money-5.1.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/compass-rails-2.0.0/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/compass-0.12.7/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/fssm-0.2.10/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/coffee-rails-3.2.2/l
ib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/coffee-script-2.2.0/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.5.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/coffee-script-source
-1.9.1.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/codemirror-rails-3.2
4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/chunky_png-1.3.4/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/cells-3.8.8/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/carrierwave-mongoid-
0.6.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongoid-grid_fs-1.9.
2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/origin-1.1.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/moped-1.5.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/cancan-1.6.7/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bcrypt-ruby-3.1.5-x8
6-mingw32/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bcrypt-3.1.10-x86-mi
ngw32/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/addressable-2.3.8/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actionmailer-with-re
quest-0.4.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rails-3.2.19/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rdoc-3.12.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rack-ssl-1.3.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/activeresource-3.2.1
9/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/tzinfo-0.3.43/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/arel-3.0.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actionmailer-3.2.19/
lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mail-2.5.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/treetop-1.4.15/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.5/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/mime-types-1.25.1/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.19/li
b`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/hike-1.2.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rack-test-0.6.3/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/journey-1.0.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/erubis-2.7.0/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/activemodel-3.2.19/l
ib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/builder-3.0.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19
/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/multi_json-1.7.9/lib`

`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/i18n-0.6.11/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/RedCloth-4.2.9-x86-m
ingw32/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/RedCloth-4.2.9-x86-m
ingw32/lib/case_sensitive_require`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/RedCloth-4.2.9-x86-m
ingw32/ext`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/rake-10.0.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.9.4/lib`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/site_ruby/2.0.0`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/site_ruby/2.0.0/i386-msvcrt`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/site_ruby`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/vendor_ruby/2.0.0`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/vendor_ruby/2.0.0/i386-msvcrt`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/vendor_ruby`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/2.0.0`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/2.0.0/i386-mingw32`
`C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.19/li
b/action_controller/vendor/html-scanner`
 `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:251:in 'block in require'`
  `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:236:in 'load_dependency'`
   `     from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:251:in 'require'`
    `    from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/RedClot
h-4.2.9-x86-mingw32/lib/redcloth.rb:13:in '<top (required)>'`
     `   from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:251:in 'require'`
      `  from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:251:in 'block in require'`
       ` from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:236:in 'load_dependency'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/actives
upport-3.2.19/lib/active_support/dependencies.rb:251:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomot
ive_cms-2.5.6/lib/locomotive/dependencies.rb:20:in '<top (required)>'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomot
ive_cms-2.5.6/lib/locomotive/engine.rb:1:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/locomot
ive_cms-2.5.6/lib/locomotive/engine.rb:1:in '<top (required)>'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:76:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:76:in 'block (2 levels) in require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:72:in 'each'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:72:in 'block in require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:61:in 'each'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler/runtime.rb:61:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/bundler
-1.9.4/lib/bundler.rb:134:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/projects/locomotive_engine/config/app
lication.rb:13:in '<top (required)>'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/railtie
s-3.2.19/lib/rails/commands.rb:24:in 'require'`
        `from C:/Bitnami/rubystack-2.0.0-25/ruby/lib/ruby/gems/2.0.0/gems/railtie
s-3.2.19/lib/rails/commands.rb:24:in '<top (required)>'`
        `from script/rails:6:in 'require'`
        `from script/rails:6:in '<main>'` 

<h4>My gem file looks like this:</h4>

`source 'https://rubygems.org'`

`gem 'rails', '3.2.19'`

`gem 'locomotive_cms', '~> 2.5.6', :require => 'locomotive/engine'`

`# Bundle edge Rails instead:`
`# gem 'rails', :git => 'git://github.com/rails/rails.git'`

`# Gems used only for assets and not required`
`# in production environments by default.`
`group :assets do`
  `gem 'sass-rails',   '~> 3.2.3'`
  `gem 'coffee-rails', '~> 3.2.1'`
  `gem 'compass', '~> 0.12.7'`
  `gem 'compass-rails', '~> 2.0.0'`

 ` # See https://github.com/sstephenson/execjs#readme for more supported runtimes`
 ` # gem 'therubyracer', :platforms => :ruby`

  `gem 'uglifier', '>= 1.0.3'`
`end`

`# To use ActiveModel has_secure_password`
`# gem 'bcrypt-ruby', '~> 3.0.0'`

`# To use Jbuilder templates for JSON`
`# gem 'jbuilder'`

`# Use unicorn as the app server`
`# gem 'unicorn'`

`# Deploy with Capistrano`
`# gem 'capistrano'`

`# To use debugger`
`# gem 'debugger'`

<p>I initially thought that the issue had to do with RedCloth, so I searched online and found suggestions for creating a directory 2.0 in the redcloth_scan directory of RedCloth, this however did not change the message any. So I'm really not sure what I'm doing incorrectly at this point. Any help would be greatly appreciated.</p>

**Comment by dimanyc** [comment]
+1. I tried creating a directory named `2.0` and dropping the `redcloth_scan.so` file in it. No luck..

**Comment by dimanyc** [comment]
@lutzjs were you able to find a fix?

**Comment by lutzjs** [comment]
Dimitry,

Yes I was able to find a fix with the help of another member. On my machine it appeared that a RedCloth installed two verisons, the version that was causing the problem was a x86 version. Even uninstalling it didn’t work as it would try to uninstall it. Finally the instructions that I found would work were

It may be worth stepping through the process of installing the required Ruby version of RedCloth 4.2.9 by manually running each command in my batch file  (from the command line) and checking  progress after each step:

# Check if win32 version of RC gem is installed (want Ruby version instead)
Run this command:
$ gem list RedCloth
What output does this give? If you already ran the batch file you should see
only RedCloth (4.2.9). In this case what does "bundle list RedCloth" report?
But if you still see RedCloth-4.2.9-x86-mingw32 listed then go to the next steps:

# Uninstall win32 RC gem (RedCloth-4.2.9-x86-mingw32) and its libraries
$ gem uninstall RedCloth
This should list the versions of RedCloth gem you have on your system if there is more than one and ask you what you want to do. In my case RedCloth-4.2.9-x86-mingw32 was listed as option 1, and after typing "1" there is a second question about removing libraries as well (or something like that), so type "Y" to take the whole thing out. Hence the 'reminder' in my batch file:
echo Select option 1 and then Y:
Make sure you remove the RedCloth-4.2.9-x86-mingw32 gem and not the Ruby version (which is listed as just RedCloth-4.2.9)

# Re-install the required RC gem version
$ gem install RedCloth -v 4.2.9 --platform ruby
You can check for the RedCloth gem folder in your filesystem - for me this is:
C:\Bitnami\rubystack-2.0.0-24\ruby\lib\ruby\gems\2.0.0\gems\RedCloth-4.2.9\
While you're there, check that there isn't any RedCloth-4.2.9-x86-mingw32 folder - if you've successfully removed the win32 gem that folder should have gone.

Lastly you just need to create the missing folder (don't forget to change the path below to match your existing folder structure, otherwise this will just create a spurious folder that your RoR system won't find):
# Create 2.0 folder
$ md C:\Bitnami\rubystack-2.0.0-24\ruby\lib\ruby\gems\2.0.0\gems\RedCloth-4.2.9\lib\2.0

And copy the file from the parent folder into the 2.0 folder you just created (again changing the paths in the command to match your folder structure):
# Copy redcloth_scan.so lib into it
$ copy C:\Bitnami\rubystack-2.0.0-24\ruby\lib\ruby\gems\2.0.0\gems\RedCloth-4.2.9\lib\redcloth_scan.so C:\Bitnami\rubystack-2.0.0-24\ruby\lib\ruby\gems\2.0.0\gems\RedCloth-4.2.9\lib\2.0

Finally check that the 2.0 folder was really created in the right place and contains the file redcloth_scan.so

The individual that helped was Nick Jurascheck, extremely helpful. It appears that it is definitely much easier to install Locomotive on Linux than Windows. Would be excellent if someone could create a Bitnami stack for Locomotive to be installed on Windows.

Thanks,

Jonathan

**Comment by dimanyc** [comment]
@lutzjs AWESOME!! Thank you so much!
