### ISSUE TITLE
Installed locomotivecms@3.0.0.pre.alpha.2 with Rails 4.2.1, but no homepage

### ISSUE THREAD

**Issue by mikeyhew** [locomotivecms/engine#1047]
I installed the latest alpha release from this repository by adding 
```ruby
gem 'locomotivecms', '~> 3.0.0.pre.alpha.2',  git: 'git://github.com/locomotivecms/engine', tag: 'v3.0.0.pre.alpha.2'
```
to my Gemfile in an new rails 4.2.1 app, and successfully ran bundle update after trying bundle install and getting a conflict. I started the server with `rails s -p $PORT -b $IP`, and the server started up fine, but when I go to the homepage of my app in the browser, all I get is a single line of text:

>Hi, we are sorry but no site was found.

Any idea what is going wrong?

EDIT: I'm working on c9.io, the online IDE. That's why I'm binding to $IP:$PORT.

**Comment by mikeyhew** [comment]
Just to add, the same message comes up when I go to /admin

**Comment by neversion** [comment]
You can go to http://localhost:8080/locomotive  and sign up a new account, and then you can create a new site.
But there must be a bug?  anyone can sign up a account and create sites.

**Comment by manuchap** [comment]
Try to seed a default db with:
```bash
rake development:bootstrap
```

**Comment by neversion** [comment]
@manuchap, thanks. It work for me.
