### ISSUE TITLE
Cannot bring tests to pass on 2.5.7

### ISSUE THREAD

**Issue by jo-m** [locomotivecms/engine#1053]
I want to develop a small feature we need on the stable branch (v2.5.x, current version is 2.5.7 c25c707).
I set up everything like described here: <https://github.com/locomotivecms/engine/blob/v2.5.x/README.textile>.

Then I start mongo: `mongo: mongod --dbpath data/`. But I cannot bring all tests to pass. `rake` outputs this (full output here: <https://gist.github.com/jo-m/887039d5e1ae2828eeb5>):

<img width="1440" alt="screen shot 2015-07-30 at 09 16 34" src="https://cloud.githubusercontent.com/assets/2587503/8977754/18adc3ee-369c-11e5-9706-eb7cf4bed5bd.png">

I am using ruby 2.2.0, might this be the issue? Which ruby versions do you recommend?

**Comment by jo-m** [comment]
OK, I re-installed it using ruby 1.9.3. I will write this into the dev docs.

**Comment by did** [comment]
Hi @jo-m
v2.5.x works perfectly with Ruby 2.1, not sure about 2.2 though.
v3 works with Ruby 2.1 and Ruby 2.2.
