### ISSUE TITLE
Feature Request: Automatic Image resize for any end Device

### ISSUE THREAD

**Issue by N00D13** [locomotivecms/engine#1057]
For an Example: you have a Big Image, that would automatically resized for any Screen Resolution.

**Comment by did** [comment]
hi @N00D13, would you achieve it on the server side? If so, how do you detect the screen resolution? 
If you were thinking about doing it on the frontend side, I'd suggest to you use Bootstrap and more specifically the responsive-image css class. Works pretty well.
