### ISSUE TITLE
TinyMCE file_browser_callback

### ISSUE THREAD

**Issue by ziedbargaoui** [locomotivecms/engine#1058]
When adding a file_browser_callback to the locomotive_misc, a "file picker" gets
added to all the input fields where file links are supposed to be pasted in (like Link
plugin).

The problems is that one cannot see those buttons, no thumbnail and no image and
even no word (like "Select File").

Is there a work around for this?

**Comment by did** [comment]
@ziedbargaoui are you referencing Locomotive v2.5.x? If so, I suggest you to try v3 instead.
