### ISSUE TITLE
Query about message in engine.

### ISSUE THREAD

**Issue by melalonso** [locomotivecms/engine#1062]
When creating a new site and I try to edit the home page I get the message "No editable elements found". I'm stil not able to realize what's the cause of the message. 

Thanks in advance.

**Comment by boie0025** [comment]
Try creating a block: http://doc.locomotivecms.com/references/api/tags/block  
with an editable_text tag inside: http://doc.locomotivecms.com/references/api/tags/editable-text
in the template for the home page.

eg:
```
      {% block 'main' %}
      {% editable_text 'main_text' %}
        <p>Lorem ipsum....</p>
      {% endeditable_text %}
      {% endblock %}
```
