### ISSUE TITLE
Deploy to Heroku is broken

### ISSUE THREAD

**Issue by dphaener** [locomotivecms/engine#1063]
In following the guide here: https://locomotive-v3.readme.io/docs/heroku the site won't load up.

I'm getting a stack level too deep when trying to hit any url. Anyone run into this?

**Comment by allanbreyes** [comment]
I got that once, but setting the `HEROKU_APP_ID` and `HEROKU_API_KEY` or whatever they are fixed it.

**Comment by dphaener** [comment]
I was able to solve the problem. I had nothing to do with Locomotive or Moped, and everything to do with the fact that MongoLab started using a version of Mongo that was incompatible with Mongoid/Moped. Switched over to Compose Mongo and everything works great.
