### ISSUE TITLE
S3 asset URLs aren't being rendered properly?  Missing bucket name?

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1064]
Running 3.0.0.rc1 and was absolutely loving it, but ran into an issue with S3 files on production...

The sample portfolio site turns from this on dev/local:
![image](https://cloud.githubusercontent.com/assets/7947900/10536075/dad9fc50-73ad-11e5-9c97-c1f7778d8425.png)

Into this on production/Heroku:
![image](https://cloud.githubusercontent.com/assets/7947900/10536072/d009ca76-73ad-11e5-8bea-b1daf4b0146f.png)

I can say for certain that S3 upload is working, but on the HTML, the assets URLs are being rendered incorrectly.

Expected:
`https://s3-us-west-2.amazonaws.com/**BUCKET_NAME**/sites/5620a491d4bcdb0003000031/content_entry5620a4a8d4bcdb0003000039/5620a4aad4bcdb000300005e/files/cabin.png?1444979882`

Result:
`https://s3-us-west-2.amazonaws.com/sites/5620a491d4bcdb0003000031/content_entry5620a4a8d4bcdb0003000039/5620a4aad4bcdb000300005e/files/cabin.png?1444979882`

I'm not sure if this is an issue with CarrierWave.  Can you point me in the right direction in the source code, and I'll see if I can submit a PR?  Thanks :)  Keep up the good work, team!

**Comment by allanbreyes** [comment]
Not sure if I'm way off on this... but it might be a Carrierwave problem?  I did a trace for areas where it didn't render, mainly, anywhere `source.url` was called.  I came to this:

https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/default_url.rb

**Comment by dphaener** [comment]
:+1: On this. I'm having the same issue. It's also unable to retrieve the assets on the asset page.

**Comment by did** [comment]
It was caused by a misconfiguration of carrierwave. I fixed the issue, did some code cleaning and removed the dependence to the fog gem (now new installation should use https://github.com/sorentwo/carrierwave-aws). I'm going to update the v3 doc.

**Comment by allanbreyes** [comment]
Thank you so much for this fix!  You rock!

**Comment by dphaener** [comment]
:+1: Yes thank you so much! Nice work on this guys! Love the new verison.

**Comment by stunjiturner** [comment]
seems like a fix to my problem @did ???, same issue i was having

**Comment by allanbreyes** [comment]
hey @did, I'd love to help in any way possible, even if it's documentation.  is there a way to fork and PR stuff from readme.io?
