### ISSUE TITLE
Can't utilize SVG as image

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1065]
It renders from `/samples/something.svg` properly when uploaded via `wagon`, but I cannot seem to select an SVG file for image assets.  I think perhaps it is recognizing it as a font, instead?

![image](https://cloud.githubusercontent.com/assets/7947900/10567460/37176d94-75cb-11e5-89f5-1aa6327fc340.png)

Selecting an SVG results in an error "Unable to load asset"

**Comment by did** [comment]
@allanbreyes You're bringing a tricky case up here :-) 

So, right, SVG files are first considered as fonts in Locomotive. 

**FIX**: The new rule is going to be this one when uploading a SVG file from the UI **OR** the API.

1. It's considered as a font if this is a theme asset and its folder is fonts
2. It's considered as an image in all the other cases (content asset or theme asset in a different folder).

**Comment by allanbreyes** [comment]
Thanks for the fix!
