### ISSUE TITLE
[v3] Resized images not being served on local or production

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1067]
Example Liquid HAML call (modified from portfolio project example):

```haml
{% for project in contents.projects %}
.col-sm-4.portfolio-item
  %a.portfolio-link{ href: "#portfolioModal1", data: { toggle: 'modal' } }
    .caption
      .caption-content
        %i.fa.fa-search-plus.fa-3x
    /- here:
    %img.img-responsive{ src: "{{ project.image.url | resize: '100x100' }}" }
{% endfor %}
```

Getting either a 400 with message: "The SHA parameter you gave is incorrect" or a 404.  Am I doing something wrong?

**Comment by manuchap** [comment]
Have you tried without the .url param?
```haml
%img.img-responsive{ src: "{{ project.image | resize: '100x100' }}" }
```

**Comment by did** [comment]
@allanbreyes what's the HTML generated by your code? thanks!

**Comment by allanbreyes** [comment]
@manuchap - without `.url` results in the same problem

@did - here is the HTML generated:

```html
<div class="col-sm-4 portfolio-item">
  <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
    <div class="caption">
      <div class="caption-content">
        <i class="fa fa-search-plus fa-3x"></i>
      </div>
    </div>
    <img class="img-responsive" src="/images/dynamic/W1siZmYiLCIvaG9tZS9hbGxhbi9Xb3Jrc3BhY2UvZW5kb3Ivc2l0ZXMvcG9ydGZvbGlvL3B1YmxpYy9wdWJsaWMvc2FtcGxlcy9wb3J0Zm9saW8vY2FiaW4ucG5nIl0sWyJwIiwidGh1bWIiLCIxMDB4MTAwIl1d/cabin.png?sha=a80b9458fcc03005">
  </a>
</div>

<div class="col-sm-4 portfolio-item">
  <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
    <div class="caption">
      <div class="caption-content">
        <i class="fa fa-search-plus fa-3x"></i>
      </div>
    </div>
    <img class="img-responsive" src="/images/dynamic/W1siZmYiLCIvaG9tZS9hbGxhbi9Xb3Jrc3BhY2UvZW5kb3Ivc2l0ZXMvcG9ydGZvbGlvL3B1YmxpYy9wdWJsaWMvc2FtcGxlcy9wb3J0Zm9saW8vY2lyY3VzLnBuZyJdLFsicCIsInRodW1iIiwiMTAweDEwMCJdXQ/circus.png?sha=8f973b9810a6a727">
  </a>
</div>
```

Some other notes:
- I know that I have ImageMagick installed correctly (resizing works in other gems/CMSes).
- Behavior is replicated in production.  I'm not sure when/where I received the 400 message... it was in some permutation of the tag inside the `img` `src` attr.
- `dragonfly.log` seems to be empty?  This seems like an issue... shouldn't something be logged here?
- Nothing of importance in `wagon.log` - just processing of the GET request.

**Comment by allanbreyes** [comment]
Actually, I'm almost positive that this is a routing issue.  I'm not sure if dragonfly is getting mounted.  I'm trying to just access without the SHA param, and getting a 404.

According to: https://github.com/markevans/dragonfly/blob/241a4ed802f3b612e5a00f18a50605321c9f7323/lib/dragonfly/routed_endpoint.rb#L28

I should be getting a 400, correct?

**Comment by allanbreyes** [comment]
Okay, to clarify, I get a `404` when running on wagon.

When deployed to either a local or production engine (heroku), I'm getting a `400`: The SHA parameter you gave is incorrect.

I think this is related to this issue: https://github.com/markevans/dragonfly/issues/387

Looks like the SHA algorithm changed on a patch update?  I'll try downgrading to see if it fixes it...

**Comment by did** [comment]
Wagon and Engine needs the very last commit of Steam in order to not run this issue anymore.

**Comment by allanbreyes** [comment]
:+1: :+1: :+1:
