### ISSUE TITLE
backbone-on-rails not installing because of eco gem

### ISSUE THREAD

**Issue by nielsenramon** [locomotivecms/engine#1072]
I am just leaving this here, but when I tried installing `locomotivecms gem` I received the following error:

```
ERROR:  Could not find a valid gem 'eco-source' (>= 0) in any repository
ERROR:  Possible alternatives: to_source, chsource, taosource, epf-source, outsource
```

Not much was found about this issue and I wasn't able to fix it by changing versions.
I had to download and install the `eco` gem locally to make `backbone-on-rails` succeed.

I got the solution from here https://github.com/sstephenson/ruby-eco/issues/1

Any one else had this issue? It kinda disturbs me that the `eco` gem issue is open for 4 years already.

**Comment by did** [comment]
@nielsenramon super weird. 
````bash
$ bundle list | grep eco
  * activerecord (4.2.4)
  * eco (1.0.0)
  * eco-source (1.1.0.rc.1)
````

**Comment by tispratik** [comment]
I am getting the same issue

```
$ gem install locomotivecms --pre                                                                                                         
ERROR:  Could not find a valid gem 'eco-source' (>= 0) in any repository
ERROR:  Possible alternatives: to_source, chsource, taosource, epf-source, outsource
```

**Comment by tispratik** [comment]
The solution suggested in sstephenson/ruby-eco#1 did not work for me :( I could install the eco-source gem using --pre but `gem install eco` still failed.

**Comment by nielsenramon** [comment]
@tispratik Try downloading the zipped eco gem from here: https://www.dropbox.com/s/akzf19kwnd41jn8/eco-1.0.0.gem?dl=0 And install it locally.

After that it should word :)

**Comment by did** [comment]
@tispratik, did you try this:
````
~ > gem install eco-source --pre
Successfully installed eco-source-1.1.0.rc.1
Parsing documentation for eco-source-1.1.0.rc.1
Installing ri documentation for eco-source-1.1.0.rc.1
Done installing documentation for eco-source after 0 seconds
1 gem installed
````

Just out of curiosity, which version of gem are u using? (not sure if it's related or not)

````
~ > gem --version
2.4.5
````

**Comment by tispratik** [comment]
Hello @did 

```
$ gem --version
2.4.6
```

Yes, i tried the --pre option, but still get the same error :(

```
$ gem install eco-source --pre                                                                                                           
Successfully installed eco-source-1.1.0.rc.1
1 gem installed
$ gem install eco                                                                                                                        
ERROR:  Could not find a valid gem 'eco-source' (>= 0) in any repository
ERROR:  Possible alternatives: to_source, chsource, taosource, epf-source, outsource
```

@nielsenramon Thanks, i will check to see how to install it locally.

**Comment by did** [comment]
it's caused by a new version of the gem command (rubygems) which must break the way the gems are found.

**Comment by tispratik** [comment]
Downgrading rubygems did not help :(

```
$ gem  uninstall eco-source
You have requested to uninstall the gem:
	eco-source-1.1.0.rc.1

eco-1.0.0 depends on eco-source (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  Y
Successfully uninstalled eco-source-1.1.0.rc.1

$ gem install eco-source --pre                                                                                                                    Fetching: eco-source-1.1.0.rc.1.gem (100%)
Successfully installed eco-source-1.1.0.rc.1
1 gem installed

$ gem install eco
ERROR:  Could not find a valid gem 'eco-source' (>= 0) in any repository
ERROR:  Possible alternatives: to_source, chsource, taosource, epf-source, outsource

$ gem -v
2.4.5
```

**Comment by did** [comment]
@tispratik You need to downgrade to a much older version of rubygems, something like 2.3.x.

So the reason why it doesn't get installed is that Rubygems doesn't want to install pre-released gems inside a gemspec. I think that's a bug.

**Comment by did** [comment]
Alright, I've opened an issue here: https://github.com/rubygems/rubygems/issues/1380

**Comment by did** [comment]
I got rid of the backbone-on-rails gem so no more eco-source issue :-) Instead, I use Bower to fetch the JS libs I need.
https://github.com/locomotivecms/engine/commit/a6faec75d7be390a4bac66f83a18b092f72f9a04

**Comment by tispratik** [comment]
Awesome!! Thanks a lot @did
