### ISSUE TITLE
bundle exec rake locomotive:upgrade:v3 / final solution : switch over to v3 / Engine Images Disappears / after editing  some pictures of the product after the deposit disappears BUT on a Web site presenting these images show. (I have used both very last commit of the v2.5.x ref: '3e2981a')

### ISSUE THREAD

**Issue by creativefingers** [locomotivecms/engine#1073]
Hi, developers

I love using and developing open source code rubyonrails locomotivecms.
I have a big problem and my clients are not happy and I don't eitherand. I don't know how to fix this error bug..

1. I have a model product with images = OK
2. I am creating a new product and add product images and save = OK

IF BUT

3. If the editing of product, some pictures of the product after the deposit disappears and i must enter images again

Thank you for your support!

Have a nice day

Filip

**Comment by did** [comment]
hey @creativefingers ! Which version of Locomotive? Localized site?

**Comment by creativefingers** [comment]
Hi Did, 

Gemfile
gem 'locomotive_cms', '~> 2.5.6', :require => 'locomotive/engine

Current version gem is locomotive_cms-2.5.6
No localized site is default en.

Thank you for your help,  I don't know how to fix this!

Filip

**Comment by did** [comment]
Could you please use the very last commit of the v2.5.x branch and tell me if it fixes your issue?

**Comment by creativefingers** [comment]
Yes  Did, 

BUT

This is the production version of the high traffic. 
How do I safely and quickly very last commit of the v2.5.x branch?

Thank you for your support.

Filip

**Comment by did** [comment]
something like that?

````
gem 'locomotive_cms', github: 'locomotivecms/engine', ref: '27d89c3f034', branch: 'v2.5.x', require: 'locomotive/engine'
````

**Comment by creativefingers** [comment]
Pardon I was ill 

but now

bundle update
Using locomotive_cms 2.5.8 (was 2.5.6) from git://github.com/locomotivecms/engine.git (at 27d89c3@27d89c3)

a problem has lasted after update product some pictures disappearing

Thank you for your support

**Comment by creativefingers** [comment]
Now Use 
Latest commit 3e2981a on Nov 30
bundle update
Using locomotive_cms 2.5.8 from git://github.com/locomotivecms/engine.git (at 3e2981a@3e2981a)

a problem has lasted after update product some pictures disappearing

I'm clueless

**Comment by creativefingers** [comment]
ruby '2.0.0'
gem 'rails', '3.2.21'
gem 'locomotive_cms', github: 'locomotivecms/engine', ref: '3e2981a', branch: 'v2.5.x', require: 'locomotive/engine'

**Comment by creativefingers** [comment]
Product images after editing disappear admin engine BUT on a Web page presenting these images show.

**Comment by creativefingers** [comment]
I created a demo product. What seems strange to me. The product model are required 6 field images, but require admin asterisk are not visible .. only see my hint.

I tried to remove required, but same result..

some product images after editing disappear admin engine BUT on a Web page presenting these images show.

This is production version of the client, and i do not know how fix this.

![screenshot at 2016-01-03 12 54 47](https://cloud.githubusercontent.com/assets/4964173/12078648/79b1e69e-b21a-11e5-90ba-a5e5b8e87aed.png)
![screenshot at 2016-01-03 12 56 16](https://cloud.githubusercontent.com/assets/4964173/12078649/79b2933c-b21a-11e5-835c-ae239f4fa15f.png)

BUT HERE require admin asterisk are visible.. hmmmm
![screenshot at 2016-01-03 13 07 27](https://cloud.githubusercontent.com/assets/4964173/12078672/32be5fbe-b21b-11e5-9c53-8b0c331cd459.png)

**Comment by creativefingers** [comment]
After the upgrade gem (very last commit ref: '3e2981a') I did

bundle exec rake db:mongoid:migration:install
bundle exec rake db:mongoid:migrate
bundle exec rake assets:clean
bundle exec rake assets:precompile

BUT
some product images after editing still disappear admin engine BUT on a Web page presenting these images show.

..

**Comment by creativefingers** [comment]
Now I tested this gem latest in a series Rails 3.2
gem 'rails', '3.2.22'

BUT the problem still persists..
some product images after editing still disappear admin engine BUT on a Web page presenting these images show..

**Comment by did** [comment]
@creativefingers, let me check that.

**Comment by did** [comment]
quick question: do you see javascript errors in the browser console when you edit a product?

**Comment by creativefingers** [comment]
No javascript errors in the browser console.

And disappearing images does not rule it randomly.. UF I'm clueless.

**Comment by creativefingers** [comment]
Did I can create for you login and send PRIVACY. This is a production version site my client.

**Comment by did** [comment]
@creativefingers yes, please, do

**Comment by creativefingers** [comment]
Yes I sent an email to didier@nocoffee.fr with login.

**Comment by creativefingers** [comment]
I sent email from my adress xdevproject.net as Filip Alexandr.. came mail?

**Comment by creativefingers** [comment]
Please do not look on a given topic site:) this is business and graphic site my client.. i am developer and server..

**Comment by creativefingers** [comment]
Actual version of Gemfile is
ruby '2.0.0'
gem 'rails', '3.2.22'
gem 'locomotive_cms', '~> 2.5.7', :require => 'locomotive/engine'

Since the very last commit (ref: '3e2981a') not work I tried this.
BUT the problem still persists..
some product images after editing still disappear admin engine BUT on a Web page presenting these images show.. And disappearing images does not rule it randomly..

**Comment by creativefingers** [comment]
PassengerRoot /usr/local/rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0/gems/passenger-5.0.23
PassengerDefaultRuby /usr/local/rbenv/versions/2.0.0-p648/bin/ruby

**Comment by creativefingers** [comment]
I have prepared additional 2 projects on locomotivecms..

**Comment by creativefingers** [comment]
Product ladies 

I created a demo product. What seems strange to me. The product model are required 6 field images, but require admin asterisk are not visible .. only see my hint.

Maybe here is problem?

Required text field have:
<li id="content_entry_age_input" class=" string input required stringish">

Required file field have in html:
<li id="content_entry_photo_6_input" class="file input optional">
[
But Although the engine is checked 6 files required field
]

I tried to remove required, but same result..

some product images after editing disappear admin engine BUT on a Web page presenting these images show.. And disappearing images does not rule it randomly..

**Comment by creativefingers** [comment]
@did Is there something wrong?

**Comment by creativefingers** [comment]
Hi, @did 

I sent email V3 engine resume - switch over to v3.

**Comment by creativefingers** [comment]
Command is 'bundle exec rake locomotive:upgrade:v3'?

**Comment by creativefingers** [comment]
I first performed local devel
=* ruby-2.2.3 [ x86_64 ]
rails 4.2.4
gem install locomotivecms_wagon --pre (2.0.0.rc7) -- ok
test create wagon init site -- ok

but if i update gemfile and bundle from existing wagon site (1.5.8)
and run local - bundle exec wagon serve
.. Set curious problem when I add stylesheet get the white side, and still is loading (loop forever)
and if i test set bundle exec guard i get 404 error..

I'm somewhat disenchanted..
