### ISSUE TITLE
undefined method `thumb' after importing from 2.5.7 to 3.0(master)

### ISSUE THREAD

**Issue by unplugandplay** [locomotivecms/engine#1081]
NoMethodError (undefined method `thumb' for #<#<Class:0x007fcac03cecf8>:0x007fcac03ceaa0>):
  /Users/josbreizh/.rvm/gems/ruby-2.2.3/bundler/gems/engine-bd15f0c0d2e3/lib/locomotive/dragonfly.rb:6:in `resize_url'

I looked at the code 
module Locomotive
  module Dragonfly

    def self.resize_url(source, resize_string)
      if file = self.fetch_file(source)
      #  Locomotive.log :error, "Unable to file.respond_to?(:thumb). fix me : #{source.inspect}"
        file.thumb(resize_string).url if file.respond_to?(:thumb)
        return
      else
        Locomotive.log :error, "Unable to resize on the fly: #{source.inspect}"
        return
      end
    end

but couldn't debug myself as there isn't any method thumb in the all project.

**Comment by burgalon** [comment]
I'm also getting this

**Comment by did** [comment]
https://locomotive-v3.readme.io/docs/upgrade-to-v3. I also described another way to upgrade to v3:
- create new Locomotive Rails app 
- use the settings of the previous MongoDB database
- run the migration rake task
- launch the Locomotive Rails app.
This could fix your issue.
