### ISSUE TITLE
Bootstrap glyphicons not showing on Locomotive 1.5.8

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/engine#1082]
Glyphicons are not showing when doing a regular install of locomotive cms 1.5.8

The workaround: go to the file

      /public/stylesheets/bootstrap/_variables.scss

Set the variable 

     $icon-font-path: "bootstrap/fonts/" !default;

to

     $icon-font-path: "../../fonts/" !default;

and it will work.

**Comment by CedricLor** [comment]
However, while doing as I mentioned earlier solves the issue in the Wagon for locomotive cms 1.5.8, it does not solve the issue in the Engine.

To solve the issue in the engine, do replace:

     $icon-font-path: "bootstrap/fonts/" !default;

by 

       $icon-font-path: "../../fonts/" !default;

glyphicons won't show in the local Wagon server, but works properly in my local Engine.

**Comment by did** [comment]
hi @CedricLor, I strongly recommend that you switch over to Engine v3 (3.0.0.rc3) and Wagon v2 (2.0.0.rc3). They're stable enough to be used in production.
In the meantime, I'm going to check out if this issue remains in the last version of Wagon.

**Comment by CedricLor** [comment]
Hi Didier

I discovered your work a couple of days ago and I really love it.

Thanks for your reply. What version of Rails do they support? Are they fit for 4..2?

This would be great!

Thanks

Cedric

**Comment by did** [comment]
thanks! Engine v3 only works with Rails 4.2.x
