### ISSUE TITLE
concatinated tags

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1084]
![zaznaczenie_012](https://cloud.githubusercontent.com/assets/2798350/11400454/c5aa7832-938d-11e5-935a-164f57e4a089.png)
![zaznaczenie_014](https://cloud.githubusercontent.com/assets/2798350/11400460/ca2e2c96-938d-11e5-9d58-5ef8cc4ed896.png)

There is a problem with concatinated tags in the engine models editor form.

REPRO
 - use the wagon and push a new project with defined model that includes a field with tags type
 - edit new record 
 - add a few tags like: "PL", "USA", "UK" in the tags field type
 - save it
 - now all is ok - you can see tags in the view correctly
 - edit again the same record

WHATS WRONG
 - now there is **only one** tag "PL USA UK" 
 - this is concatinated string of previous 3 tags
 - if you save it you get one tag "PL USA UK" instead of 3

IT SHOULD BE
 - if you edit again the same record you should see **3 tags**: "PL", "USA", "UK"

Checked with **v3.0.0.rc4**

**Comment by did** [comment]
thanks @adam-pl for the bug report.
