### ISSUE TITLE
editable_file - not working

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/engine#1092]
I want to have an editable_file that allows the editor to upload an image but in case the editor has not uploaded any image, to provide a default image. The documentation provides a way to do that: https://locomotive-v3.readme.io/docs/tags#editable_file

Let's try it. 
**First step** Let's create a new site with Wagon. In a new dir,

    $ wagon init test_site -t bootstrap

app/pages/liquid.index looks like that:

    ---
    title: Home page
    published: true
    handle: home
    ---
    {% extends 'layouts/simple' %}

    {% block content/main %}

    <div class="row">
      <div class="col-lg-4">
        {% editable_text first_column %}
          <h2>Heading #1</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        {% endeditable_text %}
      </div>
      <div class="col-lg-4">
        {% editable_text second_column %}
          <h2>Heading #2</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        {% endeditable_text %}
     </div>
      <div class="col-lg-4">
        {% editable_text third_column %}
          <h2>Heading #3</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
        {% endeditable_text %}
      </div>
    </div>

    {% endblock %}

Let's run a 

    bundle exec wagon serve

to check whether everything is fine. If everything is fine, let's push it to the Engine

     bundle exec wagon push production

**Second step** Adding an image as a logo
I want a logo. Let's make a test displaying an image. The public/image directory already contains a file entitled favicon.png. Let's use this file as a test.

Replace everything that is between 

      {% block content/main %}
 
and 

     {% endblock %}

by the following chunk of liquid:

    {{ 'favicon.png' | theme_image_tag }}

Let's check in the browser on the Wagon server, then push on the Engine, check the live preview and the back-office. Everything looks fine, except that, of course, for the moment, the editors will not be able to change the image.

**Step three** Resizing

Let's say that the logo is too small. I will then apply a resizing. I replace the chunk of code I just dropped by the following:

    {{ 'favicon.png' | theme_image_url | resize: '100x100' | image_tag }}

Again, check in the browser on the Wagon server, then push on the Engine, check the livre preview and the back-office. This looks ugly, but it is resized as I wish. Let's go on.

**Step four** Making it editable

Replace the code previously inserted by the following.

    {% capture logo_url %}{% editable_file 'logo' %}{% endeditable_file %}{% endcapture %}
    {% if logo_url != '' %}
        {{ logo_url | resize: '100x100' | image_tag }}
    {% else %}
        {{ 'favicon.png' | theme_image_url | resize: '100x100' | image_tag }}
    {% endif %}

Let's check in the browser on the Wagon server. This is fine.
Let's check in the Wagon server logs. The server complains:

     [index] missing editable_file "logo" (content/main)

If I push my website to the Engine, the default image displays properly also in the preview.
If I go to the back-office on my index page, an editable zone has been added to the right column that tells me "no file".
If I click on change and choose upload file, and then effectively upload a new logo (let's call it logo.png) and click save, everything is saved properly.

However, in the preview, the logo displayed on my index page remains favicon.png and not my new logo.

**Step five** Trying to solve the issues

Let's first make disappear the message in the Wagon server logs. In the header section of my index.liquid page, I add an editable_elements section with the following key:

    editable_elements:
        'content/main/logo': "favicon.png"

Wagon seems to be happy, it still displays properly my default logo. And the message in the logs has disappeared. Let's push it!

On the Engine side, my default logo still appears in the preview.

However, the same issue as exposed above (can't change the default logo) remains.

The issue seems to be related to the fact that logo_url never != '' never evaluates to true. If I do:

    {% if logo_url != '' %}
      beep
    {% else %}
      boop
    {% endif %}

I always boop and never beep. Worse, If I do:

    <div>Div before the drop</div>
    <div>{{ logo_url }}</div>

to check what gets captured, it seems that nothing gets captured at all, even after editing the page in the back-office. So basically the solution proposed in the documentation does not work.

The documentation for the previous version of Locomotive provided another way to do this:

    {% capture logo_url %}{% editable_file 'logo' %}'public/images/favicon.png'{% endeditable_file %}{% endcapture %}
    {% if logo_url != '' %}
      {{ logo_url | resize: '100x100' | image_tag }}
    {% else %}
      {{ 'favicon.png' | theme_image_url | resize: '100x100' | image_tag }}
    {% endif %}

but this does no longer work in Wagon (the image does not get displayed, steam does not seem to be able to located the file).

Doing this;

    {% capture logo_url %}{% editable_file 'logo' %}favicon.png{% endeditable_file %}{% endcapture %}
    {% if logo_url != '' %}
      {{ logo_url | resize: '100x100' | theme_image_tag }}
    {% else %}
      {{ 'favicon.png' | theme_image_url | resize: '100x100' | image_tag }}
    {% endif %}

does not change anything. Still broken at steam level.

----
In addition to this first issue, please note that it would be nice if the editable_files could be preloaded to a public/samples directory as it was possible in version 2.

It is weird to store elements that are going to be editable in a directory such as images which should obviously be used to store theme images. The trouble is that if I create a public/samples directory in the Wagon

    mkdir public/samples

and copy my file to this public directory:

    cp public/images/favicon.png public/samples/favicon.png

and then try to reference the image from such directory inserting the following code into my homepage:

    {% capture logo_url %}{% editable_file 'logo' %}{% endeditable_file %}{% endcapture %}
    {% if logo_url != '' %}
      {{ logo_url | resize: '100x100' | image_tag }}
    {% else %}
      {{ 'public/samples/favicon.png' | theme_image_url | resize: '100x100' | image_tag }}
    {% endif %}

this will work in Wagon, but not in the Engine (as a matter of fact, this will completely break the Engine due to the Dragonfly / Puma bug). This is due to the fact that Engine timestamps asset files other than those related to the theme and the url 'public/samples/favicon.png' does not properly make reference to my preloaded asset file.

**Comment by did** [comment]
@CedricLor. That should solve all your problems:

````liquid
<img src="{% editable_file 'logo' %}/samples/favicon.png{% endeditable_file %}" />
````

By default, it will display the ````/samples/favicon.png```` file (don't worry, Wagon / Engine doing the translation between the local path to the remote url). 
If your users want to have a different logo, they have to upload a new image from the back-office. If they want to go back to the default logo, they have to click on the remove button for this specific editable file.

**Comment by did** [comment]
Alright, there was indeed a bug with editable_file elements created by the API inside a **localized** site. I spent almost 2 days fixing this one. Here is the patch + spec (@d1064b13965e47a79875fcfd).
