### ISSUE TITLE
Is there a way to add individual components to customize pages uniquely instead of just using parent layouts?

### ISSUE THREAD

**Issue by TommyByrne** [locomotivecms/engine#1095]
Trying to create a  number of custom blocks or content_types that can be individually added to different pages and in different orders.  Is this something that Locomotive CMS can currently handle or am I going down the wrong path? 

Thanks

**Comment by did** [comment]
@TommyByrne, that's already a feature planned for v4: https://github.com/locomotivecms/engine/issues/835.
I know that the power of the content type functionality can make you think that building a page with blocks is largely doable. But the the truth is that it's way more complicated than just declaring content types.
However, content types are definitively part of the solution. I've in mind a solution based on content types and reactJS (for the live preview mode). I'm working on a prototype :-)

**Comment by TommyByrne** [comment]
@did Thank you for the quick response. Today was my first time digging into Locomotive and set up both V2 and V3  and its amazing the difference. Keep up the good work!  Look forward to seeing how things continue to develop.
