### ISSUE TITLE
many_to_many relationship created in UI for loop error

### ISSUE THREAD

**Issue by peterfealey** [locomotivecms/engine#1097]
When adding a many_to_many relationship in the Locomotive UI any for loops using the relationship do not output anything

```
{% with_scope publish_date.lte: today %}

{% for article in contents.articles %}

<div class="row mix{% for tag in article.tags %} {{ tag.title | remove: " " | remove: "'" }}{% endfor %}" id="article_tagged">
                  <div class="col-md-6">
                  <img src="{{ article.featured_image.url | resize: '550x' }}" class="img img-responsive" />
                  </div>

					<div class="col-md-6">
					<h3>{{ article.title }}</h3>
					<p>{{ article.synopsis }}</p>
					<p><a href="/africa-blog/{{ article._slug}}">Read More...</a></p>
                    </div>
</div>






{% endfor %}

{% endwith_scope %}

```

The following specifically is the section that's not returning anything

```
<div class="row mix{% for tag in article.tags %} {{ tag.title | remove: " " | remove: "'" }}{% endfor %}"
 ```

**Comment by allanbreyes** [comment]
I've ran into this issue.  I haven't looked too deeply into this, but here are a couple things to try:

1. Upgrade to latest engine.  There was an issue with `with_scope` applying to child queries #806, and you may be scoping tags with `publish_date.lte: today` (which would probably return nil).
2. I forget the syntax or use cases, but sometimes adding a `.all` helps, e.g. `for tag in article.tags.all`.

**Comment by peterfealey** [comment]
@allanbreyes Thanks so much for taking the time to get back to me. 

I haven't tried upgrading engine as yet as it's a production site and this close to Christmas I don't need the stress - but I've tried the other suggestions to no avail. The most annoying part is that it's a multi-site installation and it's working without a problem on one of the counterpart sites! I'll see if @did has anything to add :/

**Comment by did** [comment]
@peterfealey. as @allanbreyes (thank you btw) mentioned it, if you use the last commit, you shouldn't get this bug again.
If you don't want to upgrade, see the work-around here: https://github.com/locomotivecms/engine/issues/806.
