### ISSUE TITLE
"capture" with empty "editable_file" doesn't work

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1099]
REPRO

1. I want to make editable file image with default picture.
1. I've used `editable_file` tag suitable to example from [How to use editable image with a default value?](https://locomotive-v3.readme.io/docs/tags#section-how-to-use-editable-image-with-a-default-value-):

    ```
    {% capture banner_url %}{% editable_file 'banner' %}{% endeditable_file %}{% endcapture %}
    {% if banner_url != '' %}
      <h3>banner_url: {{ banner_url }}</h3>
    {% else %}
      <h3>banner_url is empty</h3>
    {% endif %}
    ```
1. I've pushed it to the Engine.
1. In the back-office I've uploaded jpg image and selected it as `Banner` field.

WHATS WRONG
1. View shows:

```
banner_url is empty
```

IT SHOULD BE

1. `banner_url` param should not be empty
1. View should show something like that:

```
banner_url: /sites/568828bb2f9e6319e5000001/pages/568828bb2f9e6319e5000003/files/Banner.png?1451764856&editable-path=content--main--banner
```

TIPS

1. I've found that the problem is if I have empty `editable_file` -> `{% editable_file 'banner' %}{% endeditable_file %}`
2. If I add at least one letter inside the `editable_file` tag the problem will disappear:
```
{% capture banner_url %}{% editable_file 'banner' %}a{% endeditable_file %}{% endcapture %}
```
3. The problem is connected with #1092

**Comment by did** [comment]
@adam-pl I think there is a misunderstanding around the **editable_file** liquid tag.

If you want to use a default image, it's easy, just write this:

````liquid
{% editable_file banner %}/samples/default_banner.png{% endeditable_file %}
````

Assuming that ````public/samples/default_banner.png```` is a valid image.

**Comment by adam-pl** [comment]
1. OK, now after your explanation that's clear for me.

My issue was created because of [original ducomentation's example](https://locomotive-v3.readme.io/docs/tags#section-how-to-use-editable-image-with-a-default-value-):
```
{% capture banner_url %}{% editable_file 'banner' %}{% endeditable_file %}{% endcapture %}
{% if banner_url != '' %}
  {{ banner_url | image_tag }}
{% else %}
  {{ 'banner.png' | theme_image_tag }}
{% endif %}
```
This example doesn't work properly.
2. I have a trouble with using `{% editable_file banner %}/samples/default_banner.png{% endeditable_file %}` with `wagon push` I get following error returned by the Engine installed in production:
```
ERROR -- : [API] undefined method `<' for nil:NilClass
```
I'm trying to investigate the problem

**Comment by did** [comment]
@adam-pl 

1. The code from the documentation is wrong. Let me fix that.

2. Does the /samples/default_banner.png exist in your Wagon site? If so, could you get the full stack trace?

thanks!

**Comment by did** [comment]
documentation updated: https://locomotive-v3.readme.io/v3.0/docs/tags#section-how-to-use-editable-image-with-a-default-value-

**Comment by adam-pl** [comment]
Ad.1 Thank you @did. Now examples are much simplier - that's very good :)
Ad.2. Yes, it does. Actually the problem has gone after reinstalation with the Capistrano.
I'm not sure what the reason was excactly because of a few things done as I remember:
 - adding `apt-get -y install nodejs imagemagick` (added instalation of missed packages)
 - rollback original `config/initializers/dragonfly.rb` file (previous it was used new `dragonfly.rb` file generated with command `rails generate dragonfly`.

I was trying to use ` datastore :file` instead of ` datastore :memory` of the Dragonfly without success for now. 

Anyway I'll report the problem if I find it again. For now the Wagon pushes my site with success.

**Comment by adam-pl** [comment]
I notified that "capture" with empty "editable_file" doesn't work inside a snippet (I mean default picture will not be loaded).

One thing is interested: If I create new block inside my snipped:
```
{% block 'content/slider' %}
{% endblock %}
```
and move capture & editable_file from my snippet to the `index.liquid` inside `block 'content/slider'`, default image file it will work!

I'm not sure if I am clear. I spent a few hours with this issue. 

Do you need detailed repro to check this problem?
