### ISSUE TITLE
if site `picture_url` is missing, General Settings becomes unavailable (throws 500)

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1103]
**Repro**:
- delete the picture_url source icon in your S3 bucket
- try clicking General Settings (you'll get a 500)

**Comment by craft37** [comment]
Have the same issue.

Firstly I've setup a AWS credentials with wrong Location Constraint (eu-central-1 for Francfurt).
I changed a picture in 'Editing the current site' and got a error.

```
Seahorse::Client::NetworkingError
```

Than when I checked AWS credentials and setted up right location, I've got this error till I recreate site. 

```
Aws::S3::Errors::NotFound in Locomotive::CurrentSiteController#edit
```

Now I cannot destroy this website cause cannot open General Settings
