### ISSUE TITLE
Cursor (.cur) files are blocked

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1107]
My .css file contains custom cursor style like that:

```
.post-hand-cursor {
	cursor:url("../images/cursors/post-hand.cur"), move;
}
```
When I push site to the Engine I'll get following error:
> Resource invalid: source You are not allowed to upload "cur" files, allowed types: jpg, jpeg, gif, png, css, js, swf, flv, eot, svg, ttf, woff, woff2, otf, ico, htc, map can't be blank
Resource invalid: source You are not allowed to upload "cur" files, allowed types: jpg, jpeg, gif, png, css, js, swf, flv, eot, svg, ttf, woff, woff2, otf, ico, htc, map can't be blank

The reason is `.cur` file format is not allowed.

See more info [Controlling cursors with CSS and creating .cur files | CSS, JavaScript and XHTML Explained](http://www.evotech.net/blog/2007/04/controlling-cursors-with-css-and-creating-cur-files/).

**Comment by allanbreyes** [comment]
Can't you whitelist that in the config?

**Comment by adam-pl** [comment]
Thanks :)

**Comment by did** [comment]
you're welcome :-)
