### ISSUE TITLE
Sprockets mismatch in compass-rails

### ISSUE THREAD

**Issue by aeberlin** [locomotivecms/engine#1108]
Probably should add a note about using the `master` branch of `compass-rails` instead of the most recent release on rubygems.org, in order to avoid this error:

`NameError at / uninitialized constant Sprockets::SassCacheStore`

Below resolves it for me:

```ruby
gem 'compass-rails',
  branch: 'master',
  git: 'https://github.com/Compass/compass-rails'
```

**Comment by did** [comment]
hey @aeberlin, I'm confused, I see no trace about the compass-rails gem inside the Engine.

**Comment by aeberlin** [comment]
`compass-rails` was updated to 3.0.0 about a week ago, which seems to have resolved the issue.
