### ISSUE TITLE
"capture" with empty "editable_file" doesn't work outside the block

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1110]
This issue is connected to #1099.

REPRO

1. Create new project with bootstrap template
1. Add following code to the file `app/views/pages/index.liquid`:

  ```
<div class="row">
  {% capture banner_url %}{% editable_file 'banner' %}/samples/below_clouds.jpg{% endeditable_file %}{% endcapture %}

  {% if banner_url != '' %}
    <h3>banner_url: {{ banner_url }}</h3>
  {% else %}
    <h3>banner_url is empty</h3>
  {% endif %}

  <h3>1. Image not scaled:</h3>
  <img src="{{ banner_url }}" alt="image not scaled" />
  
  <h3>2. Image scaled (200x100 pixels):</h3>
  <img src="{{ banner_url | resize: '200x100#' }}" alt="image scaled to 200x100" width="200" height="100" />
</div>
  ```
1. I assume image file `/samples/below_clouds.jpg` exists.
1. Push the site to the Engine. Open browser. We should get info:

    > banner_url: /sites/56953cb02f9e634937000000/assets/56953d032f9e63493700004f/below_clouds.jpg?editable-path=content--main--banner

1. Two images should be showed (the first one has original size, the second one should be scaled).
1. Now create snippet named `picture`:

    ```
    bundle exec wagon generate snippet picture
    ```
1. Move mentioned code (`<div class="row">...</div>`) from `app/views/pages/index.liquid` into created snippet file `app/views/snippets/picture.liquid`:
    ```
{% raw %}
<!-- To use your snippet, just add the following code in your page template-->
<!-- {% include picture %} -->
{% endraw %}

<div class="row">
  {% capture banner_url %}{% editable_file 'banner' %}/samples/below_clouds.jpg{% endeditable_file %}{% endcapture %}

  {% if banner_url != '' %}
    <h3>banner_url: {{ banner_url }}</h3>
  {% else %}
    <h3>banner_url is empty</h3>
  {% endif %}

  <h3>1. Image not scaled:</h3>
  <img src="{{ banner_url }}" alt="image not scaled" />
  
  <h3>2. Image scaled (200x100 pixels):</h3>
  <img src="{{ banner_url | resize: '200x100#' }}" alt="image scaled to 200x100" width="200" height="100" />
</div>
    ```
1. Edit file `app/views/layouts/default.liquid` and add `{% include picture %}` line inside `body` tags:
    ```
  <body>
    {% include 'nav' %}

    <div class="container">
      {% include picture %}
    </div>

    {% block content %}
    {% endblock %}

    {% include 'footer' %}

    {{ 'jquery.min.js' | javascript_tag }}
    {{ 'bootstrap.min.js' | javascript_tag }}
    {{ 'application.js' | javascript_tag }}
  </body>
    ```
1. Push our site to the Engine again and open browser

WHAT'S WRONG
1. We get incorrect path:

    > banner_url: /samples/below_clouds.jpg?editable-path=banner
1. Original image is not visible
1. Scaled image is also not visible

IT SHOULD BE
1. `banner_url` path should begins with `/sites/`
1. Both images shoud be visible

TIPS
1. The Engine's logs shows that image path is not correct:

    > DRAGONFLY: caught error - Command failed ('/usr/bin/convert' '/home/adam/svn/PGS/engine/public/samples/below_clouds.jpg' '-resize' '200x100^^' '-gravity' 'Center' '-crop' '200x100+0+0' '+repage' '/tmp/dragonfly20160113-4347-r39sw1.jpg') with exit status 1 and stderr convert: unable to open image `/home/adam/svn/PGS/engine/public/samples/below_clouds.jpg'

**Comment by did** [comment]
hi @adam-pl, as mentioned in the documentation, no editable elements in snippets because of potential weird behaviours ;-)

**Comment by adam-pl** [comment]
Well, I've found a way that I can use `editable_file` in snippets:

1. Add empty block at the beggining of a snippet file:

  ```
{% block 'data' %}
{% endblock %}
  ```
1. Add `capture` & `editable_file` into `index.liquid` file (page):

  ```
  {% block 'data' %}
    {% capture banner_url %}{% editable_file 'banner' %}/samples/below_clouds.jpg{% endeditable_file %}{% endcapture %}
  {% endblock %}
  ```
1. Add rendering part in a snippet file:

  ```
<h3>1. Image not scaled:</h3>
<img src="{{ banner_url }}" alt="image not scaled" />
  ```

It's working for me with over 10 snippet files :-)
I use also `editable_text` tag with success.
