### ISSUE TITLE
"capture" & "editable_file" generates <span> tag inside anchor

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1113]
This issue is connected to #1099.

REPRO

1. Create new project with bootstrap template
1. Add following code to the file `app/views/pages/index.liquid`:

  ```
<div class="row">
  {% capture 'phone_1' %}{% editable_text text_phone_1, label: 'Phone 1', hint: 'Your phone number', format: 'row', line_break: false, rows: 1 %}(530) 277 2778{% endeditable_text %}{% endcapture %}
  {% capture 'email_1' %}{% editable_text text_email_1, label: 'E-mail', hint: 'Your E-mail address', format: 'row', line_break: false, rows: 1 %}carservice@gmail.com{% endeditable_text %}{% endcapture %}

  <ul>
    <li class="template-phone">
      <a href="tel:{{ phone_1 | replace: ' ' }}">{{ phone_1 }}</a>
    </li>
    <li class="template-mail">
      <a href="mailto:{{ email_1 }}">{{ email_1 }}</a>
    </li>
  </ul>
</div>
  ```
1. Push the site to the Engine. 
1. Open browser. We'll get linked correct phone and email address:

  ```
  * (530) 277 2778
  * carservice@gmail.com
  ```
1. Now go to the back-office and change:
  * phone number to `(530) 111 2222`
  * email address to `washservice@gmail.com`
1. Refresh your page.

WHAT'S WRONG

1. We'll get incorrect phone number and email address:

  ```
  * (530)1112222">(530) 111 2222
  * washservice@gmail.com">washservice@gmail.com
   ```
1. Tag `<span>` is inserted into `<a>` tag twice:

  ```
<ul>
    <li class="template-phone">
      <a href="tel:&lt;spanclass=" locomotive-editable-text"id="locomotive-editable-text-content-main-naglowek_telefon_2" data-element-id="5698b5e22f9e630ea8000000">(530)1112222"&gt;<span class="locomotive-editable-text" id="locomotive-editable-text-content-main-naglowek_telefon_2" data-element-id="5698b5e22f9e630ea8000000">(530) 111 2222</span></a>
    </li>
    <li class="template-mail">
      <a href="mailto:&lt;span class=" locomotive-editable-text"="" id="locomotive-editable-text-content-main-naglowek_email_1" data-element-id="5698b5e22f9e630ea8000001">washservice@gmail.com"&gt;<span class="locomotive-editable-text" id="locomotive-editable-text-content-main-naglowek_email_1" data-element-id="5698b5e22f9e630ea8000001">washservice@gmail.com</span></a>
    </li>
  </ul>
  ```

IT SHOULD BE

1. `<span>` tag should not be inserted into `<a>` tag after data is changed in the back-office
1. We should get correct phone number and email address:

  ```
  * (530) 111 2222
  * washservice@gmail.com
  ```

TIPS
1. The issue is not corrected with snippets.

**Comment by did** [comment]
@adam-pl quick work-around

Assuming that your editable_text are wrapped in a block called **main**. 

````liquid
<div class="row">
{% capture 'phone_1' %}{% editable_text text_phone_1, label: 'Phone 1', hint: 'Your phone number', format: 'row', line_break: false, rows: 1 %}(530) 277 2778{% endeditable_text %}{% endcapture %}
{% capture 'email_1' %}{% editable_text text_email_1, label: 'E-mail', hint: 'Your E-mail address', format: 'row', line_break: false, rows: 1 %}carservice@gmail.com{% endeditable_text %}{% endcapture %}

<ul>
  <li class="template-phone">
    <a href="tel:{{ page.editable_elements.main.phone_1 }}">{{ phone_1 }}</a>
  </li>
  <li class="template-mail">
    <a href="mailto:{{ page.editable_elements.main.email_1 }}">{{ email_1 }}</a>
  </li>
</ul>
</div>
````

**Comment by adam-pl** [comment]
Wow, it really works.
Thank you @did.

Will be possible using `phone_1` param without `page.editable_elements.main` in the future?

**Comment by adam-pl** [comment]
Wait a moment...something is wrong...

**Comment by adam-pl** [comment]
I needed to change two things:
  - adding `'content' block to the path
  - adding `text_` prefix to param name

Now I have in my view:
  ```
  <ul>
    <li class="template-phone">
      <a href="tel:{{ page.editable_elements.content.main.text_phone_1 }}">{{ phone_1 }}</a>
    </li>
    <li class="template-mail">
      <a href="mailto:{{ page.editable_elements.content.main.text_email_1 }}">{{ email_1 }}</a>
    </li>
  </ul>
  ```

And it works fine :-)

**Comment by adam-pl** [comment]
Docs [Tags / Page](https://locomotive-v3.readme.io/docs/drops#page) doesn't say about `editable_elements` attribute.

Thank you @did for help :-)

Is there any chance to work it with `capture` in the future?

**Comment by did** [comment]
@adam-pl you're welcome!

You're right I need to update the documentation.

My only advice, stay away from capture with editable_elements :-) For instance, if you need to resize an editable_file image, use its **resize** option instead (as described in the documentation) ;-)

**Comment by did** [comment]
@adam-pl the documentation has been updated!

**Comment by adam-pl** [comment]
@did, thank you again for updating docs & advice.

Now I'm not sure what to do if I need use image twice with two different scale.
`editable_file` has `resize` options but it only generates one scale.

I do not want to make two `editable_file` fields with the same picture.
