### ISSUE TITLE
Display the page in public 

### ISSUE THREAD

**Issue by cpvinh** [locomotivecms/engine#1118]
Hi @did 
After I upgraded to v3, I don't see the pages controller in public. So I can't view a page with path /page-title. When I request the page /page-title, the system always takes me to /locomotive/sites. Please explain and show me this?

**Comment by did** [comment]
hi @cpvinh, the rendering mechanism has been extracted and moved to its own "gem" called Steam (https://github.com/locomotivecms/steam). 
If you're logged in, you can preview a page at this url: http://yourlocomotivebackofficedomain/locomotive/sites/<site-handle>/preview/<page-path>
If you bind a domain name to your site (https://locomotive-v3.readme.io/docs/domains), the url will be: http://<your-site-domain>/<page-path>.
Last thing, Locomotive v3 is only multi-sites (in v2, you could choose to use Locomotive just for hosting one single single).
