### ISSUE TITLE
Many mongoid connections

### ISSUE THREAD

**Issue by benoist** [locomotivecms/engine#1120]
I'm getting a lot of connections in my production environment resulting in to many open files.
Last time I checked I had over 11000 open connections.

This could well be a mongoid problem, just wondering if anyone else has this problem as it's a standard rails application with only the engine.

  * locomotivecms (3.0.0)
  * locomotivecms-liquid (4.0.0)
  * locomotivecms-solid (4.0.1)
  * locomotivecms_common (0.0.5)
  * locomotivecms_steam (1.0.0)

  * mongo (2.2.2)
  * mongo_session_store-rails4 (6.0.0)
  * mongoid (5.0.2)
  * mongoid-grid_fs (2.2.1)
  * mongoid-tree (2.0.1)

**Comment by did** [comment]
hi @benoist, that's a lot! Hmmm, I'm wondering if this could be related to Steam which doesn't use Mongoid to access MongoDB. We use the official ruby mongo driver. I need to spend time on it.

**Comment by benoist** [comment]
Yeah it's too many :) 
I think I may have found something worth looking at:

https://jira.mongodb.org/browse/MONGOID-4108
https://github.com/mongoid/mongoid/commit/5ff1bb816fe98ac198c548e2760cf785d58a8778

This is an issue with the mongoid driver opening a new client for each thread and storing it in thread local. If a new thread is created but the old ones not cleared the connection stays open.

The same issue might apply to steam as well if I look at this line:

https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/adapters/mongodb.rb#L89

**Comment by did** [comment]
hmm, @benoist, new version of mongoid here: https://rubygems.org/gems/mongoid/versions/5.1.0. 
Did you test it? If not, could you please and let me know if it's fixed your issue?
thanks!

**Comment by benoist** [comment]
I can't update as the engine version has it locked at 5.0.x

**Comment by jaykay** [comment]
Hi, i can confirm this issue. My connection count / used memory is permanently increasing and when hitting the system limits it crashes. Restarting puma helps, though.

**Comment by benoist** [comment]
I can also confirm that restarting puma works. Perhaps this is only an issue with threaded webservers. In a forking environment like passenger or unicorn this might not be an issue.

**Comment by did** [comment]
locomotive.works runs with Passenger, no memory issue as far as I know. Passenger has a feature which restarts Rails processes anyway if they consume too much memory.

**Comment by jaykay** [comment]
IMHO the most bothering thing isn't the memory here but the db connections. I measured almost 2k new connections the last hour. As they seem to be never cloesed, I would have to write a job that restarts puma every 5-6 hours. If found [this article](http://blog.mongolab.com/2013/11/deep-dive-into-connection-pooling/) perfectly describing the issue, but I didn't found a workaround for locomotive v3 so far.

**Comment by did** [comment]
2 things to try on your side before I dig into it:

- install and use Mongoid 5.1.0. The only way is to fork Locomotive Engine, change the gemspec, commit and push back to git. Make the Gemfile of your Rails app point to that Engine.
- change the min/max pool size in your config/mongoid.yml and see if it changes something or not.

**Comment by benoist** [comment]
@did did you check the Thread.current assignment in Steam? That creates a new client for every thread but it could  be that they are never closed. At least that was the issue in Mongoid. As you indicated that Steam does not use mongoid and uses the Thread.current, this could well be the same issue.

**Comment by did** [comment]
@benoist you're absolutely right, it could be that indeed. I really don't know what's the best strategy to close them at the right time.

**Comment by did** [comment]
hmm, okay, I see, we need a factory. I really thought that the MongoDB ruby driver was handling that.

**Comment by benoist** [comment]
I thought the mongo driver already has a connection pool, so I don't know if the client can just be created once and assigned to a constant or singleton?

**Comment by jaykay** [comment]
Okay, I tried out `max_pool_size` and `min_pool_size` so far. None of them seem to have any effect on that issue. I didn't test mongoid 5.1.0 though, perhaps I'll could do that on the weekend.

**Comment by benoist** [comment]
I think those settings only work if you reuse the client. If you create a new client per thread, connection pooling is not used as only one thread handles one request.

**Comment by did** [comment]
@benoist agreed on that, makes totally sense. So, let's test it without the Thread.current stuff in Steam. 
Btw, are you able to reproduce that behaviour locally?

**Comment by benoist** [comment]
I can check that maybe tonight.

**Comment by did** [comment]
I'll be online late in Gitter if you need me

**Comment by jaykay** [comment]
I was able to reproduce locally:

I added puma to `Gemfile`

    gem "puma"

`bundle install`

A ran a local Docker Container with mongo:

    $ docker run -d -p 27017:27017 mongo

and ran puma like:

    $ puma -e production

In a new window I opened mongostat like:

    $ docker exec -ti <name_of_container> mongostat

I then simply opened irb:

    25.times do 
      `google-chrome http://localhost:9292`
    end

This perhaps causes "a little" system load ;D

The number of connections increased with every browser connection (notice the `conn` column):

    insert query update delete getmore command flushes mapped  vsize   res faults qr|qw ar|aw netIn netOut conn     time
    *0     5     *0     *0       0     3|0       0 160.0M 564.0M 44.0M      0   0|0   0|0  814b    12k   45 17:02:54
    *0    10     *0     *0       0     6|0       0 160.0M 566.0M 44.0M      1   0|0   0|0    2k    15k   47 17:02:55
    *0     5     *0     *0       0     6|0       0 160.0M 566.0M 44.0M      0   0|0   0|0  988b    13k   47 17:02:56
    *0     5     *0     *0       0     4|0       0 160.0M 566.0M 44.0M      0   0|0   0|0  872b    12k   47 17:02:57
    *0     7     *0     *0       0     6|0       0 160.0M 568.0M 44.0M      1   0|0   0|0    1k    13k   49 17:02:58
    *0     8     *0     *0       0     7|0       0 160.0M 570.0M 44.0M      1   0|0   0|0    1k    15k   51 17:02:59
    *0     5     *0     *0       0     6|0       0 160.0M 570.0M 44.0M      0   0|0   0|0  988b    13k   51 17:03:00
    *0     5     *0     *0       0     5|0       0 160.0M 570.0M 44.0M      0   0|0   0|0  930b    13k   51 17:03:01
    *0     8     *0     *0       0     6|0       0 160.0M 574.0M 44.0M      2   0|0   0|0    1k    13k   55 17:03:02
    *0     7     *0     *0       0     5|0       0 160.0M 576.0M 44.0M      2   0|0   0|0    1k    14k   57 17:03:03
    insert query update delete getmore command flushes mapped  vsize   res faults qr|qw ar|aw netIn netOut conn     time
    *0     5     *0     *0       0     3|0       0 160.0M 576.0M 44.0M      0   0|0   0|0  814b    12k   57 17:03:04
    *0     5     *0     *0       0     6|0       0 160.0M 579.0M 44.0M      1   0|0   0|0  988b    13k   59 17:03:05
    *0     5     *0     *0       0     6|0       0 160.0M 579.0M 44.0M      0   0|0   0|0  988b    13k   59 17:03:06
    *0     5     *0     *0       0     3|0       0 160.0M 579.0M 44.0M      0   0|0   0|0  814b    12k   59 17:03:07
    *0     5     *0     *0       0     5|0       0 160.0M 579.0M 44.0M      0   0|0   0|0  926b    12k   59 17:03:08
    *0     5     *0     *0       0     8|0       0 160.0M 581.0M 43.0M      0   0|0   0|0    1k    13k   61 17:03:09
    *0     6     *0     *0       0     7|0       0 160.0M 584.0M 40.0M      1   0|0   0|0    1k    13k   64 17:03:10
    *0     9     *0     *0       0     7|0       0 160.0M 585.0M 38.0M      1   0|0   0|0    2k    15k   65 17:03:11
    *0     5     *0     *0       0     5|0       0 160.0M 585.0M 31.0M      0   0|0   0|0  930b    13k   65 17:03:12

I did this until reaching 100+ connections then closed all browser windows but connections never decreased. If you haven't installed docker this should be reproducible with local mongo db, too

**Comment by benoist** [comment]
I can confirm that it's creating a new connection on every request
altered the code to:

```

```

Gives output

```

**Comment by did** [comment]
@benoist I ran some tests on my dev and local version of locomotive.works running Puma and my patch and I didn't see the connection issue (the number of connections stays stable).

**Comment by jaykay** [comment]
I confirm that using `master` of steam resolves this issue.
