### ISSUE TITLE
[Liquid] query different document types in a single query

### ISSUE THREAD

**Issue by did** [locomotivecms/engine#1121]
[Todo in Steam]. allow "contents.all" to return all the content entries of the current site (no matter the content type they belong to).

Example:

``` liquid
{% with_scope content_type_slug.in: ['articles', 'whitepapers'], published: true, order_by: 'published_at' %}
  {% for document in contents.all %}
      {% if document.content_type_slug == 'articles' %}
      ...
      {% else if document.content_type_slug == 'whitepapers' %}
      ...
      {% endif %}
  {% endfor %}
{% endwith_scope %}
```

**Comment by stunjiturner** [comment]
Yes, I need that done.

**Comment by did** [comment]
I don't think this is a good idea anymore. We should use the [locomotive search gem](https://github.com/locomotivecms/search) instead if we're looking for the search functionality.
