### ISSUE TITLE
editable_text + "fixed: true" + page.editable_elements = doesn't work

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1126]
REPRO

1. Create new project with bootstrap template
1. Insert following code into file `app/views/pages/layouts/simple.liquid` before last line `{% endblock %}`:

  ```
  <hr />
  {% capture copyright %}{% editable_text copyright, fixed: true, label: 'Copyright', hint: 'Copyright info', format: 'row', line_break: false, rows: 1 %}NO COPYRIGHT{% endeditable_text %}{% endcapture %}
  <h5>page.editable_elements.content.copyright: {{ page.editable_elements.content.copyright }}</h5>
  <h5>copyright: {{ copyright }}</h5>
  ```
1. Create "Books" page (`bundle exec generate page books`)
1. Push new project to the Engine
1. Go to the back-office, click `Home Page` and change `copyright` value from `NO COPYRIGHT` to  `(C) BOOKER` & and save your changes
1. Open index page and check `page.editable_elements.content.copyright` and `copyright` values
1. Open books page and check the same values

WHAT'S WRONG

1. `page.editable_elements.content.copyright` value shows `NO COPYRIGHT` instead of `(C) BOOKER` on both pages (index & books) - edited data from back-office is skipped
1. copyright shows `(C) BOOKER` on both pages but it has <span> tags - this issue is known so that we use `page.editable_elements.content.copyright` - unfortunately it doesn't work.

TIPS

1. We've used `fixed: true` for showing once edited copyright on both pages
1. If we add following line into file `app/views/pages/layouts/simple.liquid`

    ```
    <h5>{% editable_text copyright2, fixed: true, label: 'Copyright 2', hint: 'Copyright info 2', format: 'row', line_break: false, rows: 1 %}NO COPYRIGHT 2{% endeditable_text %}</h5>
    ```
and edit `copyright`value in the back-office
we'll get added `<span>` tag. 
So we are trapped, specially if we want to make anchor tag with e-mail address like that:
  ```
  <a href="mailto:{{ page.editable_elements.content.email }}">{{ page.editable_elements.content.email }}</a>
  ```
1. The `<span>` problem is minor.
1. We need to use `page.editable_elements.content.email` if we want to use e-mail address a few times and want to edit email only once time.

![selection_065](https://cloud.githubusercontent.com/assets/2798350/13022532/797ebd4a-d1e2-11e5-9742-806ff77b3143.png)

![selection_066](https://cloud.githubusercontent.com/assets/2798350/13022544/949f885c-d1e2-11e5-8ec6-2508763b8640.png)

![selection_067](https://cloud.githubusercontent.com/assets/2798350/13022586/cecc9a92-d1e2-11e5-93ff-adb53a323673.png)

**Comment by did** [comment]
@adam-pl I love your bug reports :-) Sorry to mention that each time I read one of your issues in Github ;-)

Okay, this one is difficult to fix and I'm not sure it's worth it. Let me explain.

First, page.editable_elements was not planed to be implemented. I've to do it to solve your <SPAN> issue. It works but it has a lot of limitations like the one you described.

Secondly, we're about to launch a new feature called "site metafields" (https://trello.com/c/GIIT9NYJ/90-feature-add-meta-properties-to-a-site). In your case, that's exactly what you need. You will then define an email and a copyright fields only for your site. 
Then, you'll access it in liquid like this: ````{{ site.metafields.my_company.email }}```` and ````{{site.metafields.my_company.copyright }}````. 

Hope to release this very soon.
