### ISSUE TITLE
Inline Editing in V3

### ISSUE THREAD

**Issue by cpvinh** [locomotivecms/engine#1127]
Hi @did 

Currently, I don't see the button so that I can toggle it and edit content inline without going to admin management as old version.
Was that feature removed in V3?

Thank you.

**Comment by nielsenramon** [comment]
@cpvinh There is indeed no toggle button anymore. You can now edit every text field on the right side in the page. All changes will be live updated in the preview. 

What's also useful for bigger pages is that you now can hover the text on the preview and click the edit button to jump to the correct 'editable_text' field. 

See:

![image](https://cloud.githubusercontent.com/assets/1246672/13394868/6360ce66-deeb-11e5-9e06-b7bb3db61a3e.png)
