### ISSUE TITLE
exception: can't create Value of BSON type Symbol (16002) when create new site

### ISSUE THREAD

**Issue by eugenemelnikov** [locomotivecms/engine#1128]
I have this exception because of using mongo 2.2.3 or this is another problem? (ruby 2.2.0)

Stacktrace:

> mongo (2.2.3) lib/mongo/operation/result.rb:256:in `validate!'
> mongo (2.2.3) lib/mongo/operation/executable.rb:36:in`block in execute'
> mongo (2.2.3) lib/mongo/server/connection_pool.rb:108:in `with_connection'
> mongo (2.2.3) lib/mongo/server/context.rb:63:in`with_connection'
> mongo (2.2.3) lib/mongo/operation/executable.rb:34:in `execute'
> mongo (2.2.3) lib/mongo/collection/view/aggregation.rb:118:in`send_initial_query'
> mongo (2.2.3) lib/mongo/collection/view/iterable.rb:41:in `block in each'
> mongo (2.2.3) lib/mongo/retryable.rb:51:in`call'
> mongo (2.2.3) lib/mongo/retryable.rb:51:in `read_with_retry'
> mongo (2.2.3) lib/mongo/collection/view/iterable.rb:39:in`each'
> mongoid (5.0.2) lib/mongoid/contextual/aggregable/mongo.rb:26:in `to_a'
> mongoid (5.0.2) lib/mongoid/contextual/aggregable/mongo.rb:26:in`aggregates'
> mongoid (5.0.2) lib/mongoid/contextual/aggregable/mongo.rb:67:in `max'
> mongoid (5.0.2) lib/mongoid/contextual.rb:12:in`max'
> mongoid (5.0.2) lib/mongoid/relations/many.rb:10:in `max'
> locomotivecms (3.0.0) app/helpers/locomotive/base_helper.rb:232:in`cache_key_for_sidebar_pages'
> locomotivecms (3.0.0) app/views/locomotive/shared/_sidebar.html.slim:7:in `block in __home_evgeniy__rvm_rubies_ruby_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_shared__sidebar_html_slim___442791941732398528_70150264726500'
> actionview (4.2.5) lib/action_view/helpers/cache_helper.rb:117:in`cache'
> locomotivecms (3.0.0) app/views/locomotive/shared/_sidebar.html.slim:3:in `__home_evgeniy__rvm_rubies_ruby_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_shared__sidebar_html_slim___442791941732398528_70150264726500'
> actionview (4.2.5) lib/action_view/template.rb:145:in`block in render'
> activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
> actionview (4.2.5) lib/action_view/template.rb:333:in`instrument'
> actionview (4.2.5) lib/action_view/template.rb:143:in `render'
> actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:339:in`render_partial'
> actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
> actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
> activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
> activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
> activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
> actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
> actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:309:in `render'
> actionview (4.2.5) lib/action_view/renderer/renderer.rb:47:in`render_partial'
> actionview (4.2.5) lib/action_view/helpers/rendering_helper.rb:35:in `render'
> haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in`render_with_haml'
> locomotivecms (3.0.0) app/views/locomotive/layouts/application.html.slim:16:in `__home_evgeniy__rvm_rubies_ruby_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_layouts_application_html_slim___2784365293031336315_70150487672260'
> actionview (4.2.5) lib/action_view/template.rb:145:in`block in render'
> activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
> actionview (4.2.5) lib/action_view/template.rb:333:in`instrument'
> actionview (4.2.5) lib/action_view/template.rb:143:in `render'
> actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:66:in`render_with_layout'
> actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
> actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in`render'
> actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
> actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in`render'
> actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
> actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in`_render_template'
> actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
> actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in`render_to_body'
> actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
> actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in`render'
> actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in`block (2 levels) in render'
> activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
> /home/evgeniy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in`realtime'
> activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in`block in render'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in`render'
> responders (2.1.1) lib/action_controller/responder.rb:236:in `default_render'
> responders (2.1.1) lib/action_controller/responder.rb:170:in`to_html'
> responders (2.1.1) lib/responders/flash_responder.rb:107:in `to_html'
> locomotivecms (3.0.0) lib/locomotive/action_controller/responder.rb:23:in`to_html'
> responders (2.1.1) lib/action_controller/responder.rb:163:in `respond'
> responders (2.1.1) lib/action_controller/responder.rb:156:in`call'
> responders (2.1.1) lib/action_controller/respond_with.rb:205:in `respond_with'
> locomotivecms (3.0.0) app/controllers/locomotive/dashboard_controller.rb:8:in`show'
> actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
> actionpack (4.2.5) lib/abstract_controller/base.rb:198:in`process_action'
> actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
> actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in`block in process_action'
> activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:117:in`call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
> activesupport (4.2.5) lib/active_support/callbacks.rb:505:in`call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:498:in`block (2 levels) in around'
> activesupport (4.2.5) lib/active_support/callbacks.rb:292:in `call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:292:in`block (2 levels) in halting_and_conditional'
> activesupport (4.2.5) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
> locomotivecms (3.0.0) app/controllers/locomotive/concerns/timezone_controller.rb:8:in`set_timezone'
> activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
> activesupport (4.2.5) lib/active_support/callbacks.rb:291:in`call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:291:in `block in halting_and_conditional'
> activesupport (4.2.5) lib/active_support/callbacks.rb:497:in`call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:497:in `block in around'
> activesupport (4.2.5) lib/active_support/callbacks.rb:505:in`call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:92:in`__run_callbacks__'
> activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
> activesupport (4.2.5) lib/active_support/callbacks.rb:81:in`run_callbacks'
> actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
> actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in`process_action'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
> activesupport (4.2.5) lib/active_support/notifications.rb:164:in`block in instrument'
> activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> activesupport (4.2.5) lib/active_support/notifications.rb:164:in`instrument'
> actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
> actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
> actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
> actionview (4.2.5) lib/action_view/rendering.rb:30:in`process'
> actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
> actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
> actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
> actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in`call'
> actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
> actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in`serve'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in`each'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
> actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in`call'
> railties (4.2.5) lib/rails/engine.rb:518:in `call'
> railties (4.2.5) lib/rails/railtie.rb:194:in`public_send'
> railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
> actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in`serve'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in`each'
> actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
> actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in`call'
> locomotivecms (3.0.0) lib/locomotive/middlewares/site.rb:26:in `call'
> dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in`call'
> warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
> warden (1.2.6) lib/warden/manager.rb:34:in`catch'
> warden (1.2.6) lib/warden/manager.rb:34:in `call'
> rack (1.6.4) lib/rack/etag.rb:24:in`call'
> rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
> rack (1.6.4) lib/rack/head.rb:13:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
> actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in`call'
> rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
> rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
> actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
> activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
> activesupport (4.2.5) lib/active_support/callbacks.rb:778:in`_run_call_callbacks'
> activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
> actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
> actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
> web-console (2.3.0) lib/web_console/middleware.rb:28:in`block in call'
> web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
> web-console (2.3.0) lib/web_console/middleware.rb:18:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
> railties (4.2.5) lib/rails/rack/logger.rb:38:in`call_app'
> railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
> activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in`block in tagged'
> activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in`tagged'
> railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
> actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in`call'
> rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
> rack (1.6.4) lib/rack/runtime.rb:18:in`call'
> activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> locomotivecms (3.0.0) lib/locomotive/middlewares/image_thumbnail.rb:23:in`call'
> dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
> rack (1.6.4) lib/rack/lock.rb:17:in`call'
> actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
> rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
> railties (4.2.5) lib/rails/engine.rb:518:in `call'
> railties (4.2.5) lib/rails/application.rb:165:in`call'
> rack (1.6.4) lib/rack/content_length.rb:15:in `call'
> puma (2.16.0) lib/puma/server.rb:557:in`handle_request'
> puma (2.16.0) lib/puma/server.rb:404:in `process_client'
> puma (2.16.0) lib/puma/server.rb:270:in`block in run'
> puma (2.16.0) lib/puma/thread_pool.rb:106:in `call'
> puma (2.16.0) lib/puma/thread_pool.rb:106:in`block in spawn_thread'

**Comment by did** [comment]
@eugenemelnikov would it possible that for some unknown reasons you had a symbol value in your updated_at field?

**Comment by eugenemelnikov** [comment]
@did, checked, in update_at fields Date value only. 

Actually, it was a fresh engine install and empty database.

I've attached a complete dump of my db (it has only few collection that created before it crashed).
[engine_dev.zip](https://github.com/locomotivecms/engine/files/157020/engine_dev.zip)

**Comment by did** [comment]
@eugenemelnikov  MongoDB 2.2.3? Really :-) ? That's a super old version of MongoDB. You could try with MongoDB 3.x? 
thanks for the dump!

**Comment by eugenemelnikov** [comment]
@did, on other machine it fine. As i known, MongoDB 2.6 there. Will try at MongoDB 3 at windows machine soon. 

So this related to old MongoDB version?
