### ISSUE TITLE
Quickly edit uploaded images from wysihtml

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/engine#1129]
Currently, in **v3.0.1** if you have already placed an uploaded image within an editable element, you need to first navigate to the assets page and find the image in question in order to edit it (resize, crop, etc).

It would be very convenient if an `edit` button/link were added to the popup that appears when clicking the image in wysihtml, similar to the experience when first adding an uploaded asset to an editable element.

**Comment by did** [comment]
implemented in the sections (not yet documented)

**Comment by did** [comment]
documentation here: https://doc.locomotivecms.com/v4.0/docs/json-definition#section-setting-types (look for the image picker).

Implementation:
https://github.com/locomotivecms/engine/blob/master/app/javascript/src/locomotive/editor/components/cropper/index.js
https://github.com/locomotivecms/engine/blob/d7817e6f2a5fa54905162c3877cbe32b84b7ab1f/app/javascript/src/locomotive/editor/inputs/image_picker.js#L40

**Comment by cappadona** [comment]
Thanks @did. Looking forward to the `4.0` release 😄

**Comment by did** [comment]
thanks @cappadona! Working hard to fix the last issues, write documentation, test installation procedures!
