### ISSUE TITLE
Prompt for unsaved changes in back-office

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/engine#1130]
Currently, in **v3.0.1**, it's just too easy to mistakenly navigate away and lose all of your work.

#### Example Scenario

1. Open a page in the back-office
1. Add some text in one of the editable elements (**do not click the `save` button**)
1. Click the `Settings` link for the current page
1. Return back to the content editor by clicking the `CONTENT` tab

**Result:** Changes are lost

> Using the browser's back button to return to the content editor might preserve the previous changes made, but this is inconsistent and only potentially helps address the issue if the user realizes the error instead of preventing the situation by notifying the user before data is lost

**Comment by did** [comment]
@cappadona. totally agreed on that. We need to display a confirmation popup if you want to leave the page.

**Comment by did** [comment]
implemented here! https://github.com/locomotivecms/engine/commit/b7a4ef42b06eb8291f43583fdefb52dddf0d58f3.

That's a basic and naive implementation. For instance, if you type a character in an input box and then remove it, that will trigger the confirmation box if you leave that screen.
