### ISSUE TITLE
Difficult to edit link text in wysihtml

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/engine#1131]
There have been [recent improvements](https://github.com/locomotivecms/engine/commit/2d872e9) to this behavior, but in **v3.0.1** there's still at least one use case that's problematic: editing link text without resorting to the html view.

Currently the popover behavior is too aggressive. This makes it very difficult (almost impossible) to alter the link text itself. Consider activating only on user click. If not, then perhaps add a field for the link text in the popover component.

**Comment by did** [comment]
got it, I will see if I can fix that quickly.

**Comment by did** [comment]
@cappadona now, you have to double click to edit the property of your link. I think that's an acceptable behaviour.
