### ISSUE TITLE
Issue with locomotive account scss files compilation in production

### ISSUE THREAD

**Issue by taher435** [locomotivecms/engine#1132]
I have a locomotive engine site which use the locomotivecms 3.0.0 gem. All works good in development but when I host the site with Apache and have the RailsEnv as production I don't get any assets in the browser. Looking at server logs, I found this

```
Sass::SyntaxError: Undefined variable: "$border-radius-base".
/home/taher/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms-3.0.0/app/assets/stylesheets/locomotive/account/_files.scss:26
```

So I think its because of this error my css files are not pre-compiled and not served to the browser.

**Comment by jimcavoli** [comment]
You seem to be on the right path at first glance. What's the workflow for your asset precompiling - on the server, local with upload, using an asset domain w/CDN, etc?

**Comment by taher435** [comment]
its on the server, not using S3 or any other CDN. I am running the locomotive site on Passenger (Apache).

**Comment by did** [comment]
@taher435 we released a new minor version last week: 3.0.1. Could you give it a try please?
Another thing to look at is if you managed to precompile your assets locally:
````
$ bundle exec rake assets:precompile RAILS_ENV=production
````
Let me know if you were able to precompile them locally.

**Comment by taher435** [comment]
I will give a try to the new minor version. 

I tried compiling them locally with production environment but it failed with the same error.

**Comment by did** [comment]
@taher435 I've no idea what's going on here. Did you modify the css files or add new ones or did something different from the default installation?

**Comment by taher435** [comment]
No. After getting this issue I tried to change few things in the gem css files. But later I deleted my entire gemset and did a fresh install. But again I got this issue.

**Comment by did** [comment]
what's in your Gemfile? 

Otherwise, replace the line about Locomotive by this:
````
gem 'custom_fields',        github: 'locomotivecms/custom_fields',  ref: 'b5dcac5'
gem 'locomotivecms',        github: 'locomotivecms/engine',         ref: '74fa0ab'
gem 'locomotivecms_steam',  github: 'locomotivecms/steam',          ref: '9c95e13'
````

then ````bundle update````

(btw, what's your OS?)

**Comment by manuchap** [comment]
Seems like rails is picking up partials alphabetically thus missing variables

**Comment by taher435** [comment]
@did I am running Ubuntu 14.04 LTS on my production server. Will try this update you back.

**Comment by taher435** [comment]
Replacing the locomotive gem line also did not help.

I see this when I run my server, no assets

![image](https://cloud.githubusercontent.com/assets/875186/13981650/4bb4c3b6-f120-11e5-8122-cca345efc6d5.png)

**Comment by taher435** [comment]
Ok so after replacing the line  gem locomotivecms with the ones you gave above, I was able to successfully do this

`RAILS_ENV rake assets:precompile`

But without doing that my app does not work.

**Comment by did** [comment]
@taher435 glad to see you made it!

For better performance (you don't want your production server to use its precious CPU time to precompile assets), it's better to precompile them locally first before deploying your application to production. If you use Capistrano, there is a task doing that. On Heroku: [https://devcenter.heroku.com/articles/rails-asset-pipeline](https://devcenter.heroku.com/articles/rails-asset-pipeline).

**Comment by taher435** [comment]
How is this issue closed? Isn't what I did is just a workaround?

**Comment by did** [comment]
@taher435, upgrading your gems solves your initial issue, right? (unless I missed a point). 

One more thing, I forgot to tell you this. If you want your Rails app to precompile assets in production, change your config/environments/production.rb settings. That should avoid you to precompile them "manually" before deploying your app (I don't recommend it though).

````ruby
  # Do not fallback to assets pipeline if a precompiled asset is missed.
  config.assets.compile = true # by default: false
````

**Comment by taher435** [comment]
@did, Upgrading the gem did not help. Manually setting the order as you suggested worked.

I tried adding the asset compile but that did not work for some reason.

Let me see if I can do some debugging. If I do find a fix for this will submit a pull request.

**Comment by ishwinder** [comment]
Facing the similar issue with 3.2.0. Any break throughs in this one ? As @taher435 has pointed out, it seems like alphabetic complication of scss is causing undefined variables.
