### ISSUE TITLE
Localization of site seo fields

### ISSUE THREAD

**Issue by timsly** [locomotivecms/engine#1134]
Right now it's not possible to set different translation for site seo fields.
Is it on purpose?
If no i can help with implementation

**Comment by nielsenramon** [comment]
@timsly It is possible. 

You can use site wide SEO translations like this: https://locomotive-v3.readme.io/docs/localization#site-wide-seo-parameters.

And for page specific SEO translations you can use this: https://locomotive-v3.readme.io/docs/localization#page-seo-parameters

Does this resolve your issue?

**Comment by timsly** [comment]
@nielsenramon this is instruction for wagon. But how can i change site seo in the back-office?

**Comment by nielsenramon** [comment]
@timsly You can edit the SEO translations for each page when you click on settings link in the page:

![screen shot 2016-02-29 at 13 55 31](https://cloud.githubusercontent.com/assets/1246672/13394986/18b7136a-deec-11e5-960a-2a99c6188e95.png)

Then for each language you can switch the language picker in the right top and change your title + description in the SEO tab.

**Comment by timsly** [comment]
I know how to do it for page. But how i can set, say, fr site seo description?
On site seo page(`current_site/edit`, seo tab) there is no option to define locale.

**Comment by nielsenramon** [comment]
@timsly Good question, at the moment this is only possible in wagon. 

@did something for the backlog I guess?

**Comment by did** [comment]
sorry @timsly, that was missing. It'll be included in our next release (3.1.0).
