### ISSUE TITLE
mongoid dependency conflict (Edge)

### ISSUE THREAD

**Issue by jeppeliisberg** [locomotivecms/engine#1136]
Hi, I'm trying to run the engine on edge, but when I `bundle update` I get the following:

```
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    locomotivecms (>= 0) ruby depends on
      mongoid (~> 5.1.1) ruby

    locomotivecms (>= 0) ruby depends on
      custom_fields (~> 2.6.0) ruby depends on
        mongoid (~> 5.0.2) ruby
```

It looks like the problem was introduced in https://github.com/locomotivecms/engine/commit/b1690a4ac3ebcb4570a94efaa8af3abf526bbf03 and that even though custom_fields has been updated in that commit, I cannot make this dependency conflict go away. I also tried deleting my Gemfile.lock entirely and starting over with `bundle install`

**Comment by did** [comment]
@jeppeliisberg before the release of the next version, you could fix that problem by defining a specific version of the custom_fields gems in the Gemfile of your Rails app:

````
gem 'custom_fields', github: 'locomotivecms/custom_fields', ref: 'b5dcac5'
````

That should fix your issue.
