### ISSUE TITLE
Slug should map slashes

### ISSUE THREAD

**Issue by aeberlin** [locomotivecms/engine#1137]
@did 

If I map a slug as `foo/bar`, I would expect `localhost/foo/bar` to be mapped, and not as `localhost/foo-bar`. This is high priority for us, I'll contribute time to make it happen.

Sorry for the direct mention, this is very time sensitive for us.

Thanks, cheers.

**Comment by did** [comment]
hi @aeberlin, why not creating a first page with the foo slug and the bar one which will under foo?

**Comment by aeberlin** [comment]
Let me try it without our custom middleware today. If this isn't a known issue currently, it might be something on our end. We used our `home` as a parent, then created a page in the web interface extending from it, but it would just map as `foo-bar`, instead of `home/foo-bar`.

I will update you in a few hours, but thanks for the quick response and confirmation that this should just work out of the box!

**Comment by did** [comment]
Right now, in order to create "foo/bar", you'll have to create 2 pages in the back-office. 
However, if you really want to create them automatically when you enter "foo/bar" as the slug of your new page, I'd see it as a new feature.

**Comment by aeberlin** [comment]
Ahhh, I understand.

Okay, I'm thinking that we need our authors to have this capacity. Could you give me a quick few pointers on where to isolate this routing mechanism and it's interaction with the slug configuration?

I'll be happy to do the rest of the legwork.

Thank you so much! Cheers.

**Comment by aeberlin** [comment]
I have a feeling it may result in a breaking change to the mapping of slugs for `{% extends 'foo' %}` declarations. Would mapping based on file name or some other method be a better approach?

**Comment by did** [comment]
not necessarily. The way I see it is that the Engine is going to create itself the missing pages if you specify "<slug 1>/<slug 2>.../<slugN>"

**Comment by did** [comment]
https://doc.locomotivecms.com/v4.0/docs/custom-routes could solve the problem.
