### ISSUE TITLE
Huge memory requirements on Heroku

### ISSUE THREAD

**Issue by schovi** [locomotivecms/engine#1139]
Hi,

we are using locomotive on heroku with one click installer. We setup simple dyno with 512mb ram, which should be enought for simple cms web. Unfortunately it is not. It really fast run out of memory and starts to swap, which lead to longer responses and automatical restart of dyno. I am currently experiment with larger Dyno with 1024MB ram, but the price 50$ for that is not acceptable for such a small project. 
I would like to help with this problem, but I am not sure, where to start and what can cause such huge memory consumption.

<img width="1111" alt="locomotive-heroku memory" src="https://cloud.githubusercontent.com/assets/11453/14377784/e652e81e-fd71-11e5-914c-73e8673a60ae.png">

**Comment by did** [comment]
hi @schovi! Can you tell me which version of Locomotive (or commit) you're using? I remember that I fixed a couple months ago an issue in Steam which was opening too many connections to MongoDB causing the app to consume a lot of memory.
Anyway, I can help you on that.

**Comment by schovi** [comment]
@did: 
From Gemfile `gem 'locomotivecms', github: 'locomotivecms/engine', ref: '091acc0'`
I tried to get heroku repo and upgrade to some newest version, but all my attempts failed on incompatible rails/activesupport/etc. versions :/

**Comment by luisgutierrezkoombea** [comment]
Hi @did I have a site on an old locomotive version 2.0.0rcx , unfortunally about a few weeks ago , it stared to have memory issues on Heroku, I decided to upgrade to the latest version, but right now I am not sure how can I import my data to the new mongodb schema? . Any help will be appreciate it.

**Comment by did** [comment]
@schovi This should work (````bundle update```` if conflicts)

````
gem 'locomotivecms', github: 'locomotivecms/engine', ref: '34e6188'
````

Otherwise, generally speaking, 512Mb has always been not enough for a Rails application. One work-around would be to use Passenger as the web server since it knows how to deal with memory leak in RoR apps (it just restarts the processes). 

Anyway, we can track down the memory leak although it'll be a hard work. Some links: https://blog.codeship.com/debugging-a-memory-leak-on-heroku/
Embedding https://www.skylight.io in your app could be helpful as well (read their blog post about memory: http://blog.skylight.io/announcing-memory-traces/).

**Comment by schovi** [comment]
@did After download heroku git repository (which was deployed by one click installer, change gem ref to `34e6188` and run `bundle update` result is following:
```
Fetching git://github.com/locomotivecms/engine.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.2.5)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      rails (~> 4.2.5.1)
```

I tried to remove fixed `rails 4.2.5` and then it fail with

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    locomotivecms was resolved to 3.1.0.rc3, which depends on
      carrierwave-mongoid (~> 0.8.1) was resolved to 0.8.1, which depends on
        carrierwave (< 0.11.0, >= 0.8.0) was resolved to 0.10.0, which depends on
          activesupport (>= 3.2.0)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      custom_fields (~> 2.7.0.rc1) was resolved to 2.7.0.rc1, which depends on
        activesupport (~> 4.2.5)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      grape-entity (= 0.4.5) was resolved to 0.4.5, which depends on
        activesupport

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      grape-entity (= 0.4.5) was resolved to 0.4.5, which depends on
        activesupport

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      locomotivecms_steam (~> 1.1.0.rc3) was resolved to 1.1.0.rc3, which depends on
        locomotivecms_common (~> 0.1.0) was resolved to 0.1.0, which depends on
          activesupport (~> 4.2.5.2)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      pundit (~> 1.1.0) was resolved to 1.1.0, which depends on
        activesupport (>= 3.0.0)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      pundit (~> 1.1.0) was resolved to 1.1.0, which depends on
        activesupport (>= 3.0.0)

    locomotivecms was resolved to 3.1.0.rc3, which depends on
      jquery-rails (~> 4.1.0) was resolved to 4.1.1, which depends on
        railties (>= 4.2.0) was resolved to 4.2.6, which depends on
          activesupport (= 4.2.6)
```

**Comment by did** [comment]
@schovi, in your Gemfile, replace 
````
gem 'rails', '4.2.5'
```
by
````
gem 'rails', '~> 4.2.5'
````

**Comment by schovi** [comment]
@did versions works fine now, but there is bug with styling of header and menu in administration.

<img width="469" alt="locomotive" src="https://cloud.githubusercontent.com/assets/11453/14702111/006adefa-07a9-11e6-84b0-aa4b8a8c1316.png">

I tried latest commit, which include some "fix sidebar link overflow issue" https://github.com/locomotivecms/engine/commit/332a2d0a58e02c5b8ec9163df91145d1b89a51dc but result is same.

**Comment by did** [comment]
@schovi that's normal, you need to precompile the assets locally before deploying your app to Heroku.

**Comment by schovi** [comment]
@did I see. There is some "dummy" ruby buildpack. Can I use another buildpack like https://github.com/heroku/heroku-buildpack-multi.git which we use on other rails apps?

**Comment by did** [comment]
I don't know :-) Otherwise, `RAILS_ENV=production bundle exec rake assets:precompile` works great too :-)

**Comment by schovi** [comment]
@did It is not straighforward. Running this command on local requires lot of configuration which is solved on Heroku with env variables. For me that means I have to add dotenv-rails gem as easier solution

**Comment by did** [comment]
hmmm, I did it last time and it worked for me...let me see if I can update them again.

**Comment by schovi** [comment]
@did It failed on `Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']`

**Comment by did** [comment]
@schovi, the solution was to run: ````bundle exec rake assets:precompile```` :-)

**Comment by schovi** [comment]
@did: That works fine. I figured out how to enable heroku to compile assets for you. Just remove /public/assets folder from repository and deploy that. Heroku detect, that you dont handle assets by yourself and do it for you.

**Comment by schovi** [comment]
@did It seems, that upgrade (to latest yesterday master) helped with memory. So thanks for this.

But we found one bug there when deploying new site from scratch. I guess it is this error:
https://stackoverflow.com/questions/20938169/multijsonloaderror-795-unexpected-token-when-trying-to-parse-incoming-body-r

```
11:27 $ wagon deploy production -v

Pushing Site
  persisting alka.cz [failed]
    795: unexpected token at ''
795: unexpected token at ''
	/Users/schovi/.rvm/gems/ruby-2.3.0@vydryonline/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/Users/schovi/.rvm/gems/ruby-2.3.0@vydryonline/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/Users/schovi/.rvm/gems/ruby-2.3.0@vydryonline/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/current_site.rb:13:in `update'
```

I fixed that with reverting to old version, deploy and upgrade again :)

**Comment by did** [comment]
@schovi Glad to hear that! Concerning your issue, upgrade to Wagon 2.1.0 and you should be good :-)

**Comment by schovi** [comment]
@did: Like a charm :)

**Comment by DonKoko** [comment]
@schovi in the end, did you manage to solve the issue? I think we are having the same problem.

**Comment by schovi** [comment]
@DonKoko Playing around with versions of locomotive helped. Nothing more to say

**Comment by DonKoko** [comment]
@schovi so what was the conclusion? Ruby version, engine version?
