### ISSUE TITLE
Missing fr translations break forms in account / site creation

### ISSUE THREAD

**Issue by skflowne** [locomotivecms/engine#1140]
I just made my first install of Locomotive 3.0 on my local machine and I noticed there are a lot of missing french translations. While I don't really care about the translations, the fact that they are missing actually breaks the html output of some forms.

So what I did was copy all english translations files into the french ones and just changed the "en" at the top in "fr".

Things are working now. 
So maybe leave the "en" translations in the "fr" files until they are translated to avoid missing translations errors ?

**Comment by did** [comment]
@skflowne you also can remove the fr locale from the list of available locales for the back-office as shown here: https://github.com/locomotivecms/engine/blob/master/spec/dummy/config/initializers/locomotive.rb#L15.
