### ISSUE TITLE
Missing thumbnail for content_assets in Back Office

### ISSUE THREAD

**Issue by mouligno** [locomotivecms/engine#1141]
I guess the `alternative_vignette_url` has some issue in `engine/app/views/locomotive/content_assets/_list.html.slim` as it doesn't take the `vignette_url` by default.

Anyone got the same issue ?

**Comment by did** [comment]
@mouligno, what's your issue exactly? Btw, vignette_url is only used in the API (don't remember what for).

**Comment by mouligno** [comment]
@did Actually, `alternative_vignette_url` doesn't display any images... When I work locally and change it to `vignette_url` in `_lists.html`, I got my thumbnails but I'm not sure how it is used with other types of content_assets : images, pdf, rich media... 

I just need to see the thumbnail in the list actually :)

**Comment by did** [comment]
@mouligno. Works well for me: http://cl.ly/0l0q220C1Z0k (3.1.0.rc5). Does it happen with any file?

**Comment by mouligno** [comment]
@did Yes, I got it on all the files ;-) Is there a size limit ? 

btw I'm on 3.0.0

**Comment by did** [comment]
@mouligno what do your server/application logs say? Are u sure ImageMagick is installed and correctly set up? Otherwise, try to install 3.1.0 but I doubt that will fix your issue.
