### ISSUE TITLE
public_submission_accounts is empty while send_notifications method is called

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1142]
1. I use engine 3.1.0 on production.

1. My content_type has turned on `public_submission_enabled` option:

  ```
  public_submission_enabled: true
  public_submission_accounts: ['my-name1@koala.pl', 'my-name-2@koala.pl']
  ```
1. I use a form that adds new entry on form submission.

1. I expect to get email notification on submission.
Unfortunately I do not get any message.

1. I've edited file `locomotive-3.1.0/app/services/locomotive/content_entry_service.rb` and added some logs like that:
```
   def send_notifications(entry)
      return unless self.content_type.public_submission_enabled?

      account_ids = (self.content_type.public_submission_accounts || []).map(&:to_s)
 puts "  account_ids: #{account_ids}"

      self.content_type.site.accounts.each do |account|
        next unless account_ids.include?(account._id.to_s)

        Locomotive::Notifications.new_content_entry(account, entry).deliver
      end
    end
```

Unfortunately `account_ids` is empty.

`self.content_type.site.accounts` also empty.

Any advice?

**Comment by adam-pl** [comment]
I've found that in the backoffice I have to add emails in "models / my_content_type / notification settings" first.

I need to check it again.

**Comment by did** [comment]
hey @adam-pl, I'm not sure the public_submission_accounts site property in Wagon can be pushed (it certainly is for the first deployment).
