### ISSUE TITLE
Editing link popover not partially hidden

### ISSUE THREAD

**Issue by CD1212** [locomotivecms/engine#1143]
When editing a link, the popover is partially concealed outside of the editable region block. Maybe it's just a `z-index` issue.

![locomotive_ _chris_dyer](https://cloud.githubusercontent.com/assets/353185/15040327/c0e99768-12ab-11e6-981f-3f2f48561f1d.png)

**Comment by did** [comment]
hey @CD1212, that's bug. I thought I had fixed it. It looks like I hadn't :-(

**Comment by did** [comment]
hey @CD1212, which version of Engine are u using? (I wasn't able to reproduce your bug).

**Comment by CD1212** [comment]
Hi @did, I think I'm on 3.1.1. I have just attached another screenshot, because it looks as though removing `overflow: auto` on `.scrollable` sorts this. Is there anything I can do to help diagnose / debug?

![developer_tools_-_http___chrisdyer_cdengine_co_uk_manage_chrisdyer_pages_54b4445d09345be2f0000004_editable_elements_and_locomotive_ _chris_dyer](https://cloud.githubusercontent.com/assets/353185/15724045/44f631a0-283d-11e6-9b0e-ed75f56abd27.png)

**Comment by did** [comment]
you're right @CD1212, it happens when your first editable element is a text one. 
I've got no solution for now because ````overflow: scrollable```` can't be removed.
@nielsenramon, we need to refactor (UI + CSS code) this screen :-(

**Comment by nielsenramon** [comment]
@did @CD1212 I fixed it with a temp fix. Please test it again with latest commit on master. I made all popovers show up inside the WYSIWYG editor.

<img width="248" alt="screen shot 2016-06-02 at 10 47 30" src="https://cloud.githubusercontent.com/assets/1246672/15739252/6faed9ca-28af-11e6-9dd5-3dab431f9dab.png">

**Comment by did** [comment]
works for me! thanks @nielsenramon!
