### ISSUE TITLE
Running CMS on production server fails assets

### ISSUE THREAD

**Issue by rubytastic** [locomotivecms/engine#1145]
Running locomotive like:

bundle exec rails server -b 0.0.0.0
To have it available at mycompany.com:3000 fails the assets would not load.

**Comment by did** [comment]
hey @rubytastic, Locomotive engine is a Rails engine which is embedded into a standard Ruby on Rails application. In production and by default, Ruby on Rails doesn't precompile assets which means that you have to precompile them first before deploying to your server (Heroku does that for you when you push your code): http://guides.rubyonrails.org/asset_pipeline.html#in-production
