### ISSUE TITLE
Layouts showing in sitemap.xml...

### ISSUE THREAD

**Issue by interhive** [locomotivecms/engine#1148]
I'm seeing my layouts show up in the generated sitemap.xml. I added the following header code to my layouts to try to remedy the issue:

```yaml
---
is_layout: true
listed: false
---
```

This does work when serving locally but, when pushing the layouts to the server, it does not produce the same results -- the layouts are still listed in the sitemap.xml.

Is this a bug or do I need to do something differently to make sure the header variables are pushed during deployment?

**Comment by did** [comment]
@interhive fixed in Steam. thanks!
