### ISSUE TITLE
Editing images and cross origin request problem

### ISSUE THREAD

**Issue by schovi** [locomotivecms/engine#1152]
When editing image and try to resize it I get javascript error 

```
locomotive-616693e….js:680 Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```

It is because image is from different domain and there is some problem with headers.

I tried to debug it and found something. When "editing" image, it download image itself 3 times. Unfortunately each request is different.

There is screenshot from chrome network:
<img width="739" alt="open edit" src="https://cloud.githubusercontent.com/assets/11453/15431922/49816d9c-1eac-11e6-9b1a-c60ff48b0650.png">

Diffs are only in headers.  Only second request has `Origin:https://engine-domain` header and as expected only get response headers.

1)

```
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,cs;q=0.6
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:our-bucket.s3.eu-central-1.amazonaws.com
Pragma:no-cache
Referer:https://engine-domain/locomotive/vydryonlinecz/content_assets?utf8=%E2%9C%93&query=vydra
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.54 Safari/537.36
```

2)

```
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,cs;q=0.6
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:our-bucket.s3.eu-central-1.amazonaws.com
Origin:https://engine-domain
Pragma:no-cache
Referer:https://engine-domain/locomotive/vydryonlinecz/content_assets?utf8=%E2%9C%93&query=vydra
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.54 Safari/537.36
```

3)

```
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,cs;q=0.6
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:our-bucket.s3.eu-central-1.amazonaws.com
Pragma:no-cache
Referer:https://engine-domain/locomotive/vydryonlinecz/content_assets?utf8=%E2%9C%93&query=vydra
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.54 Safari/537.36
```

And response for second request has these headers

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:https://engine-domain.herokuapp.com
```

My guessing is, that in html canvas is used image without `Access-Control-Allow` headers and thats reason, why you cant access canvas image data.

PS:
We already solved CORS (images does not download at all) errors with rules directly on Amazon. There is missing documentation about it in locomotive.

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>https://engine-domain</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>engine-domain</AllowedOrigin>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>engine-domain</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>engine-domain</AllowedOrigin>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>engine-domain</AllowedOrigin>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://public-domain</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>https://public-domain</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by did** [comment]
thanks @schovi! I'll try to add it to the installation guide ASAP.

**Comment by schovi** [comment]
@did And what about that error with editing? Are CORS wrong or is there bug inside locomotive?

**Comment by did** [comment]
hmm, I've a got a version of v3 running on Heroku with AWS S3 for storing/serving the images. 
I'm totally able to resize images without any trouble. 
But, I indeed modified my CORS configuration like this:

````
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
````

**Comment by schovi** [comment]
@did: I tried to simplify like in you example and still same error. I still think problem is with multiple image downloading, where one  request is without `Origin` header. What specific version do you use?

**Comment by stunjiturner** [comment]
The documentation for the CORS configuration for LocomotiveCMS 3, is it available somewhere?

**Comment by did** [comment]
@stunjiturner unfortunately, we don't a guide for that in the documentation site. I need to spend some time on it. 
For instance, only in development, I use the rack-cors gem for my local version of our hosting platform. Here is the code for the **config/application.rb** file. 
```
# in development, allow requests to assets from anywhere
    if Rails.env.development?
      config.middleware.insert_before ActionDispatch::Static, 'Rack::Cors', debug: true, logger: (-> { Rails.logger }) do
        allow do
          origins '*'
          resource '/sites/*', headers: :any, methods: :any
        end
      end
    end
```

I need to figure out how useful it could be for other developers.

**Comment by robinlambert** [comment]
Same problem here. We have the `SecurityError: Failed to execute 'toDataURL'...` when trying to resize an image.
It can be fixed by adding the attribute `crossOrigin="Anonymous"` to the edited image tag in the backoffice.
http://stackoverflow.com/questions/20027839/todataurl-throw-uncaught-security-exception/27260503#27260503
But I can't find in the source code where to add that tag.
