### ISSUE TITLE
Wysiwyg clear content of iframe

### ISSUE THREAD

**Issue by schovi** [locomotivecms/engine#1153]
Hi,
We are trying to add youtube videos into our content. Unfortunately wysiwyg does not like it :)
There is recorded video https://v.usetapes.com/tOAVQgrscO

Happy scenario:
1) switch to code view.
2) paste iframe code from youtube
3) save page
Until now everything is fine and video works

But it goes wrong, when wysiwyg loading content from source code in these 2 cases.
**First case:**
1) switch to code view.
2) paste iframe code from youtube
3) switch off code view.
4) content of iframe is cleared

** Second case:**
1) open editor for page, where is working video
2) content of iframe is cleared immediately on load.

**Comment by did** [comment]
thanks @schovi for the bug report!

**Comment by schovi** [comment]
👍
