### ISSUE TITLE
Syncing does not work for the published flag.

### ISSUE THREAD

**Issue by eilers** [locomotivecms/engine#1156]
Using Version 3.1.1
I don't get a change of the published flag after syncing with "wagon sync .."

**Comment by robinlambert** [comment]
The title of the localized pages doesn't sync neither

**Comment by did** [comment]
only the contents of the editable elements are replaced by the sync command. 
Not sure if you should also sync the published attribute. However, syncing the page title might be a good idea.

**Comment by did** [comment]
we implemented a way of pulling content from a remote engine to a local Wagon (sync). Documentation is coming soon.
