### ISSUE TITLE
Site Model dead method

### ISSUE THREAD

**Issue by cavpollo** [locomotivecms/engine#1159]
Don't ask me why, but for my locomotive v2 site I was using the method Locomotive::Site.fetch_page

Now that I migrated to v3 the method seems to still be there:
https://github.com/locomotivecms/engine/blob/master/app/models/locomotive/site.rb#L57

BUT the models/locomotive/extensions/page/render.rb is gone from the project, and that makes that method fail when called.

I was thinking of using something along the lines of 'current_site.pages.where(fullpath: path).first' and do some verifications myself, now that the method is gone...

So I'm looking for anybody who can offer an existing alternative to that old method, and asking very nicely for the method to be removed to not mislead anybody into thinking it is still available =)

**Comment by did** [comment]
thanks @cavpollo! 

To answer your initial concern, it depends on where you want to use your fetched page. 
In the back-office? Then use `'current_site.pages.where(fullpath: path).first` (although I would rely on the handle property instead)
If that's for Steam, I would use the page repository (check the Steam source / specs).
Hope it helps.
