### ISSUE TITLE
Creating categories with many-to-many

### ISSUE THREAD

**Issue by samandera** [locomotivecms/engine#1160]
Hello,
I have a problem with displaying cetegories for posts. I'm developing the site with wagon and with mocked data in yml, without using engine, so I'd also be grateful if anyone show me when the lack of engine and database is the cause of the problems.
I've created content type post for which I need categories. Categories may have many posts and posts may have many categories, so in yml type for both is many-to-many. However displaying categories on post page doesn't work. I tried to display them with: {% for category in contents.posts.last.categories %}<span>{{ category }}</span> {% endfor %} and with {% for category in post.categories %}<span>{{ category }}</span> {% endfor %} . 

That second statement works perfect for displaying tags (type:tags). 

That's how looks field categories in posts.yml:
- categories:
    label: Categories
    type: many_to_many
    class_name: categories
    inverse_of: posts
    ui_enabled: true

And that's how looks field posts in categories.yml:
- posts:
    label: Posts
    type: many_to_many
    class_name: posts
    inverse_of: categories

When in my content type template I type {{ post | json }} there's displayed interesting thing: "category_ids":["Sample","Test"]. The array contains categories created for that post. Exchanging 'categories' in the loops above for 'category_ids' also doesn't work. Any ideas how to resolve this?

**Comment by did** [comment]
hi @samandera, assuming that:
- your categories content type has a name field 
- you've got a templatized page for your posts content type

the following code should work:

```liquid
<h1>{{ post.title }}</h1>
<ul>
    {% for category in post.categories %}
       <li>{{ category.name }}</li>
    {% endfor %}
</ul>
```

Well, at least, it works on my machine :-)
