### ISSUE TITLE
New language to site do not link to content entries

### ISSUE THREAD

**Issue by illescasjd** [locomotivecms/engine#1167]
# The problem

My teammate and I added a new language to our lcms v3 website. We couldn't generate valid links in both languages to the existent content entries, so I tried the steps 5 and 6 of the list to check if at least the URL was available. It wasn't.
# Steps to reproduce:
1. Get a lcms v1 website with only one language (lang A)
2. Generate content types & content entries for that type
3. Migrate your lcms v1 website to lcms v3 (haha, I'd love to see you succed in this step)
4. In the back office of the migrated site, add a new language (lang B).
5. Now try to access one entry in the original language:  
   http://site.com/A/contentType/contentEntrySlug  **(this should work)**
6. Now try to access the same entry with the second language:
   http://site.com/B/contentType/contentEntrySlug **this gets a 404**
# Solution:

Manually add the slug in the new language to the content_entry:

Original property
`"_slug" : {"A" : "contentEntrySlug" }`

Modified property
`"_slug" : { "A" : "contentEntrySlug" , "B" : "contentEntrySlug" }`

Command

```
db.locomotive_content_entries.update( 
{ "_id" : ObjectId("000000000000000000000000") }, 
{ $set : 
    { "_slug" : { "A" : "contentEntrySlug" , "B" : "contentEntrySlug" } 
} )
```

We have around 8,000 entries of 15 different types.

Do you have any idea to solve this? We thought we could build a console application to iterate the collections and complete the info.

**Comment by did** [comment]
hi @illescasjd! Migrating from v1! really?! :-) 

First, I recommend adding your migration task here: https://github.com/locomotivecms/engine/blob/master/lib/tasks/locomotive.rake#L30. 

Then, iterating over 8k entries can't be done in one single ruby loop with mongoid. Instead, you've to split by "packets". That's why we patched Mongoid by adding the **each_by** method. So, something like this would help you to process all your content entries:

```ruby
Locomotive::ContentEntry.all.each_by(100) do |entry|
   # apply your modifications here
end
```

Hope it helps!

**Comment by illescasjd** [comment]
Hi @did, 

I don't think this will solve the problem,  because the bug was caused in v3.

1. **In the back office of the V3 site**, add a new language (lang B).
2. Now try to access one entry in the original language:
    http://site.com/A/contentType/contentEntrySlug (this should work)
3. Now try to access the same entry with the second language:     http://site.com/B/contentType/contentEntrySlug this gets a 404

**So, this bug only appears to me because my site was migrated?**

About the content_entries, I did it with this [gist](https://gist.github.com/illescasjd/81bcd6e361eb4234e54e7e923096716f). I know, it's c#.

**Comment by did** [comment]
@illescasjd I get it. Content entries or other content resources are not duplicated in the new language that you've just added. Developers usually know from the beginning which locales they're going to have in their sites. 
Btw, nice script ;-)
