### ISSUE TITLE
Resized images are not loaded from the CDN (asset_host)

### ISSUE THREAD

**Issue by MatthieuBarthel** [locomotivecms/engine#1168]
Hi, 

Using the Engine v3.1.1 and Wagon v2.1.1 (so awesome by the way 👍), it looks like that once an image is generated by steam (resize filter), it won't be loaded from the CDN (config.asset_host in carrierwave.rb).

By example :
```<img src="{{ 'logo.png' | theme_image_url | resize: '320x240#' }}" alt="Company logo" />```

**Comment by did** [comment]
hi @MatthieuBarthel, thanks!
You're right about the CDN. That's why you need to update your Dragonfly settings (config/initializers/dragonfly.rb).
Check out the documentation here: http://markevans.github.io/dragonfly/cache/ and more specifically the "Using a CDN" chapter :-)

**Comment by MatthieuBarthel** [comment]
Hi @did,
Thanks a lot for your help, I tried to update my Dragonfly settings but it doesn't work, my images are still loaded directly from the server.
Here is my __config/initiliazers/dragonfly.rb__ file :
```
# Configure
Dragonfly.app(:engine).configure do
  plugin :imagemagick,
    convert_command:  `which convert`.strip.presence || '/usr/local/bin/convert',
    identify_command: `which identify`.strip.presence || '/usr/local/bin/identify'

  verify_urls true

  secret 'xyz'

  url_format '/images/dynamic/:job/:sha/:basename.:ext'

  url_host 'https://xyz123.cloudfront.net'

  fetch_file_whitelist /public/

  fetch_url_whitelist /.+/
end

# Logger
Dragonfly.logger = Rails.logger

# Mount as middleware
Rails.application.middleware.use Dragonfly::Middleware, :engine

```
Do you see anything wrong ? 
Thank you and have a nice day.

**Comment by did** [comment]
@MatthieuBarthel looks good to me. Did you enable page caching? (if so, just make a minor update on your page).

**Comment by MatthieuBarthel** [comment]
I disabled caching and uploaded a new picture, it doesn't change.
I also checked that the update has been correctly deployed (just to be sure), it is the case (unicorn stopped/started also to be sure).
I checked Gemfile.lock, I am using Dragonfly 1.0.12.
Thanks a lot

**Comment by did** [comment]
so ```<img src="{{ 'logo.png' | theme_image_url | resize: '320x240#' }}" alt="Company logo" />``` doesn't work?!
If not, what's the output of ```<img src="{{ 'logo.png' | theme_image_url }}/>```?

**Comment by MatthieuBarthel** [comment]
Yes exactly, without the resize filter I get the cloudfront url : 
https://d32a2a5ruz34pw.cloudfront.net/sites/57a1f44d96803b5aedc55d22/theme/images/logo.jpg?1470832519

And once I add the resize filter, I get this :
http://boilerplate.imatt.ch/steam/dynamic/W1siZnUiLCJodHRwczovL2QzMmEyYTVydXozNHB3LmNsb3VkZnJvbnQubmV0L3NpdGVzLzU3YTFmNDRkOTY4MDNiNWFlZGM1NWQyMi90aGVtZS9pbWFnZXMvbG9nby5qcGc%2FMTQ3MDgzMjQyMiJdLFsicCIsInRodW1iIiwiMTQweDE0MCMiXV0/91f9d000c30d5c01/logo.jpg

**Comment by did** [comment]
alright, I got it! thanks @MatthieuBarthel!

Add this in your **config/initializers/dragonfly.rb** file:

```ruby
Dragonfly.app(:steam).configure do
  url_host 'https://xyz123.cloudfront.net'
end
```

**Comment by MatthieuBarthel** [comment]
Awesome, it works. Thank you so much for everything @did  👍 ❤️

**Comment by did** [comment]
you're very welcome :-)

**Comment by interhive** [comment]
I've made the suggested change to my `dragonfly.rb` file and I'm still having the same issue that was brought up here. I'm only having it for images in the backend though... all frontend images are being pulled and shown correctly.

Prior to making the suggested change, my backend URLs looked like:

```shell
https://www.appserver.com/images/dynamic/W1siZnUiLCJodHRwczovL21lZGlhLnFpbmR1c3RyaWFsc2VydmljZXMuY29tLy91cGxvYWRlZF9hc3NldHMvNTcxYTdmZDNmZWY1ZWY0YzBjNzA3NzFkL2NvYnJhYnl0ZV9tYW5nYXRhcl80MDB4NDAwLmpwZyJdLFsicCIsInRodW1iIiwiNzB4NzAjIl1d/2cbb5f4929048dbc/image.jpg
```

After adding the `url_host` method to the `Dragonfly.app(:steam).configure` block, I now have URLs that look like this:

```shell
https://www.cdn.com/images/dynamic/W1siZnUiLCJodHRwczovL21lZGlhLnFpbmR1c3RyaWFsc2VydmljZXMuY29tLy91cGxvYWRlZF9hc3NldHMvNTcxYTdmZDNmZWY1ZWY0YzBjNzA3NzFkL2NvYnJhYnl0ZV9tYW5nYXRhcl80MDB4NDAwLmpwZyJdLFsicCIsInRodW1iIiwiNzB4NzAjIl1d/2cbb5f4929048dbc/image.jpg
```

Of course, those folders do not exist on AWS. Instead, I have an 'uploaded_assets' folder that contains additional folders holding individual asset files.

Am I missing something? Thanks for the help!
