### ISSUE TITLE
Metafields images don't seem to work with config.asset_host

### ISSUE THREAD

**Issue by matthew342** [locomotivecms/engine#1169]
Site metafields of type image seem to generate improper URLs when you have set up an external asset host url in your carrierwave initializer.
I have this in my carrierwave config:
`config.asset_host = 'assets.example.com`
when I upload an image to a metafield, then reference that image in a template like this:
`{{ site.metafields.theme.logo }}`
I get:
`https://www.example.comassets.example.com/sites/<id>/assets/<id>/logo.svg`

Is anyone else having this problem or do I have something misconfigured?

**Comment by matthew342** [comment]
Forgot to add - am running 3.1.1 on Ruby 2.3.1 with carrierwave-aws v1.0.1.

Possibly related to #1168 ?

**Comment by did** [comment]
hey @matthew342, I wasn't able to reproduce that bug on the very last Engine/Steam commits. So, I'm closing it.

**Comment by matthew342** [comment]
Great, thanks @did. Will try out the latest.
