### ISSUE TITLE
[WYSIWYG editor] - links rel nofollow + improvements suggestions

### ISSUE THREAD

**Issue by gillesbertaux** [locomotivecms/engine#1171]
Hi,

**1. Links in nofollow**
Locomotive adds rel=nofollow in my blog content on all the links by default. Removing the nofollow here https://github.com/locomotivecms/engine/blob/master/app/assets/javascripts/locomotive/views/inputs/rte/link_view.js.coffee#L56 should fix it.

_my suggestion:_
- quick fix = no nofollow by default => add using the html editor
- best fix = add rel option in dropdown for the link

**2. Multiple a tag on edit links**
Editing an hyperlink (e.g changing the target) while clicking on one word of a hyperlinked sentence will create another a tag with the same link. This could be interpreted as link stuffing by Google. 

Suggestion: when editing a link edit check if the word is already within an a tag and change only the attributes of that a tag. 

**3. No alt attribute editing***
The editor does not allow me to add a custom alt attribute for an image.

**3. Other suggestions to improve the editor:**
- replace default `<b></b>` by `<strong></strong>` for SEO
- remove the target="_self" option and put by default target="_blank" 

Let me know what you think :)

**Comment by did** [comment]
thanks for opening it! Btw, I wasn't able to reproduce issue #2 (tested it on Chrome).
