### ISSUE TITLE
editable_file always returns nil within editable_elements when accessed via page.children

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/engine#1172]
Running latest release candidates:
- Engine `3.2.0.rc1`
- Wagon `2.2.0.rc1`
- Steam `1.2.0.rc1`

An `editable_file` within `editable_elements` when accessed via `page.children` is populated as expected when serving the site via Wagon, but always returns `nil` when serving via Engine.

@did I haven't been able to track this down just yet but happy to submit a PR if you can help point me in the right direction

> Originally [reported in Gitter](https://gitter.im/locomotivecms/v3?at=57b5ccb76a2fa2ff3d96d26a)

**Comment by cappadona** [comment]
@did If I'm correct in thinking @claes-pontusson and I are [describing the same behavior](https://gitter.im/locomotivecms/engine?at=57e13c4a33c63ba01a19eb58), perhaps this is a _feature_ and [not a bug](https://gitter.im/locomotivecms/engine?at=57e13d8433c63ba01a19f0c4)?

**Comment by Claes-Pontusson** [comment]
I can confirm the same behaviour with 

- Engine 3.2.0.rc2
- Wagon 2.2.0.rc2

**Comment by did** [comment]
here is the bug: https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/drops/page.rb#L96

.content -> editable_text
.source -> editable_file

**Comment by cappadona** [comment]
Thanks @did. The `editable_file` is now populated with the expected string. Any way to use this value and get Steam to generate a working path to the file when the site is hosted by Engine, or will that require a new filter?
