### ISSUE TITLE
Ability to delete a content entry from its edit page

### ISSUE THREAD

**Issue by bpatram** [locomotivecms/engine#1173]
Right now the only way to delete a content entry is from its content type's entries page (where it lists out all entries). I think it would make sense to also include a button on the content entry's edit page as well in order to delete it.

**Comment by did** [comment]
@bpatram agreed. 
@nielsenramon, sorry man, we need your help here! Any idea where we could put this button? (I'll code it). thanks!

**Comment by nielsenramon** [comment]
@bpatram @did Working on it :)

**Comment by bpatram** [comment]
Seems like this was merged in a while ago, closing this issue since it is no longer relevant.
