### ISSUE TITLE
Theme asset cache-buster scheme using url params doesn't work with S3 / Cloudfront

### ISSUE THREAD

**Issue by ronhornbaker** [locomotivecms/engine#1174]
First of all, Locomotive is an awesome CMS. Been building a personal site with it for about a week, and it's great being free from WordPress hell.

I've run into a fairly big show-stopper. I use S3 for asset storage and CloudFront for CDN, pulling from the S3 origin. Everything works great, except the asset files get cached too hard. 

For example, the url for the application.css file looks like this:
`https://XXXXXXXXX.cloudfront.net/sites/57ec05811ff64d0831ae1159/theme/stylesheets/application.css?1475278069`
where only the "1475278069" url param changes when I update that file.

While that type of cache-buster works for many webservers, it does NOT work on S3 - S3 happily serves up the same old application.css file to CloudFront as before, as S3 ignores url params.

By comparison, the Rails v4.2.7 asset pipeline churns out asset URLs like this:
`https://XXXXXXXXXX.cloudfront.net/assets/application-db63e1e59b0afc60970057edc713ed195bc29fb6598e8f35b711012a57d3ebe6.css`
where the entire css filename is changed, which solves any sort of caching issues.

Am I missing a configuration option somewhere? My only workaround atm is to not use S3 and Cloudfront for asset hosting, but that's gonna put more load on the webservers and be a worse end-user experience.

**Comment by Shigawire** [comment]
In CloudFront you can enable pass-through of the query-strings (which is the ?...-string at the end of the filename). That's how I do it to break the cache CloudFront, and for me it works.

**Comment by ronhornbaker** [comment]
Yes, I've tried that. The problem is that the S3 origin still serves up the
same file.

**Comment by Shigawire** [comment]
This is weird, because the S3 storage should not cache. Did you try pulling the file straight out of the bucket?

**Comment by ronhornbaker** [comment]
S3 storage allows custom meta-data on files, and I set Cache-Control and Expires headers to their max, so that CloudFront will pick up those headers and pass them along to the client. 

Imo, this is best-practice from an end-user pov, so that css and js files need be downloaded only once per browser per year, then cached aggressively. The user sees real speed improvements on subsequent visits, and my bandwidth bill is minimized.

Pretty sure this is why the Rails asset pipeline started renaming files... relying on query string changes to break caches isn't reliable regardless of cache directives in the meta headers.

From http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/QueryStringParameters.html:

> Amazon S3 and some HTTP servers don't process query string parameters and, therefore, don't return different versions of an object based on parameter values. For these origins, if you configure CloudFront to forward query string parameters to the origin, CloudFront will still cache based on the parameter values even though the origin returns identical versions of the object to CloudFront for every parameter value.

For now, my workaround is to rename files and edit their names in the layouts, a bit of a pain. Might try to automate it on deploy. But please do consider giving files a unique hash name prior to deploy, if they have changed; I can't think of any downside to that.

**Comment by Shigawire** [comment]
@ronhornbaker I've tried to reproduce your issue. I've had an asset on my site that I wanted to replace. I've taken the original image, edited it, saved it and re-uploaded:

``` curl -H 'Accept-Encoding: gzip,deflate' -I -s -X GET  https://cdn.<mydomain>/sites/57e05163566494000d4fc02d/pages/57e05163566494000d4fc02f/files/home-editor-screenshot.jpg?awdawadw
HTTP/1.1 200 OK
Content-Type: image/jpeg
Content-Length: 114123
Connection: keep-alive
Date: Sun, 16 Oct 2016 10:30:41 GMT
Last-Modified: Thu, 22 Sep 2016 18:09:38 GMT
ETag: "96a20751cc6423ddad156e21ebb173c1"
Accept-Ranges: bytes
Server: AmazonS3
Age: 134
X-Cache: Hit from cloudfront
Via: 1.1 fabe381dacc990f9c402cdc69b69dd26.cloudfront.net (CloudFront)
X-Amz-Cf-Id: JxRAzw6tjmVS6Dg1uZVv7QWJWI_hv71VKmlZhYQqyJlgIc1shvZq0A==
```
Then, after replacing the image:

```
 ~ curl -H 'Accept-Encoding: gzip,deflate' -I -s -X GET  https://cdn.<mydomain>/sites/57e05163566494000d4fc02d/pages/57e05163566494000d4fc02f/files/home-editor-screenshot.jpg\?awdawadw
HTTP/1.1 200 OK
Content-Type: image/jpeg
Content-Length: 78808
Connection: keep-alive
Date: Sun, 16 Oct 2016 10:36:06 GMT
Last-Modified: Sun, 16 Oct 2016 10:35:48 GMT
ETag: "269961ad93fcacb85d1bfa9b980653f5"
Cache-Control: max-age=31536000
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 268be5c908db8ae22ed9c5c6cfffc109.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 1IKiM1f57guESB1D9HuVN6D81_DqU5nNXTt_WbOfPTQjfEl8vVbcLA==
```

**Comment by did** [comment]
thanks @ronhornbaker for the kind message.
thanks @Shigawire for your help btw

@ronhornbaker, have you been able to make it work?
