### ISSUE TITLE
Feature Request: Page-level Private Access

### ISSUE THREAD

**Issue by vosmith** [locomotivecms/engine#1178]
Forgive me if this is already available, but I was not able to find any documentation on how to do this. I think it would be worth while to have password protected pages within a site. I'm aware that you can password protect the entire site, but I would need this on a few pages only. Is there support planned for this?

**Comment by did** [comment]
@vosmith, we're thinking about a member private access functionality. Nothing really defined, more news about it next week.

**Comment by did** [comment]
https://doc.locomotivecms.com/v4.0/docs/introduction-1
