### ISSUE TITLE
Feature request: Users/Accounts/Customers/Members support

### ISSUE THREAD

**Issue by mariusa** [locomotivecms/engine#1181]
Use case: a CMS with parts of the content available only to registered users/members

Please add support for Users/Accounts/Customers/Members ("Customers" would be best), so that they can register, login, reset password on the site front-end.
Please see Shopify Customers for inspiration.

Having Tags would help a lot, so we can control access to sections like this
{% if customer.tags contains 'Member' %}
   show content
{% else %}
   Register at...
{% endif %}

Thanks

**Comment by did** [comment]
hey @mariusa, I'm working on it (https://github.com/locomotivecms/steam/tree/authentication). Hope to be done by next week.

**Comment by did** [comment]
https://doc.locomotivecms.com/v4.0/docs/introduction-1
