### ISSUE TITLE
Unable to override engine controller

### ISSUE THREAD

**Issue by benjineering** [locomotivecms/engine#1182]
This doc page states that an engine controller can be overridden by individual apps, but it doesn't seem to work: [http://doc.locomotivecms.com/guides/tweak-models](http://doc.locomotivecms.com/guides/tweak-models)

I assume the docs are for an older version of engine - is there a way to achieve this with the latest engine version?

**Comment by did** [comment]
hi @benjineering, so wrong to answer now a 6 months old issue. Anyway, yes, the docs are for an old version of locomotive. 
For Locomotive v3, I do recommend to use the decorators pattern. This is described here: http://stackoverflow.com/questions/16590155/rails-decorators-overriding-a-rails-engine.

**Comment by benjineering** [comment]
@did I appreciate it regardless 👍
