### ISSUE TITLE
Feature Request: Let's encrypt support

### ISSUE THREAD

**Issue by kations** [locomotivecms/engine#1186]
Don't know if this is possible but it would be cool if i could easily generate an SSL from the Backoffice at the Domain list by clicking a Button.

**Comment by loyaruarutoitsu** [comment]
Well, you cant click a  button right now but you could integrate lets encrypt into the Rails engine. You now that, right?

**Comment by Shigawire** [comment]
I'd rather vouch for keeping this separated from the Locomotive-App or even the Rails-Stack.
Usually, the typical Rails application server like WEBrick or puma should not serve directly to the internet, but instead a proxy should be used.

Proxying SSL is just ugly and requires SNI. Please let the front-end proxy/cache server handle the SSL stuff. Also, SSL termination could be better handled if de-coupled from the app.

**Comment by merqlove** [comment]
Same here, i don't like idea to have LE within Rails.
