### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by merqlove** [locomotivecms/engine#1192]
Hi! First of all hello & thanks for LocomotiveCMS.

Tried to integrate turbolinks with engine, by port changes (2 last commits) from branch `turbolinks` into `master`.
Result:
https://github.com/merqlove/engine/tree/with-turbolinks

Just want to clarify the result status of this migration.
Seems that some modules (select2) conflicts with turbolinks dynamic reload.

**Comment by Shigawire** [comment]
Hey! Just stumbled across your ticket. 

Have a look at this: https://trello.com/c/xdHv9AeC/140-snappy-back-office-with-turbolinks

It looks like @did is already implementing this functionality.

**Comment by merqlove** [comment]
Hi, oops, ok. Haven't seen that.
