### ISSUE TITLE
Required text field with markdown formatting causes validation error

### ISSUE THREAD

**Issue by BlackPPoint** [locomotivecms/engine#1196]
I create content_type with required text field (text_formatting: markdown). When I creating a new entry of this content_type from the back-office, I can't submit form. I clicking "Save" button, but nothing happens. Actually, in javascript console I can see, that error "An invalid form control with name='content_entry[body]' is not focusable." is rising when I click "Save" button. Additionally, I can see, that textarea with name='content_entry[body]', which is "display: none;", is empty.

**Comment by did** [comment]
@BlackPPoint thanks for the bug report :-)
