### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by felix-last** [locomotivecms/engine#1203]
Been working on upgrading to engine v3 for the past days and like what I see so far. So first of all, thanks for your work! 
Second of all, I can't get my site running - perhaps you can help?
The error I get is: "Site not found. Please sign in first. Then, add the <mydomain.com> domain to the list of domains of one of your sites.". 
In site.yml I have ``domains: [<mydomain.com>]`` and wagon deploy works.
I can't sign in nor access the backoffice. However, I can see my page by going to mydomain.com/locomotive/my-site-handle (which shows me my liquid-coded 404 page).

I created the account through wagon auth and the site through wagon init, then wagon deploy. I'm running mongodb 2.6 rather than 3.x but doubt that this would be the source of the problem? I'm also using passenger as the app server, not puma.

- engine: edge
- wagon: 2.20

Please let me know if you need any more info.
Thank you,
Felix

**Comment by felix-last** [comment]
Here's a screenshot of the message I'm getting. Clicking "Next" redirects to `/locomotive/sign_in` which shows this message still.
![site-not-found-locomotive](https://cloud.githubusercontent.com/assets/783826/25280523/e4b518f8-26c7-11e7-8d99-74275da2f07d.png)

**Comment by aualdrich** [comment]
@felix-last Were you able to fix this? I'm getting the same error. Thanks!

**Comment by felix-last** [comment]
Nope, sorry. I'm still running on engine version 2.3. Please let me know if you find a solution :)

**Comment by did** [comment]
@felix-last @aualdrich very sorry for the very long delay. If it's still an issue, let me know.
