### ISSUE TITLE
Update metafields throught the API

### ISSUE THREAD

**Issue by AminataC** [locomotivecms/engine#1205]
Hello,

I'm wondering how to change the site's metafields with the API. Right now I can update some fields such as name.
I looked into the code and it seems like the attribute "metafields" is not part of the site's permitted attributes list.
https://github.com/locomotivecms/engine/blob/master/app/policies/locomotive/site_policy.rb (ligne 48)
I might be wrong. If i am, can someone please tell me how to update it ? If i'm not, is there a chance to have a fix ?

Thank you
Aminata

**Comment by did** [comment]
@AminataC you're absolutely right. I'm wondering if this is because of some rule in Wagon when deploying a site.

**Comment by did** [comment]
alright, the current_site and sites api endpoints were actually different when dealing with the update action. I fixed this. Thanks @AminataC for pointing it to me.
