### ISSUE TITLE
Is it possible to sync select_options entered via back-office to wagon content_type?

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/engine#1206]
I'm not seeing that happen. Currently running latest RCs (`engine-3.3.0.rc2` & `wagon-2.3.0.rc1`) but this has been the behavior for as long as I can remember.

What is the expected behavior/spec? Is what I'm seeing a bug or a feature? :)

Because the `select_options` managed via **edit options** link in back-office aren't included when running `wagon sync` this leads to errors when attempting to deploy the site with data to another engine:

```log
Resource invalid: <field> can't be blank
```

Does `wagon backup` capture the `select_options` as they exist in the back-office?

Anyone else run into this?

Thanks for any suggestions or advice.

**Comment by did** [comment]
@cappadona this seems to be related to https://github.com/locomotivecms/engine/issues/1233

**Comment by did** [comment]
Just ran a quick test with the code from the master branch, my backup got the right select_options.
