### ISSUE TITLE
How to use model file type in liquid？

### ISSUE THREAD

**Issue by tingrun919** [locomotivecms/engine#1221]
![image](https://user-images.githubusercontent.com/8611840/28704505-882c277a-739d-11e7-82e1-858d61f5472f.png)
this is carousel.yml
![image](https://user-images.githubusercontent.com/8611840/28704519-a41a3a9e-739d-11e7-92f7-88267c5d5dd6.png)
the picture is upload
i'm chinese , please help me!

**Comment by did** [comment]
hi @tingrun919, sorry for the delay. Next time, go to our Gitter channel instead. There are kind people there helping newcomers. Url: https://gitter.im/locomotivecms/engine?utm_source=share-link&utm_medium=link&utm_campaign=share-link.
Other than that, your code seems valid.
