### ISSUE TITLE
Rails 404 page loaded for path /404

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/engine#1229]
When loading the 404 path (example.com/404) on any Locomotive site, the engine's 404 page is loaded. 

In our case, for some reason and the pattern is not clear to me, some previously existing paths redirected to /404, instead of loading the site's 404 template (which is how we found above issue).

**Comment by banditrider** [comment]
Solved the mystery of the existing paths going to the rails 404 template: Somehow, a couple of PDFs contained the Rails 404 HTML docs. 

What remains would be the /404 paths leading to the sites 404 page instead of the Rails 404 page.

**Comment by did** [comment]
@banditrider did you remove the public/404.html page in your Rails app?

**Comment by did** [comment]
Works fine with code from the master branch so I close this issue.
