### ISSUE TITLE
Error with locomotive:install

### ISSUE THREAD

**Issue by Svashta** [locomotivecms/engine#1230]
Hi,

i am trying to give a Locomotive a spin, but am having problems installing engine.
I have RVM with ruby 2.4.0 and rails 4.2.6

bundle exec rails generate locomotive:install gives this:

/home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:110: warning: constant ::Fixnum is deprecated
/home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:111: warning: constant ::Bignum is deprecated
/home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
         ... 4073 levels...
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/----/.rvm/gems/ruby-2.4.0@locomotive/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

What is the problem? Is the Ruby too high?

**Comment by gridar** [comment]
Hi @Svashta ,
Thanks for trying locomotive, we are working on a new version which will use ruby 2.5 but currently I'll recommend staying in ruby 2.2.2.
That should resolve your problem.

**Comment by Svashta** [comment]
Hi @gridar 
Thanks for quick response.
I successfully installed engine and wagon. Now, while playing around a little, i am getting this error when deploying wagon to locomotive:  Unknown modifier: $pushAll

I have installed mongodb today, the latest version - but i suspect this might, again :), be the problem :)
Which mongo version do you support? In documentation it says any 3.x - i am using 3.6.2.

Thx

**Comment by manuchap** [comment]
You need to downgrade mongo to 3.4.

**Comment by Svashta** [comment]
Yup, all well. Thx
