### ISSUE TITLE
Puma Mongo connection

### ISSUE THREAD

**Issue by Svashta** [locomotivecms/engine#1231]
Hi,

i am trying to setup server with locomotive engine, puma and of course mongodb.
Puma scripts are all set, but puma fails to start because of the failing config.
I can't figure out how to properly set the MongoDB connection in on_worker_boot.
Need some assitance here.

I understand I can't do active_record connection as active record is not used with locomotive/mongoid.
But how do I establish connection properly?

Thanks

**Comment by Svashta** [comment]
Sometimes I want to complicate things :) . Turns out no connection configuration is needed at all.
Now the app loads, butnow i have other issues :)
Any idea:

Refused to execute script from 'http://DOMAIN/locomotive/sign_up' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
sign_up:1 Refused to apply style from 'http://DOMAIN/locomotive/sign_up' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by gridar** [comment]
Mmmh not sure what's that about, we'll need more context.
First where does that output come from ? Your web browser, your rails log or something else ?
Then, what's the content of your /etc/hosts ?
And what is the url you're requesting ?

**Comment by Svashta** [comment]
Hi,

the error comes from the browser console log.
Nothing special in production.log or puma log.

/etc/hosts:
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1 localhost.localdomain localhost railsbox
# Auto-generated hostname. Please do not remove this comment.
XX.XX.XX.XX railsbox.svashta.com  railsbox
::1     localhost       ip6-localhost   ip6-loopback

http://locomotive.svashta.com is the URL

**Comment by gridar** [comment]
It seems the error is Chrome specific as Firefox does not trigger it.
In both browsers you can see javascript is not loading properly ("$ is not defined" mean JQuery is not loaded).
Did you launch ```bundle exec rake assets:precompile```when you deployed your website like explained in the link below ?
https://locomotive-v3.readme.io/docs/heroku#section-pre-compile-your-assets

**Comment by Svashta** [comment]
Hey,

i have to admit i did not read Heroku part as it doesn't apply to me - i have my own server.
Reading it now and precompiling assets....it works :).
I did a precompiling before asking question, but it was failing, probably due to the initialize_on_precompile not being set.

Great, now i can try to play around :)
I guess i'll be having more question when it comes to multi-domain situation, which i hope it will at some point.

I would also just like to say i have applied on transifex to join the team. I would like to transalte the Slovenian langauge and use it eventually on my locomotive installation. Request is probably pending.

Thx for your help!

**Comment by gridar** [comment]
Glad you solved it out. Thank for the help in the translation, you've been added just now.
Let us know if you have more trouble.
See ya
