### ISSUE TITLE
Nokogiri vulnerability

### ISSUE THREAD

**Issue by Gianniballerini** [locomotivecms/engine#1232]
The version of libxml2 packaged with Nokogiri contains a vulnerability. Nokogiri has mitigated these issue by upgrading to libxml 2.9.6.

It was discovered that libxml2 incorrecty handled certain files. An attacker could use this issue with specially constructed XML data to cause libxml2 to consume resources, leading to a denial of service.

Category description: Denial of Service is any attack which causes a service to become unavailable for legitimate clients.

**Solution**: upgrade nokogiri to >= 1.8.2

**Comment by did** [comment]
@Gianniballerini, I've been working on the upgrade to 5.1 which should solve the vulnerability you're facing. Here is the experimental branch: https://github.com/locomotivecms/engine/tree/rails-5.1. All the tests pass but you might discover issues.

**Comment by did** [comment]
the https://github.com/locomotivecms/engine/tree/rails-5.1 branch is now using the very last version f Nokogiri.
