### ISSUE TITLE
locale_switcher in zh-CN

### ISSUE THREAD

**Issue by terfex** [locomotivecms/engine#1234]
When using the `{% locale_switcher %}` tag (referenced at https://locomotive-v3.readme.io/v3.3/docs/localization) on a Chinese page (zh-CN) , the resulting list shows duplicated Chinese entries for each locale instead of the correct name, however the link works still.

Locale Switcher on an English page
`<div id="locale-switcher"><a href="/" class="en current">English</a> | <a href="/zh-CN" class="zh-CN">Chinese</a></div>`

Locale Switcher on an Chinese page
`<div id="locale-switcher"><a href="/" class="en">中文</a> | <a href="/zh-CN" class="zh-CN current">中文</a></div>`

On a sidenote, is it also possible to show country flags as well?

**Comment by terfex** [comment]
Please note this only occurs when using `{% locale_switcher label: 'locale' %}`. ISO labels are not affected.

**Comment by terfex** [comment]
Apologies for any confusion caused by accidental closing of the issue earlier.

**Comment by did** [comment]
@terfex no pb :-) didn't have a chance to look at it
