### ISSUE TITLE
Aws::S3::Errors::Forbidden in Locomotive::ContentEntries#edit

### ISSUE THREAD

**Issue by stunjiturner** [locomotivecms/engine#1236]
Using the latest locomotive engine form master, When I goto upload a image to one of my content entries, the file do not upload, and I get following error

''''
Aws::S3::Errors::Forbidden in Locomotive::ContentEntries#edit

'''

**Comment by toreyheinz** [comment]
@stunjiturner 

I tested this with:
  **Ruby**: 2.5.1
  **Rails**: 5.1.6
  **Locomotive**: Master
and it worked with a PNG and JPG image.

Have you tried it with other files?

Below are the accepted content_types

```ruby
def content_types
  {
    image:      ['image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png', 'image/jpg', 'image/x-icon', 'image/svg+xml'],
    media:      [/^video/, 'application/x-shockwave-flash', 'application/x-flash-video', 'application/x-swf', /^audio/, 'application/ogg', 'application/x-mp3'],
    pdf:        ['application/pdf', 'application/x-pdf'],
    stylesheet: ['text/css'],
    javascript: ['text/javascript', 'text/js', 'application/x-javascript', 'application/javascript', 'text/x-component'],
    font:       [/^application\/.*font/, 'application/x-font-ttf', 'application/vnd.ms-fontobject', 'application/x-woff', 'application/x-woff2', 'application/x-font-truetype', 'application/x-font-woff', 'application/x-font-woff2']
  }
end
```

**Comment by stunjiturner** [comment]
I tried it with pdf and png

S Tunji Turner
sightuary
@sightuary

**Comment by toreyheinz** [comment]
Oops, I did not test this with AWS, I'll give that a try. 

Could you post the full error trace?

Torey

**Comment by stunjiturner** [comment]
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/request.rb:70:in `send_request'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/client.rb:5462:in `put_object'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/file_uploader.rb:42:in `block in put_object'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/file_uploader.rb:49:in `open_file'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/file_uploader.rb:41:in `put_object'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/file_uploader.rb:34:in `upload'
vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.9.0/lib/aws-sdk-s3/customizations/object.rb:252:in `upload_file'
vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws_file.rb:59:in `store'
vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:18:in `block in store!'
vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:17:in `tap'
vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:17:in `store!'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/store.rb:57:in `block in store!'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/store.rb:56:in `store!'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/mounter.rb:100:in `each'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/mounter.rb:100:in `store!'
vendor/bundle/ruby/2.5.0/gems/carrierwave-1.2.2/lib/carrierwave/mount.rb:395:in `store_promo!'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `block in invoke_after'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `each'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `invoke_after'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
vendor/bundle/ruby/2.5.0/gems/mongoid-6.3.0/lib/mongoid/interceptable.rb:132:in `run_callbacks'
vendor/bundle/ruby/2.5.0/gems/mongoid-6.3.0/lib/mongoid/persistable/updatable.rb:110:in `prepare_update'
vendor/bundle/ruby/2.5.0/gems/mongoid-6.3.0/lib/mongoid/persistable/updatable.rb:132:in `update_document'
vendor/bundle/ruby/2.5.0/gems/mongoid-6.3.0/lib/mongoid/persistable/savable.rb:25:in `save'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/app/services/locomotive/content_entry_service.rb:108:in `block in update'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/app/services/locomotive/content_entry_service.rb:104:in `tap'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/app/services/locomotive/content_entry_service.rb:104:in `update'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/app/controllers/locomotive/content_entries_controller.rb:65:in `update'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/time/zones.rb:64:in `use_zone'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/app/controllers/locomotive/concerns/timezone_controller.rb:8:in `set_timezone'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:135:in `run_callbacks'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124:in `process'
vendor/bundle/ruby/2.5.0/gems/actionview-5.1.6/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844:in `call'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `public_send'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `method_missing'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844:in `call'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/lib/locomotive/middlewares/site.rb:26:in `call'
vendor/bundle/ruby/2.5.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'
vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/conditional_get.rb:38:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-71e6eb051bfe/lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
vendor/bundle/ruby/2.5.0/gems/dragonfly-1.1.5/lib/dragonfly/cookie_monster.rb:9:in `call'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.5.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.5.0/gems/puma-3.11.3/lib/puma/configuration.rb:225:in `call'
vendor/bundle/ruby/2.5.0/gems/puma-3.11.3/lib/puma/server.rb:624:in `handle_request'
vendor/bundle/ruby/2.5.0/gems/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
vendor/bundle/ruby/2.5.0/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
vendor/bundle/ruby/2.5.0/gems/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"iL8uRHQNsC8EFuJM4JmBmW11Of3SMMaumwh892huQZ4u1AEvscErBb/v8NSWkRwqIZDD5BJeEM53QEWgt6KKKA==",
 "active_tab"=>"main",
 "_location"=>"",
 "content_entry"=>
  {"title"=>"The Northeast Adventure 3",
   "formatted_start_date"=>"07/19/2015",
   "formatted_end_date"=>"07/26/2015",
   "promo"=>
    #<ActionDispatch::Http::UploadedFile:0x000055b7d8ac2c00
     @content_type="image/jpeg",
     @headers="Content-Disposition: form-data; name=\"content_entry[promo]\"; filename=\"IMG_0457-1.JPG\"\r\n" + "Content-Type: image/jpeg\r\n",
     @original_filename="IMG_0457-1.JPG",
     @tempfile=#<File:/tmp/RackMultipart20180409-11-hw77kp.JPG>>,
   "remove_promo"=>"0",
   "remote_promo_url"=>"[FILTERED]",
   "occurrence_id"=>"5697e0e24865e7000b000016",
   "summary"=>
    "<p>Summers northern exposure, come join us for a five day sustainable&nbsp;living systems focused summer enrichment program for school age boys and their&nbsp;guardians. The summer of 2014 we will travel to the White Mountain National&nbsp;Forest region of New Hampshire, with day trips to Maine and Vermont. Our&nbsp;qualified guides and staff will teach life long learning activities and techniques&nbsp;to the participants. A full list of activities and a healthy menu will be provided&nbsp;upon proper registration.<br></p>",
   "formatted_rsvp_date"=>"",
   "place"=>"White Mountain National Forest",
   "store_code"=>"",
   "active"=>"0",
   "program_id"=>"569d760447ba69000b00001d",
   "tags"=>"camping,tenting,whales,new hampshire,maine,swimming",
   "intent_ids"=>["569a8cb95534ea000b000045"],
   "seo_title"=>"",
   "meta_keywords"=>"",
   "meta_description"=>"",
   "_slug"=>"tnea-3",
   "_visible"=>"1"},
 "_wysihtml5_mode"=>"1",
 "site_handle"=>"lush-briars-4816",
 "slug"=>"experiences",
 "id"=>"569a8eee5534ea0013000053"}

**Comment by stunjiturner** [comment]
Important Change - Managing Your AWS Secret Access Keys
As described in a previous announcement, you cannot retrieve the existing secret access keys for your AWS root account, though you can still create a new root access key at any time. As a best practice, we recommend creating an IAM user that has access keys rather than relying on root access keys.

**Comment by toreyheinz** [comment]
OK, I was able to verify upload with AWS https://teagles-sandbox.s3.amazonaws.com/sites/5ac3bb17f88fbb5e0d7efd8d/content_entry5ac3bb75f88fbb5e0d7efd92/5acbba3af88fbb3b95568d4f/files/wwwgooglecom-full.png

Your params look right and you're getting a Forbidden error, so I'm guessing your bucket permissions or your IAM user doesn't the right access level. https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList

As a test:
- Create a new IAM user and grant them AmazonS3FullAccess
- Create a new bucket
- Add the new creds to your app and try again.

* Make sure you have your region right when setting your `S3_BUCKET_REGION=<YOUR S3 BUCKET REGION>` https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.`

**Comment by stunjiturner** [comment]
Did you try with PDF

S Tunji Turner
sightuary
@sightuary

**Comment by toreyheinz** [comment]
Yes, PDF worked just fine.

One kind of hacky way to debug this is to put a debugger in the AWS gem at vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/request.rb:70
```ruby
def send_request(options = {}, &block)
  @context[:response_target] = options[:target] || block
  @handlers.to_stack.call(@context)
  byebug ## opens debugger in console
end
```

Trying uploading a file, then in your console try `(byebug) pp @context.http_response`

For me it looks like:
```
#<Seahorse::Client::Http::Response:0x00007facb0852a78
 @body=#<StringIO:0x00007facb0852938>,
 @complete=false,
 @done=true,
 @error=nil,
 @headers=
  {"x-amz-id-2"=>"ZywVyjscHKPdcYXEogn3hTva7pEkN9+oFZxhwrbwAfdntZlGlHPq8zKHYeDDOHZexLSFU660MzM=", "x-amz-request-id"=>"DA396C1FF1747AF0", "date"=>"Tue, 10 Apr 2018 00:53:34 GMT", "etag"=>"\"619f77112b02b441730b299b3e2f5c56\"", "content-length"=>"0", "server"=>"AmazonS3"},
 @listeners={:headers=>[], :done=>[], :data=>[]},
 @status_code=200>
```

For you, I'm guessing the error will contain something helpful. Post it here if it does.
