### ISSUE TITLE
(3.4) Select2 broken with multiple many-to-many relationships in one form

### ISSUE THREAD

**Issue by toreyheinz** [locomotivecms/engine#1237]
Creating a separate issue from this thread #1189.

This was working at this commit 48b263e
<img width="1122" alt="screenshot 2018-04-10 09 49 32" src="https://user-images.githubusercontent.com/23319/38562260-22a43b52-3ca8-11e8-8061-0aafb2befbbb.png">

I upgraded the base app and set the locomotivecms to commit cca767b, to see if it was working at any point since upgrading to Rails 5. It was not :(

I will switch back to master, and work from there.

**Comment by toreyheinz** [comment]
This took way too long for figure out. In the end, it seems to have been an issue with the duplicate IDs, even though it was fine before. I'm guessing there was a change in the select2 js that was introduced here c2136a1.

**Comment by did** [comment]
thanks @toreyheinz for having pointed the wrong code!
