### ISSUE TITLE
RAILS 5 / HEROKU Can't verify CSRF token authenticity. Completed 422 Unprocessable Entity. 

### ISSUE THREAD

**Issue by potluckcatering** [locomotivecms/engine#1244]
Hi I realize 3.4 is in beta, however was wondering if you could still provide some guidance. I've deployed Engine to Heroku using rails 5.1.6 and ruby 2.5.1. The deployment went fine, however when I try to create a new account I am greeted with: 
<img width="536" alt="screen shot 2018-07-11 at 3 17 26 pm" src="https://user-images.githubusercontent.com/41126701/42602282-9a4e5742-851d-11e8-9c02-64c76496670e.png">
Also the logs:
<img width="1406" alt="screen shot 2018-07-11 at 3 18 38 pm" src="https://user-images.githubusercontent.com/41126701/42602312-bc7743ba-851d-11e8-9aab-bc1fa9dad2d3.png">
I'm aware that its possible to add the  skip_before_action :verify_authenticity_token in the application controller but feel that is not the appropriate way to go about this. Any guidance from the Locomotive team would be great.

Thanks in advance!

**Comment by potluckcatering** [comment]
Okay a slight update but still a problem. I've added prepend: true to protect from forgery in the application controllers as is done with Rails 5. So account creation works, I can see in mongolab a new user is created, however immediately after creating the account I am redirected to sign and when I try to sign in, i get redirected back. Here's the logs:
<img width="1386" alt="screen shot 2018-07-11 at 3 26 22 pm" src="https://user-images.githubusercontent.com/41126701/42602669-5ef59b4a-851f-11e8-819c-fe215fed7049.png">
It looks like pundit is blocking the new user from accessing the sites index as we now have a 401 error. Again any help is greatly appreciated!

**Comment by manuchap** [comment]
Have you generated your secret key (rake secret) and put it in your SECRET_KEY_BASE config variable?

**Comment by potluckcatering** [comment]
@manuchap hi I realized I hadn't but just tried it. I done rake secret and added it to heroku config, restarted the app but am getting the same error. I appreciate your advice and hope you or anyone else can provided more insight/guidance.

**Comment by manuchap** [comment]
Someone had a similar issue over at [gitter](https://gitter.im/locomotivecms/v3?at=58359003bc17b2e756070793).
You might wanna ask there since more people might read you.
In the meantime here's [my heroku gemfile](https://tgvbkp.studiowan.fr/miscs/heroku-gemfile?type=misc).

**Comment by potluckcatering** [comment]
@manuchap thanks for pointing me to that gitter thread. I believe I am having the same issue because strangely enough I had to use the Chrome extension SessionBox to fire up a new session. Once that happened I logged in correctly and the whole app works, including aws, etc. I am still having that problem though where I cannot log in unless i fire up a new session using SessionBox. It's weird because I can't log in using Firefox, Edge or Incognito Chrome (even on different computers in different locations), and SessionBox is the only way. What exactly did @did mean in that thread when he said "the "ActionController::InvalidAuthenticityToken” exception might happen if you try to save a cached form and that your server has been restarted between." ? How do I resolve that so I can log in normally. It's impractical for client to have that extension on their browser and use it each time they log in. Again I appreciate all of your help. Apologies if this is a very noob question but I'm pretty much just a HTML,CSS, Javascript front end guy - but that's also the reason why Locomotive makes so much sense for my client projects!

**Comment by did** [comment]
hi @potluckcatering, good call, don't add `skip_before_action :verify_authenticity_token` as you wisely mentioned it.
Does it work locally?

**Comment by JacobEvelyn** [comment]
Hi @did @manuchap, I'm having the same issue. Locally everything works fine, but when I push my app to Heroku and run it in production I get CSRF errors when trying to create a new account or log in with an existing one. Heroku automatically generates a `SECRET_KEY_BASE` environment variable.

**Comment by gridar** [comment]
Hi @JacobEvelyn, Hi @potluckcatering,
It seems the sessions workflow in mongoid changed somehow.
Try adding a new initializers in config/initializers/session_store.rb with the following : 
```Rails.application.config.session_store :cookie_store, key: '_station_session'```
Solved it for me.
It let Rails take care of session. We'll update Locomotive to use session the Rails' way.

**Comment by JacobEvelyn** [comment]
Thanks for the help, @gridar. I tried adding that initializer and now when I try to register a new account I get this error resulting in a 500 response:

```
[LocomotiveCMS] [ApplicationError] #<Module::DelegationError: Locomotive::ApplicationPolicy#account delegated to membership.account, but membership is nil: #<Locomotive::SitePolicy:0x00007f944ea2d700 @membership=nil, @resource=Locomotive::Site>>

vendor/bundle/ruby/2.5.0/bundler/gems/engine-a6302d231603/app/policies/locomotive/application_policy.rb:15:in `rescue in account'
Module::DelegationError (Locomotive::ApplicationPolicy#account delegated to membership.account, but membership is nil: #<Locomotive::SitePolicy:0x00007f944ea2d700 @membership=nil, @resource=Locomotive::Site>):
vendor/bundle/ruby/2.5.0/bundler/gems/engine-a6302d231603/app/policies/locomotive/application_policy.rb:15:in `account'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-a6302d231603/app/policies/locomotive/application_policy.rb:24:in `initialize'
...
```

**Comment by did** [comment]
> Hi @JacobEvelyn, Hi @potluckcatering,
> It seems the sessions workflow in mongoid changed somehow.
> Try adding a new initializers in config/initializers/session_store.rb with the following :
> `Rails.application.config.session_store :cookie_store, key: '_station_session'`
> Solved it for me.
> It let Rails take care of session. We'll update Locomotive to use session the Rails' way.

https://github.com/mongoid/mongo_session_store/issues/35
