### ISSUE TITLE
Sections select2 wrong placement

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/engine#1259]
See attached screenshot. I have tested this in **Firefox**, **Chrome** and **Safari**. The issue persists.
Here are the versions I have in my Gemfile:
```ruby
gem 'custom_fields', require: false
gem 'locomotivecms_common', require: false
gem 'locomotivecms_steam', github: 'locomotivecms/steam', branch: 'sections', ref: '9d075ad', require: false
gem 'locomotivecms_coal', github: 'locomotivecms/coal', branch: 'master', ref: '761f15a', require: false
gem 'locomotivecms', github: 'locomotivecms/engine', branch: 'sections', ref: 'a584f599'
```

![screen shot 2018-10-09 at 11 38 06](https://user-images.githubusercontent.com/7840007/46660745-ff734c00-cbb7-11e8-93f7-5d650934831e.png)

**Comment by did** [comment]
hmmm, I don't see the issue anymore on our last version.

**Comment by DonKoko** [comment]
Nope, was fixed indeed.
