### ISSUE TITLE
Locomotive internationalization problem with pushing to the engine

### ISSUE THREAD

**Issue by truthSeekr** [locomotivecms/engine#1260]
(info about resolving issue was my first situation I decided to edit topic not adding new)

now i have : 

```
  persisting index (pl-PL, en) [done]
  persisting 404 (pl-PL, en) [done]
  persisting layouts (pl-PL) [done]
  persisting layouts/default (pl-PL, en) [done]
 [failed]
    undefined method `+' for nil:NilClass

# Error description:
undefined method `+' for nil:NilClass



```
# Backtrace:

	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:40:in `label_for'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:33:in `block in _push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'

**I resolved the issue.**
_I had already pages created in "single lang way" therefore sites on engine was considered that they lack "pl-PL". I had to delete site and create again as I can't delete pages without "slug"._ 

I use `gem 'locomotivecms_wagon', '~> 2.4.0'`

In pages/ every file has copy with "pl-PL" added like "index.pl-PL.liquid.haml". Its like the doc is saying:

    For instance, if you have an index.liquid page that you want to localize, create a index.fr.liquid page in the app/views/pages folder.

Every file in pages/layouts/ is like

```
---
title: Strona domowa
published: true
handle: domowa
---
```
to be sure `title` and `handle` is uniq on everypage
What Am I doing wrong ?

Error:
``
[Pushing Site
  persisting mywebsite [skip]

Pushing ContentTypes
  persisting Nieruchomosci [done]
  persisting Nieruchomosci with relationships [skip]

Pushing Pages
  persisting index (pl-PL) [done]
  persisting 404 (pl-PL) [done]
  persisting layouts (pl-PL) [failed]
    **Resource invalid: title can't be blank**

# Error description:
Resource invalid: title can't be blank

# Backtrace:

	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_coal-1.5.1/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_coal-1.5.1/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_coal-1.5.1/lib/locomotive/coal/resources/base.rb:35:in `update_with_locale'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:27:in `block in persist'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:114:in `block (3 levels) in translated_in'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:113:in `tap'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:113:in `block (2 levels) in translated_in'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_steam-1.4.0/lib/locomotive/steam/decorators/i18n_decorator.rb:48:in `__with_locale__'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:112:in `block in translated_in'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `each'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `find_all'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `translated_in'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:23:in `persist'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/core_ext/time/zones.rb:64:in `use_zone'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon.rb:73:in `push'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/gems/locomotivecms_wagon-2.4.0/bin/wagon:12:in `<top (required)>'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/bin/wagon:23:in `load'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/bin/wagon:23:in `<main>'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	/home/radoslaw/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
]
```
engine Gemfile:
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.6'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'devise', '~> 4.4.3'
gem 'mongoid', '~> 6.4.2'
gem 'locomotivecms', :git => "https://github.com/locomotivecms/engine.git", :branch => "v3.4.x"
gem 'bootsnap', require: false
gem 'moped'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

**Comment by truthSeekr** [comment]
Yes 2 Lang, When English was my Main Lang and my files was 'index.pl-Pl.liquid' it worked. It doesnt work when my first Lang is pl-PL, and second is English, files are then with '. en'.

**Comment by manuchap** [comment]
There were a few mistakes in you wagon site. I sent you the git link on gitter.

**Comment by truthSeekr** [comment]
Thanks ! I will check it out right away.
