### ISSUE TITLE
Module::DelegationError when creating account

### ISSUE THREAD

**Issue by JacobEvelyn** [locomotivecms/engine#1265]
Another issue from me (sorry!) in trying to upgrade our app to Locomotive 3.4. I didn't see this locally (possibly because my local app has an empty database but our Heroku testing one does not), but when I push my engine to Heroku and try to use the Locomotive `sign_up` page to create a new account, I encounter this error:

```
Module::DelegationError (Locomotive::ApplicationPolicy#account delegated to membership.account, but membership is nil: #<Locomotive::SitePolicy:0x000055fdf06e56d8 @membership=nil, @resource=Locomotive::Site>):
vendor/bundle/ruby/2.5.0/bundler/gems/engine-9ed6083539b5/app/policies/locomotive/application_policy.rb:15:in `rescue in account'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-9ed6083539b5/app/policies/locomotive/application_policy.rb:15:in `account'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-9ed6083539b5/app/policies/locomotive/application_policy.rb:24:in `initialize'
vendor/bundle/ruby/2.5.0/gems/pundit-1.1.0/lib/pundit.rb:112:in `new'
vendor/bundle/ruby/2.5.0/gems/pundit-1.1.0/lib/pundit.rb:112:in `policy!'
vendor/bundle/ruby/2.5.0/gems/pundit-1.1.0/lib/pundit.rb:235:in `policy'
vendor/bundle/ruby/2.5.0/gems/pundit-1.1.0/lib/pundit.rb:194:in `authorize'
vendor/bundle/ruby/2.5.0/bundler/gems/engine-9ed6083539b5/app/controllers/locomotive/sites_controller.rb:9:in `index'
...
```

Is there some setup step or database migration I'm missing?

**Comment by did** [comment]
@gridar any hint? thanks!

**Comment by JacobEvelyn** [comment]
@gridar just a friendly ping! 😃

**Comment by did** [comment]
hi @JacobEvelyn, could you try with https://rubygems.org/gems/locomotivecms/versions/4.0.0.alpha3 ? (don't be scared, it's marked as alpha but we've already been running it in production for a couple of months).
Re-open the issue if you still have the issue.

**Comment by JacobEvelyn** [comment]
Hey @did, thanks for following up here. We ended up switching away from Locomotive, in part because this problem didn't seem to be getting any traction and we were [uncomfortable being on out-of-date versions of Rails](https://github.com/locomotivecms/engine/issues/1189#issuecomment-370878634). It sounds like the project is moving forward though! Best of luck.

**Comment by did** [comment]
It's our fault, sorry about that :-( 
Thanks for the message anyway!
