### ISSUE TITLE
Field : Image multiple sizes

### ISSUE THREAD

**Issue by proxygear** [locomotivecms/engine#1267]
Hello,

I would like to build a Gallery within Locomotive.
I checked the questions already asked on the topic.

I can change default image quality with this hack : https://github.com/locomotivecms/engine/issues/925

However, it would be nice to generate multiple sizes, you know, one for overview, and one larger after clicking the preview.
I don't see how this could be done.

One hack I would think of would be to hook the `model update action` to detect fields group such as :
* original_picture
* preview_picture
to generate the preview field depending on the original ...

Do you think it's do-able, or am I going the wrong direction (for a quick dirty hack) ?

**Comment by did** [comment]
Why not creating a section that will name "gallery"? https://doc.locomotivecms.com/v4.0/docs/section-introduction
A block of a section would represent an image (the original picture). 
Then, in the liquid template of your section, you'd use the resize liquid tag to get a thumbnail of your image (https://doc.locomotivecms.com/v4.0/docs/filters#section-resize)
