### ISSUE TITLE
Pasting html with inline styles, removes styles

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/engine#1269]
At the moment, when using a field `editable_text` with format `html`, the authors cannot paste html with inline styles in the wysiwyg editor. If you for example paste a responsive embed code from vimeo, it will just remove the styles and basically make it look broken.
This means that it is basically impossible for an author to properly embed a video in an `editable_text` field, unless they know html, which is not to be expected. 

Was this made on purpose, can it be turned off as an option?

Engine version: 3.4.0.

**Comment by gridar** [comment]
Hi @DonKoko,
Yes this is made on purpose. We could enable it via an argument in the section JSON and pass it to the wysiwyg in rich_text.js
https://github.com/locomotivecms/engine/blob/559702f3c7ccb946d847dfe07f77c67232ea65b1/app/javascript/src/locomotive/editor/inputs/rich_text.js#L83

We didn't think of this use case. Mostly, users don't know about CTRL+SHIFT+V so we just remove text style by default.

Might be nice to have an option here.

**Comment by DonKoko** [comment]
Makes sense. I agree both cases can be useful. What about adding an option in for it when creating a `content_type` text field, which has `html` formatting? That way we can enable it in some fields and disable it in others?

**Comment by gridar** [comment]
oh sorry you're on 3.4.0 and I was talking about 4.0. My bad I need to dig that a bit

**Comment by did** [comment]
okay, it sounds that we could add an option to enable/disable the style removing when pasting HTML in the rich text field of a content entry.

**Comment by DonKoko** [comment]
I really like that option. And what about the idea of allowing to switch to html view?
