### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by EBII** [locomotivecms/engine#1282]
Hello !
create site in locomotive 4.0.0RC0
in ACCESS POINT activate  Site-Wide Password and save 
go to your empty site => stack trace
![invalid](https://user-images.githubusercontent.com/4985100/56978482-e5ab4d80-6b77-11e9-9f5a-177dd97a7941.png)

**Comment by manuchap** [comment]
Version of ruby/rails?
Just tried it with the same versions and it worked (with local domain) on ruby 2.5.3.
Try with the latest gems clones:
```
gem 'locomotivecms_common', path: '../common', require: false
gem 'custom_fields', path: '../custom_fields' # for Developers
gem 'locomotivecms_steam', path: '../steam', require: false
gem 'locomotivecms', path: '../engine'
```

**Comment by did** [comment]
I was unable to reproduce it in the last commit :-(
