### ISSUE TITLE
Add support for default value to metafields_schema.yml

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1298]
It seems awkward to define the default values for the site metafields within `config/site.yml`. This makes it easy to have inconsistencies between the this file and the `metafields_schema.yml`. 

I propose to have a default value key within `metafields_schema.yml`. This would lead to less inconsistencies and would take less brain power as I can define I default while I am defining it without context switching.

**Comment by did** [comment]
I see your point but I won't call it `default`. In your example, it's more a test value that you want to have in your wagon site and not necessarily in your engine when you'll deploy your site.
In that case, I guess, yes, we could have like another field (I don't like the `default` name) to set its test value.

**Comment by westonganger** [comment]
What about `sample_value`

**Comment by did** [comment]
I chose `sample` :-)

Example:
```yaml
theme:
  fields:
    font:
      type: string
      sample: 'OpenSans'
```

**Comment by westonganger** [comment]
Awesome this will be much easier to use. Thanks!

**Comment by westonganger** [comment]
I note documentation needs to be updated still. Will the old way of defining within config/site.yml be removed from the docs? I think it should be as its confusing or its section should be downsized and  strongly recommended to use the new approach.

**Comment by westonganger** [comment]
I note that this new `sample` field will not be deployed? Can we please make it deployable so that it is a complete drop in replacement for config/site.yml metafields

**Comment by westonganger** [comment]
Theres a bug with the new implementation. The value in `config/site.yml` should take precendence over the `sample` in `config/metafields_schema.yml`. Currently its the other way around.
