### ISSUE TITLE
Rename sections liquid tag :placement argument

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1305]
By reading the documentation I was not sure what the sections liquid tag `:placement` option did. Is the position related to the frontend html or to the backend editor? After experimenting I found it is for the backend editor grouping.

Maybe it could be renamed to better explain this. ie. `:editor_group_placement`

**Comment by did** [comment]
Hmm, I think the description of the `placement` attribute is pretty clear (https://doc.locomotivecms.com/v4.0/docs/how-to-display-sections#section-global-sections). No?

**Comment by westonganger** [comment]
That was just my initial thought while reading the code, I am reading Liquid/HTML I am thinking front end / views. I was confused, others may think the same too.

**Comment by did** [comment]
Got it, I've added a callout to precise what the **placement** atttribute is used for.
