### ISSUE TITLE
double / in url ?

### ISSUE THREAD

**Issue by EBII** [locomotivecms/engine#1311]
have you seen the double / aprear after login in the url ? 
domain.fr//locomotive ?

**Comment by did** [comment]
@EBII, I can't reproduce it :-( Could you reproduce it? Could you write a spec? thanks!

**Comment by EBII** [comment]
yes it is the second installation that generates this behavior
i don't know where is from so .. what you need ?

**Comment by did** [comment]
hmmm, the server logs could be a good start

**Comment by EBII** [comment]
my log goes to syslog with systemd.service. 
so i grep on // 
![image](https://user-images.githubusercontent.com/4985100/58030698-472f5e00-7b1f-11e9-883e-820fc0278c37.png)

**Comment by did** [comment]
hard to say, don't you have a more precise set of logs from a simple sign in process. Would it be possible that it's caused by a bad Nginx config?

**Comment by EBII** [comment]
for nginx i dont think so after read site config there no trailing / 

this log for one url ask thet return with double /
May 20 15:02:05 www LocoMotiveCMS[25866]: Started GET "/locomotive/sites/" for 127.0.0.1 at 2019-05-20 17:02:05 +0200
May 20 15:02:05 www LocoMotiveCMS[25866]: [LocomotiveCMS] [fetch site] host = www.cryptome.fr / site_handle = nil / locale = :en
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"domains"=>{"$in"=>["www.cryptome.fr"]}}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x70016169878060 type=uuid data=0xa5bc579e8fc6402c...>}}
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | SUCCEEDED | 0.001s
May 20 15:02:05 www LocoMotiveCMS[25866]: Processing by Locomotive::SitesController#index as HTML
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"_id"=>BSON::ObjectId('5ce067314eae35606c74f64d')}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x70016169878060 type=uuid data=0xa5bc579e8fc6402c...>}}
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | SUCCEEDED | 0.001s
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"memberships.account_id"=>BSON::ObjectId('5ce067314eae35606c74f64d')}, "sort"=>{"name"=>1}, "lsid"=>{"id"=><BSON::Binary:0x70016169878060 type=uuid data=0xa5bc579e8fc6402c...>}}
May 20 15:02:05 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | SUCCEEDED | 0.001s
May 20 15:02:05 www LocoMotiveCMS[25866]: DEPRECATION WARNING: Rendering layouts from an absolute path is deprecated. (called from resolve_layout at /home/eric/.rvm/gems/ruby-2.5.1/gems/actionview-6.0.0.rc1/lib/action_view/renderer/template_renderer.rb:102)
May 20 15:02:05 www LocoMotiveCMS[25866]:   Rendering /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/sites/index.html.slim within locomotive/layouts/account
May 20 15:02:05 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/shared/account/_navigation.html.slim (Duration: 1.4ms | Allocations: 987)
May 20 15:02:05 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/shared/_account_navigation.slim (Duration: 3.8ms | Allocations: 2781)
May 20 15:02:05 www LocoMotiveCMS[25866]:   Rendered collection of templates [0 times] (Duration: 0.0ms | Allocations: 3)
May 20 15:02:05 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/sites/index.html.slim within locomotive/layouts/account (Duration: 4.6ms | Allocations: 3089)
May 20 15:02:05 www LocoMotiveCMS[25866]: Completed 200 OK in 371ms (Views: 361.4ms | Allocations: 354622)
May 20 15:02:20 www LocoMotiveCMS[25866]: Started GET "//locomotive/sites/new" for 127.0.0.1 at 2019-05-20 17:02:20 +0200
May 20 15:02:20 www LocoMotiveCMS[25866]: [LocomotiveCMS] [fetch site] host = www.cryptome.fr / site_handle = nil / locale = :en
May 20 15:02:20 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"domains"=>{"$in"=>["www.cryptome.fr"]}}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x70016169878060 type=uuid data=0xa5bc579e8fc6402c...>}}
May 20 15:02:20 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | SUCCEEDED | 0.000s
May 20 15:02:20 www LocoMotiveCMS[25866]: Processing by Locomotive::SitesController#new as HTML
May 20 15:02:20 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"_id"=>BSON::ObjectId('5ce067314eae35606c74f64d')}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x70016169878060 type=uuid data=0xa5bc579e8fc6402c...>}}
May 20 15:02:20 www LocoMotiveCMS[25866]: MONGODB | localhost:27017 | locomotive_development.find | SUCCEEDED | 0.000s
May 20 15:02:20 www LocoMotiveCMS[25866]: DEPRECATION WARNING: Rendering layouts from an absolute path is deprecated. (called from resolve_layout at /home/eric/.rvm/gems/ruby-2.5.1/gems/actionview-6.0.0.rc1/lib/action_view/renderer/template_renderer.rb:102)
May 20 15:02:20 www LocoMotiveCMS[25866]:   Rendering /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/sites/new.html.slim within locomotive/layouts/account
May 20 15:02:20 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/shared/account/_navigation.html.slim (Duration: 1.4ms | Allocations: 987)
May 20 15:02:20 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/shared/_account_navigation.slim (Duration: 3.8ms | Allocations: 2793)
May 20 15:02:20 www LocoMotiveCMS[25866]:   Rendered /home/eric/.rvm/gems/ruby-2.5.1/gems/locomotivecms-4.0.0.rc0/app/views/locomotive/sites/new.html.slim within locomotive/layouts/account (Duration: 15.5ms | Allocations: 19294)
May 20 15:02:21 www LocoMotiveCMS[25866]: Completed 200 OK in 364ms (Views: 359.9ms | Allocations: 365253)
![doubleslash](https://user-images.githubusercontent.com/4985100/58031902-b7d77a00-7b21-11e9-97eb-eb699256d021.gif)

**Comment by did** [comment]
I do believe it's a Nginx issue :-)

- **Step 1**

```bash
~ -  $ curl -I https://www.cryptome.fr/locomotive/sites
...
Location: http://www.cryptome.fr/locomotive/sign_in
...
```

- **Step 2**

```bash
~ -  $ curl -I http://www.cryptome.fr/locomotive/sign_in
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.0 (Ubuntu)
Date: Mon, 20 May 2019 15:11:54 GMT
Content-Type: text/html
Content-Length: 194
Connection: keep-alive
Location: https://www.cryptome.fr//locomotive/sign_in
```

I also noticed an error with the CSRF token.

**Comment by EBII** [comment]
Yes you right ! thanks ! 
it is nginx http => https redirection trouble

**Comment by did** [comment]
You're welcome :-)
