### ISSUE TITLE
Add alias `defaults` for key `default` in Section JSON definition

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1315]
I could not figure out what the problem was turns out I was using `defaults` intead of `default` I would say both are equally valid. Can we add the alias for `defaults`

**Comment by westonganger** [comment]
Oh I see that it has been renamed to `global_content` already.

**Comment by did** [comment]
yeah, as you suggested it :-) `global_content` and `default` will work.

**Comment by westonganger** [comment]
I dont think the `global_content` is a good key, maybe `default_attributes` would be the preffered key. 

I actually dont mind `default`, however its easy to miswrite as `defaults` so I would enjoy this alias if only to save a massive headache debugging.
