### ISSUE TITLE
Why use JSON instead of YAML for Section definition?

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1321]
Is there a reason why we are using JSON instead of YAML for the sections definition? This feels a little jarring, considering YAML is used for everything else.

**Comment by manuchap** [comment]
You forgot to edit the 'not' in the question 😁.
As a followup, I'd rather have JSON everywhere since the new sync command produces that and it's relevant/consistent with mongo.

**Comment by westonganger** [comment]
I think the reason for JSON is that there is a better abstraction between Arrays and Hashes/Objects. Whereas in YAML it can be hard to differentiate what data type is what.

My main problem with JSON is having to use string keys gets me (ie. `"label": "foobar"`). Sometimes I accidentally write `label: "foobar"` and everything blows up and I go down a debugging rabbit hole.

Could we possibly also support quoteless keys in our JSON for simple developer ease. Ex.

```
{
  name: "Foobar",
  class: "my-class",
  settings: {
    label: "Title",
    id: "title",
    type: "string"
  }
}
```

This should be totally possible since we are completely in charge of parsing the JSON.

**Comment by westonganger** [comment]
We can just use HJSON.

https://hjson.org/

JSON Add-Ons:

- Trailing Commas
- Comments (`#`, `//`, `/* */`)
- Quoteless Keys
- Quoteless String (meh but okay why not)
- Write multiline strings with proper whitespace handling.

Thats all it does. Seems like the perfect solution to me.

**Comment by westonganger** [comment]
Could be just as simple as changing these three load statements methods in `steam`

https://github.com/locomotivecms/steam/search?q=MultiJson&unscoped_q=MultiJson

**Comment by westonganger** [comment]
Maybe we could avoid this whole HJSON support if section definitions supported both YAML and JSON

**Comment by did** [comment]
@westonganger I like your suggestion! let me see if I can add it for v4.

**Comment by did** [comment]
@westonganger @DonKoko @manuchap @thibaultrey  
quick question, if we allow both json and yaml to describe a section, what would the default format be?

**Comment by westonganger** [comment]
Everything else is YAML so I would say that should be the default.

**Comment by DonKoko** [comment]
I really got used to the JSON but I agree with @westonganger that YAML would be more consistent with the rest.

**Comment by did** [comment]
@DonKoko @westonganger next steps:
- [ ]modify the section generator in Wagon (YAML by default). This is great because I'm going to put comments in the header! (this is something I was missing before)
- [ ] update the documentation about sections (replace JSON examples)

**Comment by did** [comment]
thanks again @westonganger. YAML is definitively the best choice. So simple to read and write compared to JSON. Besides, thanks to the **Liquid HTML** ST3 plugin, I've got the perfect code highlighting to read liquid pages.

**Comment by DonKoko** [comment]
I think its great that we have both options. I have to disagree that YAML is better when it comes to complex data structures, as for a person who never user YAML, its super confusing how do you manage arrays and objects, and with JSON it follows the conventions that we all know and love, arrays with [] and objects with {}. This can make it very confusing to debug, especially considering how dependent it is on indentation. I personally would not use it, but again, i think its a good option to have.

**Comment by manuchap** [comment]
I'm like 50/50 on this. Maybe 51/49 towards json since js devs and apis use it a lot and it fits well with wagon sync and mongo which I hope will never be replaced with potgresql 😅
