### ISSUE TITLE
Section Javascript Events Documentation inconsistent for block events

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1322]
Documentation seems to be inconsistent for block events: https://doc.locomotivecms.com/v4.0/docs/events#section-block-events

The table lists events:
- `locomotive::block::select`
- `locomotive::block::unselect` (section manager seems to use `deselect` instead of `unselect`, this should stay consistent `locomotive::block::deselect`, also Section Manager `blockDeSelect` has awkward capitalization, should be renamed to `blockDeselect`)

The example shows:
- `locomotive::block::load`

What exactly is the full list of block events?

**Comment by did** [comment]
documentation cleaned. thanks!
