### ISSUE TITLE
Documentation for `block.locomotive_attributes`

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1325]
We should have some more documentation regarding `block.locomotive_attributes`. Currently its unknown as to what it does.

From the docs: https://doc.locomotivecms.com/v4.0/docs/liquid-template#section-blocks

```
Wrap the block within a tag

To get the smoothest editing experience in the LocomotiveCMS back-office, we strongly recommend to wrap the block within a tag like this:

<TAG ... {{ block.locomotive_attributes }}>

where TAG can be any HTML5 tag.
```

Specifically I require more explanation about this statement: 
```
To get the smoothest editing experience in the LocomotiveCMS back-office
```

Also this documentation should probably be displayed more prominently.

**Comment by did** [comment]
Done! https://doc.locomotivecms.com/v4.0/docs/liquid-template#section-blocks
