### ISSUE TITLE
link_to and path_to not working

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1328]
Both `link_to` and `path_to` seem to not be working. In the following example the href attribute is output as an empty string.

```
<div class="container text-center">
  <h1 class="text-underline mt-5 mb-4">Website Templates</h1>
  {% with_scope depth: 1, listed: true %}
    {% for p in site.pages %}
      <div class="mt-2">
        <a class="btn" href="{{ path_to p }}">{{ p.title }}</a>
      </div>
    {% endfor %}
  {% endwith_scope %}
  <div class="mt-5"></div>
</div>
```

Can you please point me in the right direction?

**Comment by DonKoko** [comment]
You are using the wrong syntax. The correct syntax is `{% path_to p %}` and `{% link_to p %}`.
https://doc.locomotivecms.com/docs/tags#section-path_to

**Comment by westonganger** [comment]
Thanks @DonKoko that was totally my issue.
