### ISSUE TITLE
Preview fails to work when "Redirect to first domain" is turned on

### ISSUE THREAD

**Issue by louis77** [locomotivecms/engine#1366]
Preview fails to work when "Redirect to first domain" is turned on and Loco UI is not accessed with the primary domain, because the page that is loaded by the preview pane returns a `301` redirect to the primary domain. 

This behaviour should be overridden by the preview pane, i.e. passing an internal query parameter or header to the engine to turn the redirect off or something.

**Comment by did** [comment]
@louis77, on our hosting platform, the locomotive UI is only accessible through the *main* locomotive domain (ie station.locomotive.works) and never through the domain name of the site.
I believe we force it by default.
