### ISSUE TITLE
Sections URL picker produces error if Model is selected but no instance of the model

### ISSUE THREAD

**Issue by dotsi** [locomotivecms/engine#1368]
To reproduce:

1.  open a section with an URL picker in the CMS
2. select Model
3. select Content type under WHICH MODEL?
4. Click the chevron on top to go back to the section

This produces an error: TypeError: Cannot read property '0' of undefined
If the user presses save instead of back the section is lost and needs to be deleted from the database.

**Comment by did** [comment]
thanks @dotsi  for the bug report

**Comment by dotsi** [comment]
> thanks @dotsi for the bug report

So happy you are back! Thanks!
