### ISSUE TITLE
Stuck waiting for preview pane to load

### ISSUE THREAD

**Issue by dyerc** [locomotivecms/engine#1371]
There were no JS errors logged in the console and I could see by inspecting the iframe that the page had in fact correctly loaded behind the scenes.

After debugging various things, what caused the issue for me was the "Redirect to first domain" setting. I wasn't accessing the engine at the URL of the site I was editing. The new JS editor must not be able to handle this type of event loop.

I'm not sure what's the best way to prevent this error. Perhaps forcing editing through the first domain of the site, or ignoring the redirect when pages are rendered in editing mode.

**Comment by did** [comment]
thanks @dyerc for reporting it! 
I set up a 20s timeout before displaying an error message at the center of the screen. Besides, I decided to show the sidebar (with all the sections) although the changes won't appear.
