### ISSUE TITLE
Rails 6 Support

### ISSUE THREAD

**Issue by kevinrood** [locomotivecms/engine#1378]
Hello! 👋 

First off, thanks for providing this incredible software!

Are there plans to provide support for Rails 6?

**Comment by dahogenelst** [comment]
Some OS's have scheduled to retract support for 5.2 in the foreseeable future. @did any updates on this issue? 5.2 is getting a bit stale at this point in time.

**Comment by dahogenelst** [comment]
@did any updates on this issue? We're currently using loco for our corporate website but maintenance-wise it's getting beyond stale at this point. What issues are preventing this update? Can I provide PR's to accommodate the transition?

**Comment by dahogenelst** [comment]
I got in touch with Didier over email to ask about a future Rails update and it is something that is they're plan on doing in the future. Thought I'd update this issue since I've recently heard about their intentions.

**Comment by did** [comment]
hey all 👋

I'm super happy and relieved to announce that we can now close this issue 🎉

The master branch contains my work on upgrading Locomotive to Rails 7 and Ruby 3 (< 3.2). It was a gigantic work and I do hope that I didn't break any stuff. 
My staging platform of Locomotive is already running the 4.3 version. FYI, the demo site that you can test on the locomotivecms.com is hosted on my staging platform.
Next step is to update my hosting platform.

If everything goes well, then I'll officially release the 4.3 version on Rubygems.

Btw, there will be a 4.2 version (check out the v4.2.x branch) which is based on Rails 5, Ruby 2.7 and Mongoid 7 so it's like the 4.1 one but with the support of MongoDB 6.

thanks!
