### ISSUE TITLE
404 with just edited and saved page

### ISSUE THREAD

**Issue by larssmit** [locomotivecms/engine#306]
I get an 404 error on a page which was just edited and saved. The page was just working before the edit. See http://www.besturenmeteenvisie.nl/overons. Can anyone help me?

**Comment by justmark** [comment]
This is happening to us as well.  We have a lot of content in the system, and everything works fine.  Now new pages are showing the contents of the 404 page in the editor.  

Running:

 bundle exec wagon generate page some_page_name

Generates the proper HAML page, and if we leave it as is, and push to production, we see the page listed, but when trying to access it via the browser, or editor, results in a 404 error.
