### ISSUE TITLE
WARNING: Can't verify CSRF token authenticity when submiting a form from a template

### ISSUE THREAD

**Issue by miskander** [locomotivecms/engine#382]
Currently there is no way to add a CSRF token to a form created in a template. So when submitting a form from the public side, say a search form, it will log you out on the backend. It would be nice have some way to add a CSRF token to a form inside of a template. Or is there a better way to add a search form to a page?

**Comment by lcx** [comment]
for anyone getting here, new links are: 
http://doc.locomotivecms.com/references/api/tags/csrf-meta 
http://doc.locomotivecms.com/references/api/tags/csrf-param
