### ISSUE TITLE
edit models in place

### ISSUE THREAD

**Issue by fringd** [locomotivecms/engine#422]
It would be awesome if there was some way to edit model data in place

i.e.

```
<ul>
{%for project in contents.projects %}
<li>
   <span class=title>{% inplace 'project.title' %}</span>
   <span class=size>{% inplace 'project.size' %}</span>
</li>
{% endfor %}
</ul>
```

the expected behavior would be that the in place editor highlights this data, and any changes to it are saved back to the specific project. Does anybody else like this idea? Does this sound possible?

**Comment by did** [comment]
Now that we've got sections (https://doc.locomotivecms.com/v4.0/docs/section-introduction) which offers a much better in-place editing, it would become easier to have this kind of feature. 
It's just that I'm concerned about the complexity of several content types which may make the in-place UI difficult to use (if we keep the sections UI). 
My point is that we might not use a content type for very simple cases and use a section with blocks instead. And if the content type is too complex, it's better to edit it in a full width form.
So I'm closing it for now.
