### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by greeneca** [locomotivecms/engine#442]
The Tiny  MCE editor is embedding an attribute in anchor tags in editable_long_text that prevents the html form being validated.

Here is the validation error:

 Line 195, Column 683: there is no attribute "data-mce-href"
…p://iacadia.acadiau.ca" data-mce-href="http://iacadia.acadiau.ca">iacadia.acad…

You have used the attribute named above in your document, but the document type you are using does not support that attribute for this element. This error is often caused by incorrect use of the "Strict" document type with a document that uses frames (e.g. you must use the "Transitional" document type to get the "target" attribute), or by using vendor proprietary extensions such as "marginheight" (this is usually fixed by using CSS to achieve the desired effect instead).

This error may also result if the element itself is not supported in the document type you are using, as an undefined element will have no supported attributes; in this case, see the element-undefined error message for further information.

How to fix: check the spelling and case of the element and attribute, (Remember XHTML is all lower-case) and/or check that they are both allowed in the chosen document type, and/or use CSS instead of this attribute. If you received this error when using the <embed> element to incorporate flash media in a Web page, see the FAQ item on valid flash.

**Comment by did** [comment]
we dropped TinyMCE in v3 and it got replaced by http://wysihtml.com instead.
