### ISSUE TITLE
Feature request : localized templates

### ISSUE THREAD

**Issue by gabrielnau** [locomotivecms/engine#483]
Hello,

Translations in Locomotive works very well.
Still, there is one thing which could save a lot of time, it's having the ability to define weither all the locales share the same template or not.

For now, we have to duplicate the template across every locale. If there is only one template, then you just have to translate custom fields and custom entries.

I imagine there is some cases were a different template is required for each locale, that's why I think giving the choice would be a great compromise ?

This was discussed here : https://groups.google.com/d/topic/locomotivecms/FHOPBdrjrW4/discussion

Thanks,

Gabriel

**Comment by robomc** [comment]
Not sure why this was closed - a different template is still required for each locale isn't it?
