### ISSUE TITLE
Dev / Prod workflow

### ISSUE THREAD

**Issue by jacklin10** [locomotivecms/engine#517]
I'm struggling with the best way to keep a local development copy of my site while the designer works on the production version.

For example the designer has added several pages and other assets to the production version and they are having a problem.

I want to basically have the production version on my machine.

I'm hosting with heroku and using aws for images / css / etc as recommended.

I can backup the mongo db from prod and restore to my local version, but I won't have the images and the styles from prod.  

Is the recommended solution at this time to download my aws bucket and cram that in my local file system?

And if that is the solution, and I then add images or change a style locally I need to copy those to aws manually or production won't have them.

Unless I'm missing something, which is likely because I'm just learning the system, this workflow 
is awkward.  ( Especially because it looks like downloading the entire bucket from aws isn't done easily ).

Can anyone share their best practices for this type of situation?

Also what are the plans down the road for this process.  I've read in the docs that the 1.0 version had an import / export that seems like it would address this problem, so my guess is that's probably on the list somewhere for the 2.0 version.

**Comment by did** [comment]
in V3, a site gets created from Wagon only. I will add a guide about the ideal workflow later.
