### ISSUE TITLE
Feature request: Page as content_type

### ISSUE THREAD

**Issue by Geeza** [locomotivecms/engine#532]
`Page` isn't a `content_type`, but it functions as a _special_ model within the CMS. 

It would be sweet if  `Page` would be selectable in the `belongs to`, `has many` and `many to many` of content types. 

This opens up a lot of additional functionality like:
- Reusable links (much like Wordpress does)
- Content blocks assignable to pages

**Comment by m43nu** [comment]
Any progress on this feature? Or is there a simple workaround?

**Comment by did** [comment]
We've got sections now and it solves a lot of problems we were facing with LocomotiveCMS.
https://doc.locomotivecms.com/v4.0/docs/section-introduction
