### ISSUE TITLE
cancan controller(s) refactoring

### ISSUE THREAD

**Issue by Papipo** [locomotivecms/engine#536]
In ThemeAssetsController resource instances are loaded through find(), create(), etc, while cancan is already loading them, so we should remove code from the actions themselves.

Apart from that, the load_and_authorize_resource call should use :through => :current_site parameter, and :class parameter might be dropped.

We should also check if this happens elsewhere.

**Comment by did** [comment]
No more CanCan, Pundit is now the new sheriff in town :-)
