### ISSUE TITLE
Memory leak - Heroku?

### ISSUE THREAD

**Issue by nathandonaldson** [locomotivecms/engine#666]
We are seeing our app start at about 125 mb and steadily rise over a number of page views until it hits around 550mb and Heroku kills it. 

Has anyone else seen this? 

We have the following add-ons installed: MongoHQ, New Relic and Send Grid

Rails: 3.2.13
Locomotive 2.0.3
Thin

**Comment by did** [comment]
Hope it's not a problem anymore with v3. We could check it once we'll upgrade Mongoid to 5.0. The whole explanation here: locomotivecms/heroku-instant-deploy#4
