### ISSUE TITLE
Feature Request: Translation should work like I18n (and should fall back on I18n)

### ISSUE THREAD

**Issue by widescape** [locomotivecms/engine#685]
The translation filter currently only uses keys stored in the database and does not fallback to locales defined in Rails config/locales/. 

It would be great if a developer could provide basic translations via config/locales which an admin may then customize via Locomotive translations.

This would also suggest, that Locomotive translations would be as powerful as I18n translations (using parameters, count switches etc.).

I already created such behavior as a Liquid filter, but that was from before the new translations were implemented:

```
# Usage:
#
# {{ 'locomotive.locales.en' | t }}
# => Englisch
# {{ 'products.index.title' | t: ':count', products.count, ':locale', 'de' }}
# => 4 Produkte
#
def translate(input, *args)
  options = { locale: I18n.locale }
  args.each_with_index do |arg, index|
    if arg.is_a?(String) and arg.match(/^\:/) and args[index+1].is_a?(String) and !args[index+1].match(/^\:/)
      options[arg.gsub(':','').to_sym] = args[index+1]
    end
  end
  I18n.t(input, options)
end
```

**Comment by did** [comment]
implemented here https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/services/translator_service.rb#L34

**Comment by Papipo** [comment]
😱

**Comment by did** [comment]
@Papipo, yeah, right? 6 years ago!
