### ISSUE TITLE
Problem when trying to update an entry with an image

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#738]
Scenario:
 - I have an entry with many fields ( a few of each of these: simple input, text, date, file, many to many and belongs to )

 - I added a new field "File" in order to add extra images to this entries

Problem:

 - I try upload an image to this entry but the saving process fails ( kinda silently ).

Some information i got from the "preview" tab inside of the "network" tab of Developers Tools on chrome:

NoMethodError in Locomotive::ContentEntriesController#update

undefined method `__bson_dump__' for Fri, 28 Jun 2013:Date
Rails.root: /Users/hems/workspace/git/hires/engine/beauty

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"xhr"=>"true", "content_locale"=>"en", "content_entry"=>{"_slug"=>"david-bianca-and-light-blue", "_visible"=>"true", "title"=>"David, Bianca and Light Blue", "text_1"=>"Some Text Here", "formatted_date"=>"06/28/2013", "text_2"=>"More Text Here...", "summary"=>"summary", "intro_text"=>"intro", "thumbnail"=>#<ActionDispatch::Http::UploadedFile:0x007fbb0c9bb7d8 @original_filename="Screen_Shot_2013-05-20_at_11.03.17.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"content_entry[thumbnail]\"; filename=\"Screen_Shot_2013-05-20_at_11.03.17.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<File:/var/folders/0r/hj6blw1j6_j5dt8cdks8mkdc0000gp/T/RackMultipart20130704-12218-fyayou>>, "tag_ids"=>[], "make_up_news_push_ids"=>[]}, "slug"=>"articles", "id"=>"519b5b550bf29190fc000024"}

Response:

Headers:

None

**Comment by did** [comment]
I don't have this issue in v3.
