### ISSUE TITLE
creating a custom liquid tag with inline output and a yield sideeffect in the html header

### ISSUE THREAD

**Issue by silvermind** [locomotivecms/engine#741]
dear all

i'm trying to write a custom liquid tag to allow easy implementation of Google Dart For Publisher Tags. https://www.google.com/dfp

I want to place my custom ad_slot tag somewhere in the body content:
```html
<body>
{% ad_slot "300x250", "SlotID" %}
...
</body>
```

Then I need two different outputs to happen:

the easier one is the ad_slot inline html output, which is already working as it should. 
```html
<body>
<div id="SlotID" style="width:300px;height:250px;"></div>
// plus some asynch javascript loader using the SlotID
</body>
```

the other output which i have problem is, the sideeffect which is required to go in the HTML head. 
The idea here is that each tag should store it's slotID in a collection as a sideeffect, which is then rendered in the header. (I've already solved this problem in a rails app using content_for in the ad_slot helper, which is den yield in the header code)
```html
<head>
// basic google dart for publisher code (only rendered if at least one ad_slot is present)
// plus 1 line of javascript preparing each of the ad_slots defined as tags.
</head>
```

The main problem, is that the output in the header is before the ad_slot tags in the body. It would be quite easy to render the loader output in the footer, but google want it to be placed in the html head.

Do you have any ideas how to solve this using the liquid tags correct lifecycle?

**Comment by did** [comment]
As far as I understand the whole thing, you'll need two liquid tags: one going in the header, the one to display the ad.
