### ISSUE TITLE
Link_to : how to add attributes in the <a> tag?

### ISSUE THREAD

**Issue by jloosfelt** [locomotivecms/engine#743]
The #507 deals with the new link_to tag, but how do you add extra attributes in the <a> tag?
A syntax could be to add any attribute on the tag:

    {% link_to mypage, class: 'active' %}

But I think this would have some limits.

Any thoughts ?

**Comment by did** [comment]
solution: using the **path_to** liquid tag (link_to is built on top of that). Example:

````
<a href="{% path_to about_us %}" ....>Hello world</a>
````
