### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by benhutton** [locomotivecms/engine#746]
Hey @did,

Any estimate on when we can expect to see Rails 4 support?

-Ben

**Comment by zepplock** [comment]
Still no rails 4 support?

**Comment by RaviAsnani** [comment]
+1

**Comment by dimanyc** [comment]
+1

**Comment by mariusz** [comment]
June 2013: Rails support by the end of the year
May 2015: Still no Rails support. Moving on.

**Comment by did** [comment]
hi @mariusz, 

Your comment is both harsh and wrong (and today is not my day, sorry).

First, look at the activity of the project and the other related ones too (Steam, Coal, Wagon).There is at least one commit a day! 
Moreover, if you had read the [README](https://github.com/locomotivecms/engine/blob/master/README.md) file of Locomotive, you'd have noticed that I put a link to a Trello. Inside this [Trello board](https://trello.com/b/kRiy1dZu/locomotive-v3), you'd have also seen that our alpha version of Locomotive v3 already runs with Rails 4 and that we've accomplished a lot.

Finally, open source works in the both way, meaning contributions are welcome. 

So, if you want Locomotive v3 to be out sooner, well, ... you know what to do :-)

**Comment by benhutton** [comment]
Hey @did, thanks for all your hard work on Locomotive and the v3 upgrade... we really appreciate it and are looking forward to it!

**Comment by jimzar** [comment]
+1 to @benhutton! Keep rocking guys :-)

**Comment by did** [comment]
thanks @jimzar and @benhutton for you support! I know I'm not very good at delivering at the right time but we're going to make it for sure.

**Comment by rvalyi** [comment]
kudos for the hard work on Locomotive 3 @did
At Akretion we are slowly but steadily working to make it possible to have an open source Locomotive powered e-commerce with Odoo as a backend. Stay tuned.

**Comment by mikeyhew** [comment]
You should close this if rails 4 is supported.

**Comment by mariusz** [comment]
@mikeyhew it still isn't.

**Comment by mikeyhew** [comment]
@mariusz I thought you were moving on?

>Inside this Trello board, you'd have also seen that our alpha version of Locomotive v3 already runs with Rails 4 and that we've accomplished a lot.

I looked at the trello board and it says that the task "Upgrade to Rails 4" is done. I haven't been able to get it working (see #1047) but if it's done, then this issue has been dealt with.

**Comment by did** [comment]
v3 beta.1 has been released and it uses the last version of Rails (4.2.4).
