### ISSUE TITLE
Feature: greater flexibility with nav snippet

### ISSUE THREAD

**Issue by HashNotAdam** [locomotivecms/engine#750]
Currently a snippet used with the nav tag is only able to modify the text of the menu link which makes it highly inflexible.

Twitter Bootstrap helps you [add dividers between menu items](http://twitter.github.io/bootstrap/components.html#navbar) by using an extra list item like:
```html
<nav id="nav">
    <ul>
        <li><a href="/">Home</a></li>
        <li class="divider-vertical"></li>
        <li><a href="/foo">Foo</a></li>
    </ul>
</nav>
```
If the snippet was generating the whole list item, using liquid helpers for items such as the ID on the li (which currently is fantastic), these kinds of deployments would become possible without having to manually build the nav.

**Comment by did** [comment]
the nav tag takes a snippet in the last versions of Locomotive
