### ISSUE TITLE
Feature Request: "Redirect Here From" field on Locomotive::Page

### ISSUE THREAD

**Issue by benhutton** [locomotivecms/engine#751]
Hey @did,

I'm working on sites in Locomotive that replace old sites. The URLs are completely changing.

I want a clean way to link an old url with the new page. I don't think using the current page redirect function is even viable - I want to redirect from urls like "index.php?id=123"

What do you think about the following?

1.) Every page has an array of "redirect_here_from_urls" (entered into a textarea in the backend, one per line)
2.) We augment the routing code to query on that field as well. This would involve rewriting the Render.locomotive_page method (https://github.com/locomotivecms/engine/blob/master/lib/locomotive/render.rb#L103-L110), or perhaps something farther up the stack.
3.) If there's a hit, trigger a 301 redirect (or make it configurable 301/302) TO the page that was returned

As always, I'd be happy to implement if this is a desirable feature.

-Ben

**Comment by did** [comment]
The UI speaks for itself :-) 
<img width="670" alt="screen shot 2015-10-22 at 11 16 03 pm" src="https://cloud.githubusercontent.com/assets/8065/10680423/ef1b2712-791f-11e5-9de0-7eda367847ff.png">

**Comment by allanbreyes** [comment]
Very nice! :+1: love it.

**Comment by benhutton** [comment]
@did magical :)
