### ISSUE TITLE
Multiple jQuery issue

### ISSUE THREAD

**Issue by HashNotAdam** [locomotivecms/engine#752]
Since the 2.2.x releases, I am finding that the inline editor is not working.

I have tracked this down to 2 copies of jQuery being loaded in the page frame. In total, there are actually 3 completely different copies of jQuery per admin load:
1) v1.8.3 is loaded from /assets/jquery.js in the outer frame;
2) v1.7.2 is loaded from /assets/aloha/lib/vendor/jquery-1.7.2.js in the page frame; and
3) v1.7.2 is also minified inside /assets/locomotive/aloha.js in the page frame.

On top of this, if there is jQuery in the site template, a fourth copy is brought in.

Looking only at the page iFrame, the first version of jQuery is loaded; then Aloha adds the function extendedObjects to jQuery; then the next version of jQuery loads, taking over the jQuery and $ variables which essentially wipes out extendedObjects; finally Aloha tries to call $.extendedObjects but, of course, $ is no longer a reference to the jQuery containing that function.

**Comment by did** [comment]
in V3, no more AlohaEditor, no more TinyMCE, no more different versions of jQuery :-)
