### ISSUE TITLE
with_scope resets control fields

### ISSUE THREAD

**Issue by HashNotAdam** [locomotivecms/engine#753]
**Tested on v2.2.1**

Adding a with_scope tag to a page that checks the value of an editable control field causes the control field to lose its value.
## Steps to reproduce

Index page: no custom fields
Page 2: extends index page

Page 2 has the following field added at the end of the file (ie. not in a block):

```
{% editable_control "featured_on_home", options: 'false=No,1=Position 1,2=Position 2,3=Position 3', hint: "Will this page be shown in one of the feature spots on the home page? If so, which in which position", priority: 1 %}
false
{% endeditable_control %}
```

Go to page 2 in the back office, set featured_on_home to 'Position 1'

Index page tries to search for pages with a feature position using:

```
{% with_scope featured_on_home.gte: 0 %}
{% assign featured = site.pages %}
{% endwith_scope %}
{{ featured.size }}
```

Upon saving the index page, featured_on_home will now be set to No.

Go to page 2 in the back office, set featured_on_home to 'Position 1'

Save the index page again.
featured_on_home is still correctly set to 'Position 1'
Change:

```
{% with_scope featured_on_home.gte: 0 %}
```

To:

```
{% with_scope featured_on_home.gte: 1 %}
```

Save the index page

featured_on_home will be set to No again.

**Comment by did** [comment]
editable_controls become deprecated with v4. Sections are now the new way to go. More details [here](https://doc.locomotivecms.com/v4.0/docs/section-introduction)
