### ISSUE TITLE
items in "many to many" relationship are not clickable when visualising entry

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#755]
When listing items on the content entry page ( for instance when you have many to many ) the item title on the list doesn't link to to the entry itself.

So if you want to jump to that related entry you will have to do it "by hand".

That also brings a problem, which is if the user is updating some information and then click he might loose the edition if doesn't save before click the entry.

So ideally we would:
1. Let the user know when he will leave the page without saving the entry
2. Make the title of the related entries a link to the entry itself
   ![screen shot 2013-07-17 at 20 35 29](https://f.cloud.github.com/assets/27327/814526/12a849a6-ef18-11e2-81b7-6459d7184909.png)

**Comment by did** [comment]
related to the old UI
