### ISSUE TITLE
Feature: remove empty lines from HTML

### ISSUE THREAD

**Issue by HashNotAdam** [locomotivecms/engine#756]
It would be nice if the empty lines could be removed from HTML before it is sent to the browser.

Apart from any sections where we have used new lines to make the liquid logic more legible, we are also using a snippet before the opening html tag that does nothing more than assign variables so every page now has many empty lines before the first real content.

**Comment by did** [comment]
https://www.schneems.com/2017/11/08/80-smaller-rails-footprint-with-rack-deflate/ 
https://www.reddit.com/r/ruby/comments/7bm6fu/80_smaller_rails_page_size_with_rack_deflate/
