### ISSUE TITLE
Feature Request: editable_linkto with backoffice ui

### ISSUE THREAD

**Issue by jasongonzales23** [locomotivecms/engine#795]
This might just be a custom liquid tag. But here is the idea I've had:

A list of links would default to the list of site pages, but content editors could add to that list of links, the use case being complex outside links. For example I have more than one client who needs to be able to link throughout their site to other services (like constant contact and an appointment service). 

The interface for adding links (Link Manager?) could look kind of like this:

Site links:
-index
-home
-about
(and so on)

Add a new link
href = 
title = (optional)
target = (optional)
class = (optional)

Then, much like the editable_control, a web developer or designer could place a tag that might look like this:

{% editable_linkto 'feature 1 image link' %}{% endeditable_linkto %}

Then each time this is placed into a page, the content editor just gets a select menu of the links edited in the 'Link Manager'.

**Comment by did** [comment]
Problem solved with the sections and the url type setting (https://doc.locomotivecms.com/v4.0/docs/json-definition#section-setting-types)
