### ISSUE TITLE
Custom "rss2" tag based on "consume" tag

### ISSUE THREAD

**Issue by TheDahv** [locomotivecms/engine#800]
We ran across this on the project I'm working on. A site may need to syndicate blog content from a different platform. The consume tag is incredible and almost does what we want it to, except most blog engines expose their content feeds in RSS and the way "`consume`" parses RSS2 XML feeds doesn't work.

XML exposes its feed items as "item" tags nested within a "channel" tag (see [startupweekend.org/blog/feed](http://startupweekend.org/blog/feed/) as an example.

When Ruby serializes the HTTP response, the "`item`" key gets overwritten every time and the client is only left with one RSS feed item.

I propose creating a new "`rss2`" tag based of the "`consume`" tag. The only part that needs to get overridden is how Ruby deserializes the items content and jams them into an array instead of overwriting the key.

I'll be working on this in another fork since I want to pursue this direction for my own project.

Thoughts? Concerns?

**Comment by did** [comment]
The rss2 liquid tag should be developed for the Steam gem: https://github.com/locomotivecms/steam.
