### ISSUE TITLE
local_path => is already taken pushing images from wagon

### ISSUE THREAD

**Issue by miletbaker** [locomotivecms/engine#824]
Hi, 

I am having an issue pushing image assets from wagon.  When trying to push images that contain either ```@2x``` in their filename, they upload fine on the first push but then on subsequent pushes the command line returns ```local_path => is already taken``` for these assets. I've also noticed the same issue if I create an additional folder in public that contains images, all of these return the same error.

I am assuming the logic for this is in the engine rather than Wagon itself, and wagon is just reporting the error back from the engine? If not I can reopen an issue on that repo.

Thanks.

**Comment by neversion** [comment]
locomotive_cms(2.5.7) + locomotive_wagon(1.5.7) still got the error.

**Comment by did** [comment]
@neversion that's annoying. what's the local path of the failed file?

**Comment by neversion** [comment]
Once I there is file in directory expect fonts/images/javascripts/stylesheets/samples, I will got the error. In my case, it's plugins directory. Once I move plugins into javascripts, the error gone.
![2015-10-07 1 59 55](https://cloud.githubusercontent.com/assets/3972614/10330125/cddebc74-6cfb-11e5-84df-b3675d9fd6b1.png)

**Comment by did** [comment]
@neversion are u using v3? If so, could you test with the last git commits of both Engine, Steam and Wagon please? thanks!

**Comment by did** [comment]
Alright, I was able to deploy/push images containing the "@2x" string with the last versions of Wagon/Engine. So, I'm closing the issue for now. If there are other failed cases, please re-open the issue.

**Comment by neversion** [comment]
@did sorry, I am using locomotive_cms(2.5.7) + locomotive_wagon(1.5.7).
