### ISSUE TITLE
Locomotive elements

### ISSUE THREAD

**Issue by stephenson** [locomotivecms/engine#835]
Locomotive is already a fantastic CMS, but it missis one big thing. For me a CMS needs to give power, not only to the developer, but also to the content managers.

Today if you wish to build a new page on your locomotive powered website you need basic HTML knowledge. I would like to introduce Elements\* as a part of Locomotive.

What is a element?
A element is basically a snippet with editable content, files etc. But the difference from snippets is how they are used.

In the admin panel of a page you get a interface to add elements to blocks. Reorder them and fill content in.

I this way the developer can build a set of elements that the content manager can use to build pages without help from the developer.

Features of elements:
- A content manager can add the same element many times to the same page
- A element can have editable content/files
- Elements will be added to blocks, you can add elements to all the blocks of the pages template

I tried to frame the parts on our website that would be elements (https://www.firmafon.dk/omstilling/ ):

![billig_mobil_omstilling_-_89_kr _inkl _fri_viderestilling-14](https://f.cloud.github.com/assets/60150/1529938/11350a46-4c42-11e3-920c-8013c9fe65f9.png)

All the content on the screenshot is editable. Look closely and you can see that feature_image_right is used more then ones.

This is just a concept, if you like it i would love to use some more time to mock up the backend design.

What do you think of the idear?

*"Elements" is just a made up feature name

**Comment by dennisvdvliet** [comment]
@did Any plans for a timeline for v4? A feature like this would be very welcome for a project I'm currently working on. Would be happy to contribute if possible. So if you can share what your ideas where with React I might be able to help get this feature of the ground.

**Comment by did** [comment]
@dennisvdvliet sure, we can talk about it in Gitter: https://gitter.im/locomotivecms/v3?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by did** [comment]
locomotive sections at the rescue! https://doc.locomotivecms.com/v4.0/docs/section-introduction

**Comment by stephenson** [comment]
Amazing that it was introduced so many years later 👏
