### ISSUE TITLE
Modal js / ajax

### ISSUE THREAD

**Issue by daveed** [locomotivecms/engine#841]
Hi,

I would like to know what is the best practice to display modals in Locomotive?
Hide modal contents in the DOM and display on click?
Is there a way to dynamically load the content of each modal which I know how to do but in Locomotive there is no controller/action where I can point to.

Thanks

**Comment by did** [comment]
Locomotive v3 uses now Bootstrap for the UI/UX which makes easy to add modal, style elements in the back-office.
