### ISSUE TITLE
File inputs inside has many relationship editor are not refreshed

### ISSUE THREAD

**Issue by kkrol89** [locomotivecms/engine#844]
Here is the full scenario to reproduce this error

Given I have following content types:
Topic
 - title:string
 - comments:has_many
Comment
 - title:string
 - content:text
 - file:file

When I create a new Topic with two Comments:
- one with file
- and second without any file.
And I go to the created topic
And I edit first comment in the popup window
And then I edit second comment in the popup window
Then the file input for the second comment is not refreshed

It happens only for the file inputs without any file attached. They contain file of the previously edited content entry.

**Comment by did** [comment]
no more popup in v3 to manage entries of a has_many relationship.
