### ISSUE TITLE
multisite menu / option not show up in menu after enabling multi_sites in config

### ISSUE THREAD

**Issue by rubytastic** [locomotivecms/engine#854]
After enabling multi_sites in config 
( there is also error in config order incorrect of the multi_sites = true line ) there is no menu option to enable a new site.

I was able to read the source and do like 
http://hero.cms.dev:3000/locomotive/sites/new

**Comment by did** [comment]
multi-sites in V3 is straight forward now. need a proof? the multi_sites = true does not exist anymore :-)
