### ISSUE TITLE
How to customize loco engine?

### ISSUE THREAD

**Issue by ewilliam** [locomotivecms/engine#865]
I've looked at mini_app for guidance (https://github.com/locomotivecms/mini_app) but its outdated and I wonder if there's any up to date reference on how to extend the loco engine without having to open up a custom engine?

**Comment by ianmilliken** [comment]
@did I am using v3.1 of the engine and looking to extend it, I've also found the mini_app documentation to be outdated - has there been any progress on the documentation to customise the back-office?

**Comment by did** [comment]
hi @ianmilliken, what do you have in mind?

**Comment by ianmilliken** [comment]
I'd like to integrate an interactive [Mapbox map](https://www.mapbox.com/mapbox-gl-js/examples/) within a content type so that back-office users have a map to customise instead of form fields.

**Comment by did** [comment]
@ianmilliken like to spot a location? so, basically, having a address field type which will come with a map when rendered inside a content entry form in the back-office?

**Comment by ianmilliken** [comment]
@did Yeah that's what I had in mind, though I don't know how feasible it is. I have a work around for the moment which is to use two fields in the back-office form, one each for latitude and longitude, that return values to the content type template - but it's not a good solution for non-technical back-office users. Ideally I'm trying to get the Mapbox geocoder to be accessible from the back-office.

**Comment by did** [comment]
that'd be a nice addition. Is the mapbox geocoder available for everyone? Is there a limit for the number of displayed maps? For instance, you are limited if you use Google's one. 

Anyway, what kind of attributes would we need for that field? Btw, all the types are declared/defined here: https://github.com/locomotivecms/custom_fields. Then, the Locomotive Engine renders the correct form input based on the field type.
