### ISSUE TITLE
bundle exec rails g locomotive:install command

### ISSUE THREAD

**Issue by ilanbiala** [locomotivecms/engine#867]
The command `bundle exec rails g locomotive:install` from http://doc.locomotivecms.com/get-started/install-engine doesn't run properly. The `bundle install` command ran correctly.

![screen shot 2014-01-18 at 6 48 59 pm](https://f.cloud.github.com/assets/3695164/1948573/2280172c-809b-11e3-9605-207b03592e1d.png)

This is my Gemfile:
![screen shot 2014-01-18 at 6 50 00 pm](https://f.cloud.github.com/assets/3695164/1948576/44e09256-809b-11e3-9a67-52fa72e5ad22.png)

**Comment by lakesare** [comment]
having the same issue. running from the root rails folder. `rails s` returns the same results.
