### ISSUE TITLE
Enable gzip compression of CSS and JS

### ISSUE THREAD

**Issue by benhutton** [locomotivecms/engine#886]
Google PageSpeed tells me the following: "Enable compression for the following resources to reduce their transfer size by 498.7KiB (57% reduction)."

That's A LOT of potential reduction.

It would be great to also build in asset minification, far-future expires headers, and asset fingerprinting so that the far-future expiration would make sense (this would allow us to use a CDN with our assets).

**Comment by did** [comment]
I believe the solution would be to use Gulp inside Wagon.

**Comment by did** [comment]
Wagon minifies the js / css files but do not concate them 
Gzip compression is done at the http server level, Nginx or Apache.
All assets are fingerprinted in V3.

**Comment by DonKoko** [comment]
hey @did . I know this is very old but I am looking for a way to enable gzip compression on my engine on Heroku. Do you have any tips on how to approach this?
