### ISSUE TITLE
Nav menu should include content type pages if template is 'listed'

### ISSUE THREAD

**Issue by Dirklectisch** [locomotivecms/engine#888]
The navigation menu generated by the nav tag should include content entries when the content-type-template has its listed property set to true. This is necessary because the only other way to include those menu entries is by using a rather dirty hack within a custom menu-entry snippet. See the discussion on the Google Group here:

https://groups.google.com/forum/#!topic/locomotivecms/pFGmRJ_bY5Q

An example use case would be: showing categories defined by a custom content type in the site's global navigation.

**Comment by did** [comment]
we believe sections and blocks are now more flexible to build nav menus (https://doc.locomotivecms.com/v4.0/docs/section-introduction).
