### ISSUE TITLE
If you mark a "File" as required, then try to create an entry it will return an error "Entry not created"

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#892]
Basically i created a model with,

Simple Input
File
Description

marked all as "required".

Then went to "New entry", but i can't save the new entry since even after i selected an image on the file field locomotive still thinks there's no file selected and give me the

"Entry was not created" Error, looking on the "Network" tab of my Dev Tools, i can see a json being returned:

image: [can't be blank]
0: "can't be blank"

**Comment by did** [comment]
Works fine in V3.
