### ISSUE TITLE
SEO / SOCIAL meta tags improvement

### ISSUE THREAD

**Issue by bricemaurin** [locomotivecms/engine#896]
Your CMS is really powerful, thanks a lot. However, for all sites created using your CMS, we always add the same SEO / SOCIAL meta tags. I think everyone would benefit from having them included in the "main" > "seo" settings.

Everything's not P1, I've added priority to each meta, feel free to ask if you need more information.

Brice

---
#### [P1] rel canonical

Specify the canonical url for this page & avoid duplicate content on your site.

```
<link href='{{ page.url }}' rel='canonical'>
```

Default value should be {{ url }}, but should be editable.
#### [P1] rel author

Specify the author's google+ profile and allow to show the author's face on google results. In most case, this will increase the click through rate on google. Example: [https://www.google.fr/search?q=apple](https://www.google.fr/search?q=apple)

```
<link href='{{ page.g+_author }}' rel='author'>
```

To verify your rel=author, go to the G+ page and add the URL of company’s site to the sites you contibute to. This creates a “reciprocal” link between the two sites and tells Google that it’s the real deal.  

This setting should be set in the user/author page.
#### [P1] rel publisher

Specify the company's google+ official page and allow the description of the company to be shown on the right side f google results. Example: [https://www.google.fr/search?q=comment mesurer son referencement](https://www.google.fr/search?q=comment%20mesurer%20son%20referencement)

```
<link href=”{{ site.g+_publisher }}” rel=publisher />
```

To verify your rel=author, go to the G+ page and add the URL of company’s site to the to verify it. This creates a “reciprocal” link between the two sites and tells Google that it’s the real deal.   

This setting should be set globally for the site.
#### [P1] article:publisher

Specify the facebook page url of the company. It will enhance the display of your post shared on facebook. [More info here](https://developers.facebook.com/docs/reference/opengraph/object-type/article/).

```
<meta property="article:publisher" content="{{ site.fb_publisher }}" />
```

This setting should be set globally for the site.
#### [P2] article:author

Specify the facebook profile of the author's facebook page. It will enhance the display of your post shared on facebook. [More info here](https://developers.facebook.com/docs/reference/opengraph/object-type/article/).

```
<meta property="article:author" content="{{ page.fb_author }}" />
```

This setting should be set in the user/author page.
#### [P2] og:title

Specify the page title used when the page will be shared on opengraph compatible sites (facebook...). More [details about og:title here](http://ogp.me/#metadata).

```
<meta content='{{ page.og_title}}' property='og:title'>
```

The default value for this value should be set to {{ page.seo_title }} but should be editable.
#### [P2] og:description

Specify the page description used when the page will be shared on opengraph compatible sites (facebook...). More [details about og:description here](http://ogp.me/#metadata).

```
<meta content='{{ page.og_description }}' property='og:description'>
```

The default value for this value should be set to {{ page.meta_description }} but should be editable.
#### [P2] og:url

Specify the canonical url for this page. More [details about og:url here](http://ogp.me/#metadata).

```
<meta content='{{ page.url }}' property='og:url'>
```

Default value should be {{ url }}, but should be editable.
#### [P2] og:type

Specify the page type, and changes the way your pages will look like when shared on opengraph compatible sites (facebook...).  

```
<meta content='{{ page.og_type }}' property='og:type'>
```

Possible [og:type values are listed here](http://ogp.me/#types). Most of the time, we'll use one of the 3 main values, but the list is expanding regularly. Ideally, the CMS should let user choose from the following 4 values:
-   website
-   article
-   profile
-   other: please specify (let the user enter its own value)

We should be able to choose the default value for each page template.
#### [P2] og:image

Specify the image used when the page will be shared on opengraph compatible sites (facebook...). More [details about og:image here](http://ogp.me/#structured).

```
<meta content='{{ page.og_image }}' property='og:image'>
```

Image should be squared, 400x400px minimum. We should be able to choose the default value for each page template.  
#### [P1] twitter:site

Specify the twitter account for the company. It will enhance the display of your post shared on twitter.  

```
<meta content='{{ site.tw_publisher }}' name='twitter:site'>
```

This setting should be set globally for the site.
#### [P2] twitter:title

Specify the title of the page to be shared on twitter.  

```
<meta content='' name='twitter:title'>
```

The default value for this value should be set to {{ page.seo_title }} but should be editable.
#### [P2] twitter:description

Specify the page description used when the page will be shared on twitter.

```
<meta content='{{ page.tw_description }}' property='twitter:description'>
```

The default value for this value should be set to {{ page.meta_description }} but should be editable.
#### [P2] twitter:url

Specify the canonical url for this page when shared on twitter.

```
<meta content='{{ page.url }}' property='og:url'>
```

Default value should be {{ url }}, but should be editable.
#### [P1] twitter:card

Specify the way the page should look like when shared on twitter.  

```
<meta content='{{ page.tw_card }}' name='twitter:card'>
```

Possible [twitter:card values are listed here](https://dev.twitter.com/docs/cards). The list may evolve. To avoid complex situations (some twitter cards need large amout of information, and will thus need more developments), the CMS should allow to choose the 2 most common values:
-   summary (default value)
-   photo
-   none: disable the tag. This could be used when you want to include another type (app, gallery, player, product) that requires more in-depth integration.
#### [P2] twitter:image

Specify the image used when the page is shared on twitter.

```
<meta content='{{ page.tw_image }}' name='twitter:image'>
```

Image should be squared, 120x120px minimum: larger / non-squared images will be resized & cropped by twitter. We should be able to choose the default value for each page template.  
#### [P2] twitter:creator

Specify the author's twitter username.

```
<meta property="twitter:creator" content="{{ page.tw_author }}" />
```

This setting should be set in the user/author page.

**Comment by did** [comment]
related to #940
