### ISSUE TITLE
Aloha JS problem

### ISSUE THREAD

**Issue by Hengjie** [locomotivecms/engine#899]
I experience this whenever I go onto a page to edit inline. Could it be that I'm running my own version of jQuery as well?

![screen shot 2014-03-25 at 10 41 02 am](https://f.cloud.github.com/assets/261870/2505772/53e3f718-b39d-11e3-9f7e-bd87547c11c9.png)

**Comment by did** [comment]
No more dependency to Aloha in v3 :-)
