### ISSUE TITLE
Imagemagick options

### ISSUE THREAD

**Issue by MatthieuBarthel** [locomotivecms/engine#925]
When using the "resize" filter, LocomotiveCMS uses Dragonfly + ImageMagick to generate the resized images. By default it will generate quite heavy images, it would be nice to be able to configure some imagemagick options, like "quality" or "strip" (strip the image of any profiles or comments).

I created a thread about it in Google Group : https://groups.google.com/forum/#!topic/locomotivecms/wP0B1ewFNzs

Unfortunately I don't have time to dig into that and I am pretty newbie in LocomotiveCMS.

Thanks :)

**Comment by benhutton** [comment]
We've actually hacked our Locomotive install to do this.... you can put this code in your dragonfly initializer:

    module Locomotive::Dragonfly
      def self.resize_url(source, resize_string)
        if file = fetch_file(source)
          /(?<size>[^q]*)(?:q(?<quality>\d+))?/ =~ resize_string
          transformed_file = file.thumb(size)
          transformed_file = transformed_file.convert("-quality #{quality}") if quality.present?
          transformed_file.url
        else
          Locomotive.log :error, "Unable to resize on the fly: #{source.inspect}"
          return
        end
      end
    end

So 1600x900q75 will give you an image resized to 1600x900 at quality 75%

**Comment by did** [comment]
The resize filter has now more features: https://doc.locomotivecms.com/v4.0/docs/filters#section-options
Plus, we're going to implement this: https://github.com/locomotivecms/engine/issues/1275
