### ISSUE TITLE
Bulk Delete Pages / Assets with wagon push

### ISSUE THREAD

**Issue by brettallred** [locomotivecms/engine#930]
When I build a site with a pre purchased template theme that has lots of pages and assets I push the site using wagon, but as I remove pages and / or assets and continue to push it doesn't remove the deleted assets on the server.

Currently I have to remove them one by one and it is a huge pain.

**Comment by duxan** [comment]
+1

**Comment by jimzar** [comment]
Currently the only solution is to delete them one by one manually in the admin panel ?

**Comment by did** [comment]
I'm working on the Ruby API Client (https://github.com/locomotivecms/coal). I've not finished yet but we could imagine an action like destroy_all which would take care of that. How does it sound?

**Comment by jimzar** [comment]
Will we have to run a seperate command to delete them or will it happen on the background when we run wagon push ? (Sorry if I didn't understand well your answer but I am a more frontend guy)

**Comment by did** [comment]
https://locomotive-v3.readme.io/docs/delete-resources
