### ISSUE TITLE
Item template not used on Backoffice DropDown

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#932]
As you can see on this screenshot:

![screenshot 2014-05-18 21 17 46](https://cloud.githubusercontent.com/assets/27327/3008684/9914ee08-dec9-11e3-9e50-2f61ab87cd7e.png)

The item template is used when listing the items on the backoffice, but not used on the "Select box".

In that case i have a field template as:

{{ entry.date_field | date: "%A, %b %d %Y" }}

**Comment by did** [comment]
the new v3 layout prevents that inconsistency.
