### ISSUE TITLE
Snippet update doesn't trigger the page update

### ISSUE THREAD

**Issue by danielmyasnikov** [locomotivecms/engine#935]
Once you update the snippet that is included in the page, unless a developer updates the pages the changes on the pages (snippet changes) are not taken the place. So at the moment to trigger snippet change, here is the workflow:

=> update snippet content
=> update page (change something, click save)
=> hard reload the page in the browser to that change

**Comment by ziedbargaoui** [comment]
@did It's the same for me, I am using version 2.5.6, and even I tried to assign variable
inside the conditional statement and then use it as a snippet name but it didn't work, looks like
the include tag doesn't work with variables.

**Comment by did** [comment]
@ziedbargaoui what you are trying to achieve does not work in v2.5.x. However, that will work on v3. Want some proof? https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/tags/snippet.rb#L34 :-)
(Steam is the common rendering layer for both Engine and Wagon).

**Comment by ziedbargaoui** [comment]
Thanks V3 looks promising (j'ai hate ) :) But this is for using a variable in the include tag.
What about triggering the page update (the original purpose of this issue)?

**Comment by did** [comment]
in V3, we've simplified a lot the page rendering. No more complex page / snippet dependencies, we just render the page without caching the parsed liquid template. The performance is even a little bit better than now. 
(v3 is really at the corner :-) )
