### ISSUE TITLE
Adding string field to a content type: can't edit the value of the new field for "old" content entries

### ISSUE THREAD

**Issue by reka** [locomotivecms/engine#961]
Starting situation:
my app contained the content type "posts" with some content entries e. g. "Sample 2"
Engine 2.5.4
Wagon 1.4.0

I added a string field to the content type posts
in app/content_types/posts.yml added:

```
 - results_link:
    label: Link zu den Ergebnissen
    type: string
    required: false
    hint: z. B. zu chess-results<br />Das Link wird nach dem Text angezeigt.
    localized: false
```

I pushed the changes to engine:
`bundle exec wagon push dev2`

=>
The new property results_link appeared on the back-office page of the existing post "Sample 2",
BUT
when I edited results_link, and saved the changes, nothing happened. When I reopened the post "Sample 2" in the back-office, the field results_link was empty again.

When I created a new post "Report with results", and filled in the property results_link, it was stored correctly.

According to MongoDB:
The content_entry document of "Sample 2" didn't contain a field results_link, but the document of "Report with results" did.

There was also a difference in custom_fields_recipe.rules:
In the (new) document "Report with results" it contained the field results_link, but in the (old) document "Sample 2" it didn't. It was rather strange, because custom_fields_recipe.name was the same for both documents.

That lead to a workaround: After I added the new field to custom_fields_recipe.rules of the document "Sample 2", I was able to edit results_link of the post in the editor screen.
``` 
var link_field = {
				"name" : "results_link",
				"type" : "string",
				"required" : false,
				"unique" : false,
				"localized" : false
			};
db.locomotive_content_entries.update({title: "Sample 2"},{$push: {"custom_fields_recipe.rules": link_field}})
```
Is this a bug, or did I do sth wrong, as I declared the new field and pushed the changes?

**Comment by did** [comment]
Works fine in V3.
