### ISSUE TITLE
csv export flaws

### ISSUE THREAD

**Issue by manuchap** [locomotivecms/engine#963]
I upgraded to 2.5.2 to benefit the "export empty fields" fix (that is empty fields are exported as a pair of quotes).
I noticed that if the empty field is a **belongs_to** field then nothing is exported, hence resulting in data offset in the csv file.

It also took me a while to figure out how to properly import the csv into excel for mac. Since I'm french (yeah bad luck strikes randomly) I use accented characters. The only way (other than importing/exporting to google docs) is to open the csv file first in sublime and save it with encoding **UTF-16 LE with BOM** prior to importing it into excel, although this might have to do with my server config...

**Comment by did** [comment]
@manuchap I don't have the problem in v3 with the phone numbers. They get exported correctly.
