### ISSUE TITLE
Inline editor doesn't work for escaped captured editable_text

### ISSUE THREAD

**Issue by mayhewluke** [locomotivecms/engine#968]
Steps to reproduce:

- Place an `editable_text` tag inside a `capture` tag, like so:
```liquid
{% capture caption %}
  {% editable_text "caption", format: 'raw' ... %}
    Gyeongbokgung, Seoul
  {% endeditable_text %}
{% endcapture %}
```
- Use the captured variable later with the `escape` filter:
```html
<p>{{ caption | escape }}</p>
```

`escape` will escape the markup used to make the text editable by Aloha, resulting in something like the following:
![screenshot from 2014-07-12 11 24 18](https://cloud.githubusercontent.com/assets/5531936/3562306/86df721c-09e9-11e4-8bda-d552e568702c.png)

At this point the only solution is to not escape the `editable_text` input, which is unsafe when `format == 'raw'`.

------

From what I can tell the problem is coming from deeper down in the way the captures and editable sections interact. When Locomotive encounters a `capture` it calls `#render` on it and each of the tags inside of it and then assigns that result to the variable. Later when the variable is output (eg. `{{ caption | escape }}`) it runs the value through the filters and displays the result. The problem is that an editable element's Aloha markup is added during the `element.render` phase **prior to being saved to the variable**. By the time the variable is rendered the value already has the Aloha markup hardcoded in and it's not possible to escape only the user-input content.

I'm wondering if this is a separation of concerns problem. It seems that the `Locomotive::Liquid::Tags::Editable::Text` element should either be a data object **or** a functional object, but not both. That is, it should contain the user-inputted contents and other configuration data (eg. `format` or `rows`) but it shouldn't have to worry about how to display itself or create the Aloha markup (or vice versa). Rendering the Aloha markup seems like something that needs to come right at the end of the render chain, anyway, since its tags should wrap the final output value.

I've considered several ugly hacks just to get this working on a fork for the time being but I just can't seem to find any way to move the Aloha markup to the end of the rendering queue. As far as I can tell the Aloha markup relies on `element.id` and `element._index`, but since Locomotive converts the entire document structure to strings rather than using objects it's impossible to get that information after the editable element has been rendered to the variable.

I understand that to change this properly would be a big task and since you're pushing for release of v3 it might not make sense to attempt to tackle this issue. However, if anyone could perhaps provide some feedback or point me in the right direction I might be able to hack together a temporary fix that I could at least use until v3 comes out. Speaking of which, is there any chance v3 will fix this issue?

------

By the way, it also looks like editable files (eg. photos, etc.) can't be edited through the inline editor either - is this true, or am I missing something here?

**Comment by did** [comment]
work-around:

````
{{ page.editable_elements.caption | escape }}
````

or if wrapped by blocks

````
{{ page.editable_elements.content.menu.caption | escape }}
````

This will return the raw content of the editable element.
