### ISSUE TITLE
theme_image_url generated url incorrect for uploaded images

### ISSUE THREAD

**Issue by LouisSayers** [locomotivecms/engine#978]
When I use the backend to upload images, the theme_image_url url generated is incorrect. I've started poking about, and it looks like the problem lies in that the following code block in html.rb is given a complete path/url for the 'input' parameter for images that are uploaded in the backend:

```
def theme_image_url(input)
      return '' if input.nil?

      input = "images/#{input}" unless input.starts_with?('/')

      asset_url(input) #input is good up until this point
end
```
The actual image is defined as follows in the template:
```
{% capture about_us_pic %}{% editable_file "About us photo" %}chi-siamo.jpg{% endeditable_file %}{% endcapture %}
```

Examples of what happens to the urls (locally):
```
/sites/53931181ff16cb5f00000002/theme/sites/53931181ff16cb5f00000002/pages/53931181ff16cb5f00000004/files/Drystorm_homepage.jpg
```
when the correct url should be:
```
/sites/53931181ff16cb5f00000002/pages/53931181ff16cb5f00000004/files/Drystorm_homepage.jpg
```
In production, for s3 the generated url looks like:

```
http://s3-eu-west-1.amazonaws.com/ama.test/sites/53931b606532e27876000002/theme/images/http%3A//s3-eu-west-1.amazonaws.com/ama.test/sites/53931b606532e27876000002/pages/53931b606532e27876000004/files/chi-siamo.jpg
```
When it should be:
```
http://s3-eu-west-1.amazonaws.com/ama.test/sites/53931b606532e27876000002/pages/53931b606532e27876000004/files/chi-siamo.jpg
```

I've monkey patched to solve my specific problem for now as I need to get this work out of the way:

```
module Locomotive
  module Liquid
    module Filters
      module Html
        def theme_image_url(input)
          return '' if input.nil?
          input = "images/#{input}" unless input.starts_with?('/')
          url_is_complete = /^(images\/)?(https?:\/\/|\/sites)/.match(input)

          url_is_complete ? remove_prefix(input) : asset_url(input)
        end

        private
        def remove_prefix(input)
          input.sub(/^images\//, '')
        end
      end
    end
  end
end
```

**Comment by did** [comment]
@LouisSayers I'm very but I'm not sure to understand the issue here. ````theme_image_url``` is only used for, well, theme images. ````{% editable_file .... %}```` are content assets. The 2 have got different urls. 
The thing is that you can't use the ````theme_image_url```` liquid filter with a content asset from the ````{% editable_file %}```` liquid block.
