### ISSUE TITLE
Unused Access Control Modifiers

### ISSUE THREAD

**Issue by benhutton** [locomotivecms/engine#979]
Rubocop picked these up in my project:

https://github.com/locomotivecms/engine/blob/master/mongodb/migrate/20130326201349_rename_entry_to_content_entry.rb#L31

https://github.com/locomotivecms/engine/blob/master/mongodb/migrate/20130621135025_create_editable_texts.rb#L19

Class methods defined on `self` below `private` or `protected` don't actually take those modifiers. 

See here: http://stackoverflow.com/questions/4952980/creating-private-class-method

**Comment by did** [comment]
thanks, good to know! (btw, those migrations files have been removed in v3).
