### ISSUE TITLE
wagon pull adds prepend empty line on js file

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#980]
Hey guys, i just noticed after doing a wagon push and then doing a wagon pull eventually ( not sure if its all the time ) will add an empty line to the beginning of my js file.

![screenshot 2014-08-07 12 08 40](https://cloud.githubusercontent.com/assets/27327/3840815/42e2c3e0-1e23-11e4-9482-6afca2129b29.png)

**Comment by asapp-kv** [comment]
This is happening to my all of my css and js files....

**Comment by did** [comment]
I don't seem to have this behavior with the last versions of both Engine and Wagon.
