### ISSUE TITLE
_ in slug gets replaced by - when pulling from wagon

### ISSUE THREAD

**Issue by hems** [locomotivecms/engine#981]
just created a page ( with children ) on locomotive panel with slug choose_wisely but after doing wagon pull, i got "choose-wisely" folder on my file system.

Now my "choose_wisely" page is acessible via "localhost/choose_wisely" and via "localhost/choose-wisely" but the children page only via "/choose-wisely/child_slug".

**Comment by did** [comment]
do not seem to be an issue in v3 from a local test I did.
